sabbelasichon/typo3-rector

config/typo3-94.yaml
src/Frontend/ContentObject/CallEnableFieldsFromPageRepositoryRector.php
stubs/Frontend/ContentObject/ContentObjectRenderer.php
stubs/Frontend/Page/PageRepository.php
tests/Frontend/Page/CallEnableFieldsFromPageRepositoryRectorTest.php
tests/Frontend/Page/Fixture/call_enable_fields_from_page_repository.php.inc

The public method \TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer->enableFields() has been marked as deprecated
Use PageRepository->enableFields() directly
- Resolves: #1146

[TASK] Add rector to use enableFields from PageRepository directly

---

src/Rector/Annotation/CascadeAnnotationRector.php
tests/Rector/Annotation/AnnotationTest.php
tests/Rector/Annotation/Fixture/cascade_remove.php.inc

Many projects use `@cascade remove` instead of `@cascade` alone.
This patch fixes rewriting these occurences of the annotation to the new namespaced versions.

[TASK] Fix CascadeAnnotationRector for @cascade remove annotations

---

composer.json

When using typo3-rector as composer package i'll get the following error since this commit
c89549be85d1e8ce21e253a7673c44dee09d06a7
`[ERROR] Class 'Symplify\PackageBuilder\Yaml\ParameterInImportResolver' not found`
I think the classmap should be defined in the "autoload" section instead of "autoload-dev".

fix autoloading issue

---

config/typo3-93.php
src/Rector/Backend/Utility/BackendUtilityGetModuleUrlRector.php
stubs/Backend/Utility/BackendUtility.php
tests/Rector/Backend/Utility/BackendUtilityGetModuleUrlRectorTest.php
tests/Rector/Backend/Utility/Fixture/backend_utility_get_module_url.php.inc
tests/Rector/Backend/Utility/Fixture/backend_utility_get_module_url_no_second_param.php.inc

I'm not sure how to migrate the 'buildUriFromModule` deprecation properly.
Happy to get feedback, first real rector I wrote.

[TASK] Use UriBuilder instead of BackendUtility::getModuleUrl

---

.gitignore
composer.json

The .code folder is only for local testing purposes but confuses other contributors
Resolves: #1496

[TASK] Remove misleading .code folder

---

.gitignore
composer.json
rector.php
src/Rector/Core/Database/DatabaseConnectionToDbalRector.php
src/Rector/Core/Html/RteHtmlParserRector.php
src/Rector/Core/Resource/SubstituteResourceFactoryRector.php
src/Rector/Core/Resource/UseMetaDataAspectRector.php
src/Rector/Core/Utility/RefactorIdnaEncodeMethodToNativeFunctionRector.php
src/Rector/Extbase/InjectEnvironmentServiceIfNeededInResponseRector.php
src/Rector/Frontend/Page/RemoveInitMethodFromPageRepositoryRector.php
src/Rector/Misc/AddCodeCoverageIgnoreToMethodRectorDefinitionRector.php
src/Rector/v10/v4/UnifiedFileNameValidatorRector.php
src/Rector/v9/v4/SystemEnvironmentBuilderConstantsRector.php
tests/Rector/Misc/AddCodeCoverageIgnoreToMethodRectorDefinitionRectorTest.php
tests/Rector/Misc/Fixture/code_coverage_ignore.php.inc
utils/phpstan/config/typo3-rector.neon
utils/phpstan/src/Rules/AddCodeCoverageIgnoreForRectorDefinition.php
utils/phpstan/tests/Rules/AddCodeCoverageIgnoreForRectorDefinition/AddCodeCoverageIgnoreForRectorDefinitionTest.php
utils/phpstan/tests/Rules/AddCodeCoverageIgnoreForRectorDefinition/Fixture/MissingCodeCoverageIgnore.php
utils/phpstan/tests/Rules/AddCodeCoverageIgnoreForRectorDefinition/Fixture/SkipWithCodeCoverageIgnore.php
utils/phpstan/tests/Rules/AddSeeDocBlockForRectorClass/AddSeeDocBlockForRectorClassTest.php

For the method getDefinition we do not need a codeCoverage report. To ensure that, we add @codeCoverageIgnore docblock
Resolves: #1493

[TASK] Add @codeCoerageIgnore rule

---

config/v8/typo3-80.php
src/Rector/v8/v0/PrependAbsolutePathToGetFileAbsFileNameRector.php
src/Rector/v8/v0/RefactorRemovedMarkerMethodsFromHtmlParserRector.php
stubs/Core/Imaging/GraphicalFunctions.php
stubs/Core/Utility/GeneralUtility.php
tests/Rector/v8/v0/PrependAbsolutePathToGetFileAbsFileName/Fixture/prepend_absolute_path_to_get_file_abs_filename.php.inc
tests/Rector/v8/v0/PrependAbsolutePathToGetFileAbsFileName/PrependAbsolutePathToGetFileAbsFileNameRectorTest.php

Use GeneralUtility::getFileAbsFileName() instead of GraphicalFunctions->prependAbsolutePath()
Resolves: #388

[TASK] Refactor GraphicalFunctions->prependAbsolutePath()

---

src/Rector/v8/v5/ContentObjectRendererFileResourceRector.php
stubs/Core/TypoScript/TemplateService.php
stubs/Frontend/ContentObject/ContentObjectRenderer.php
stubs/Frontend/Controller/TypoScriptFrontendController.php
tests/Rector/v8/v5/ContentObjectRendererFileResource/ContentObjectRendererFileResourceRectorTest.php
tests/Rector/v8/v5/ContentObjectRendererFileResource/Fixture/tsfe_content_object_renderer.php.inc
tests/Rector/v8/v5/ContentObjectRendererFileResource/Fixture/tsfe_content_object_renderer_in_class.php.inc

[TASK] Refactor method fileResource of ContentObjectRenderer

---

config/v9/typo3-95.php
src/Rector/v9/v5/RefactorPropertiesOfTypoScriptFrontendControllerRector.php
stubs/Frontend/Controller/TypoScriptFrontendController.php
tests/Rector/v9/v5/RefactorPropertiesOfTypoScriptFrontendController/Fixture/refactor_properties_tsfe.php.inc
tests/Rector/v9/v5/RefactorPropertiesOfTypoScriptFrontendController/Fixture/refactor_properties_tsfe_in_class.php.inc
tests/Rector/v9/v5/RefactorPropertiesOfTypoScriptFrontendController/RefactorPropertiesOfTypoScriptFrontendControllerRectorTest.php

[TASK] Refactor deprecated properties of TSFE

---

config/v9/typo3-90.php
src/Rector/v9/v0/RefactorBackendUtilityGetPagesTSconfigRector.php
stubs/Backend/Utility/BackendUtility.php
tests/Rector/v9/v0/RefactorBackendUtilityGetPagesTSconfig/Fixture/refactor_backend_utility_get_pages_tsconfig.php.inc
tests/Rector/v9/v0/RefactorBackendUtilityGetPagesTSconfig/RefactorBackendUtilityGetPagesTSconfigRectorTest.php

- Can only transform calls where rootline is null
Resolves: #948

[TASK] Refactor BackendUtility::getPagesTSconfig where possible

---

typo3.constants.php

Under some circumstances it might happen that TYPO3_COMPOSER_MODE is
already defined.
This change fixes the following notice:
Notice: Constant TYPO3_COMPOSER_MODE already defined in
/vendor/ssch/typo3-rector/typo3.constants.php on line 42

Prevent possible duplicate constant definition

---

templates/rector.php.dist

The configured path to typo3.constants.php file is wrong.
It is now changed to expected location.
This already fixes the following issue for default setups.
Still if packages are installed somewhere else, the path would still be
wrong.
[ERROR] Could not process "*" file, due to:
"File or directory 'typo3.constants.php' not found.".

Fix configured path to typo3.constants.php

---

src/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModulesRector.php
tests/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModules/Fixture/refactor_configure_plugin.php.inc

Adjust code and add test scenario where optional third argument to
configure none cacheable actions is not provided.
As this was not checked beforehand, it would lead to this error:
[ERROR] Could not process "*" file by
"Rector\Core\Rector\AbstractRector", due to:
"Argument 1 passed to Rector\Core\Rector\AbstractRector::getValue() must be an instance of PhpParser\Node\Expr,
null given, called in
vendor/ssch/typo3-rector/src/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModulesRector.php:156".

Don't break if no none cacheable actions are configured

---

src/Rector/v7/v4/DropAdditionalPaletteRector.php
tests/Rector/v7/v4/DropAdditionalPalette/Fixture/no_change_without_additional_palette.php.inc

if no changes to the syntax tree are necessary, we should not alter it, to preserve the code formatting.
this reduces noise in rector output and git logs

[BUGFIX] Preserve formatting of TCA when no changes are necessary

---

src/Rector/v8/v7/MoveForeignTypesToOverrideChildTcaRector.php
tests/Rector/v8/v7/MoveForeignTypesToOverrideChildTca/Fixture/foreign_record_defaults.php.inc
tests/Rector/v8/v7/MoveForeignTypesToOverrideChildTca/Fixture/foreign_selector_fieldTcaOverride.php.inc
tests/Rector/v8/v7/MoveForeignTypesToOverrideChildTca/Fixture/withExtensionManagementUtilityGetFileFieldTcaConfig.php.inc

Following the slack discussion, two additonal cases of https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/8.7/Deprecation-80000-InlineOverrideChildTca.html are handled by the alredy existing rector

Override child tca

---

config/v10/typo3-100.php

* `ssch/typo3-rector`: 0.9.0
* `rector/rector`: 0.9.26
* PHP: 7.4.13
Version 0.9.0 contains an issue regarding nested array configuration of the service `rename_namespace_backend_controller_file_to_filelist_controller_file`. This PR solves the issue by defining the properly nested array.
1. Install Rector:
```bash
composer req --dev ssch/typo3-rector:0.9.0
```
2. Add set `Typo3SetList::TYPO3_104` in generated `rector.php`:
```php
$parameters->set(Option::SETS, [
Typo3SetList::TYPO3_95,
Typo3SetList::TYPO3_104,
]);
```
3. Run Rector:
```bash
vendor/bin/typo3-rector process
```
Now you should see the following error:
```
[ERROR] Invalid service "rename_namespace_backend_controller_file_to_filelist_controller_file": method …
```

[BUGFIX] Correct nested array of service configuration call

---

config/v10/typo3-104.php
tests/Rector/v10/v4/SubstituteObjectManagerGetWithGeneralUtilityMakeInstanceRector/Fixture/substitute_objectmanager_get.php.inc
tests/Rector/v10/v4/SubstituteObjectManagerGetWithGeneralUtilityMakeInstanceRector/Fixture/substitute_objectmanagerinterface_get.php.inc
tests/Rector/v10/v4/SubstituteObjectManagerGetWithGeneralUtilityMakeInstanceRector/SubstituteObjectManagerGetWithGeneralUtilityMakeInstanceRectorTest.php
tests/Rector/v10/v4/SubstituteObjectManagerGetWithGeneralUtilityMakeInstanceRector/config/configured_rule.php

This migration assumes developers already migrated to dependency
injection where possible and useful.
All existing calls will be migrated.
In order to have proper working code, a Services.yaml is necessary.
Relates: #1883

[FEATURE] Migrate ObjectManager->get() to GeneralUtility::makeInstance()

---

.github/workflows/build_scoped_typo3_rector.yaml

This addresses previously mentioned issue, when scoped version is build on PR. It should happen on merge to master or release

do not build scoped version on PR

---

config/v8/tca-87.php
src/Rector/Tca/AbstractTcaRector.php
src/Rector/v8/v6/MigrateLastPiecesOfDefaultExtrasRector.php
src/Rector/v8/v6/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRector.php
tests/Rector/v8/v6/MigrateLastPiecesOfDefaultExtrasRector/Fixture/migrate_moves_nowrap_and_enable-tab.php.inc
tests/Rector/v8/v6/MigrateLastPiecesOfDefaultExtrasRector/Fixture/migrate_wrap_to_columns_override_without_existing_config.php.inc
tests/Rector/v8/v6/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRectorTest/Fixture/migrate_drops_style_pointer_from_show_item.php.inc
tests/Rector/v8/v6/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRectorTest/Fixture/migrate_moves_special_configuration_to_columns_overrides_default_extras.php.inc
tests/Rector/v8/v6/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRectorTest/Fixture/migrate_moves_special_configuration_to_columns_overrides_default_extras_and_merges_existing_default_extras.php.inc
tests/Rector/v8/v6/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRectorTest/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRectorTest.php
tests/Rector/v8/v6/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRectorTest/config/configured_rule.php

fixes #1988 
The tests for the core migration take into account that another migration is run after the one handled here.
To separate responsibilities and keep the code close to the core migration, i chose to adapt the fixtures and add some test-cases to the second rector that ensures that we finally reach the desired state after running both of them.

Move special configuration to columns overrides

---

src/Rector/v9/v4/ConstantsToEnvironmentApiCallRector.php
tests/Rector/v9/v4/ConstantsToEnvironmentApiCallRector/Fixture/environment_constants.php.inc

- Method calls in constants is not allowed. So skip it
Resolves: #2451

[BUGFIX] Skip refactoring for constants

---

src/FileProcessor/Composer/Rector/ExtensionComposerRector.php
src/FileProcessor/TypoScript/Conditions/GlobalStringConditionMatcher.php
src/FileProcessor/TypoScript/Conditions/GlobalVarConditionMatcher.php
src/FileProcessor/TypoScript/Rector/OldConditionToExpressionLanguageTypoScriptRector.php
src/FileProcessor/TypoScript/TypoScriptFileProcessor.php
src/Helper/TcaHelperTrait.php
src/NodeFactory/ImportExtbaseAnnotationIfMissingFactory.php
src/Rector/v10/v0/RefactorIdnaEncodeMethodToNativeFunctionRector.php
src/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php
src/Rector/v7/v4/DropAdditionalPaletteRector.php
src/Rector/v7/v5/UseExtPrefixForTcaIconFileRector.php
src/Rector/v8/v6/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRector.php
src/Rector/v9/v3/ValidateAnnotationRector.php
src/Rector/v9/v4/SystemEnvironmentBuilderConstantsRector.php
src/Rector/v9/v5/ExtbaseCommandControllerToSymfonyCommand/AddCommandsToReturnRector.php
utils/phpstan/src/Type/ContextGetAspectDynamicReturnTypeExtension.php

This pull request aims to replace old code snippets with new ones.
Doing so is desirable, because it leads to more concise and semantically better speaking code.
The following upgrades have taken place (where applicable):
- replace `strpos` with `str_contains`, in cases where it has been used to check if a string contains another string
- replace `switch` and `if/else`-chains with `match`-expressions, in cases where they have been used to return different values based on some input value
- replace anonymous functions with arrow functions, in cases where they immediately return a result and don't do further processing/checks

Make extensive use of PHP8/7.4

---

templates/rector.php.dist

old path was Ssch\TYPO3Rector\FileProcessor\TypoScript\Visitors\FileIncludeToImportStatementVisitor

fix path and classname to FileIncludeToImportStatementTypoScriptRector

---

config/v11/typo3-115.php
src/Rector/v11/v5/ReplaceTSFEATagParamsCallOnGlobalsRector.php
stubs/TYPO3/CMS/Frontend/ContentObject/ContentObjectRenderer.php
tests/Rector/v11/v5/ReplaceTSFEATagParamsCallOnGlobalsRector/Fixture/fixture.php.inc
tests/Rector/v11/v5/ReplaceTSFEATagParamsCallOnGlobalsRector/ReplaceTSFEATagParamsCallOnGlobalsRectorTest.php
tests/Rector/v11/v5/ReplaceTSFEATagParamsCallOnGlobalsRector/config/configured_rule.php

[FEAT] Replace TSFE->ATagParams calls

---

config/v11/typo3-115.php
src/Rector/v11/v5/HandleCObjRendererATagParamsMethodRector.php
tests/Rector/v11/v5/HandleCObjRendererATagParamsMethodRector/Fixture/fixture.php.inc
tests/Rector/v11/v5/HandleCObjRendererATagParamsMethodRector/HandleCObjRendererATagParamsMethodRectorTest.php
tests/Rector/v11/v5/HandleCObjRendererATagParamsMethodRector/config/configured_rule.php

feat: handle ContentObjectRenderer->getAtagParams()

---

.gitattributes

Hi @sabbelasichon, currently, the longest time to downgrade on `rector` scoping is typo3-rector package. Do you think `stubs` directory needs to be included in the dist? If no, I think it can be registered as export-ignore in `.gitattributes`

Add stubs to export-ignore

---

src/Rector/v11/v4/ProvideCObjViaMethodRector.php

This is an attempt to make `AbstractRector` slimmer and lighter :) services should be injected only when needed. No just because 10 rules use them.
See Rector core change https://github.com/rectorphp/rector-src/pull/1298

[DX] Make visibility manipulator explicit inject

---

config/v11/typo3-110.php
src/NodeFactory/InjectMethodFactory.php
src/Rector/v11/v0/ReplaceInjectAnnotationWithMethodRector.php
src/Rector/v9/v0/InjectAnnotationRector.php
stubs/TYPO3/CMS/Extbase/Annotation/Inject.php
tests/Rector/v11/v0/ReplaceInjectAnnotationWithMethodRector/Fixture/fixture.php.inc
tests/Rector/v11/v0/ReplaceInjectAnnotationWithMethodRector/ReplaceInjectAnnotationWithMethodRectorTest.php
tests/Rector/v11/v0/ReplaceInjectAnnotationWithMethodRector/Source/InjectionClass.php
tests/Rector/v11/v0/ReplaceInjectAnnotationWithMethodRector/Source/ShortInjectionClass.php
tests/Rector/v11/v0/ReplaceInjectAnnotationWithMethodRector/config/configured_rule.php

feat: replace TYPO3 inject annotations with setter methods

---

.github/workflows/weekly_pull_requests.yaml
composer.json

@sabbelasichon @TomasVotruba based on my pull request on rector-src at https://github.com/rectorphp/rector-src/pull/1551#issue-1087504280
this is a weekly automatic PR to verify that `typo3-rector/config` directory is always compatible with php 7.1
@sabbelasichon for note ,current weekly error on `Update composer packages` task is unrelated:
https://github.com/sabbelasichon/typo3-rector/runs/4571935671?check_suite_focus=true#step:5:25
```
Script @php vendor/bin/rector add-composer-typo3-extensions-to-config handling the update-composer-packages event returned with error code 137
Script @update-composer-packages was called via update-composer
```

Update weekly make config/ directory files compatible with php 7.1

---

src/Rector/v11/v3/UseLanguageTypeForLanguageFieldColumnRector.php
tests/Rector/v11/v3/UseLanguageTypeForLanguageFieldColumnRector/Fixture/skip_language_type.php.inc
tests/Rector/v11/v3/UseLanguageTypeForLanguageFieldColumnRector/Fixture/use_language_type.php.inc
tests/Rector/v11/v3/UseLanguageTypeForLanguageFieldColumnRector/UseLanguageTypeForLanguageFieldColumnRectorTest.php
tests/Rector/v11/v3/UseLanguageTypeForLanguageFieldColumnRector/config/configured_rule.php
utils/generator/src/Command/Typo3GenerateCommand.php
utils/generator/templates/src/Rector/__Major__/__Minor__/__Name__.php

Add rector for language TCA type

---

composer.json
src/FileProcessor/TypoScript/Rector/ExtbasePersistenceTypoScriptRector.php
src/Template/TemplateFinder.php
templates/maker/Extbase/Persistence.tpl
tests/FileProcessor/TypoScript/Expected/Extbase.php.inc
tests/FileProcessor/TypoScript/Fixture/Extbase/002_extbase_persistence.txt
tests/FileProcessor/TypoScript/Source/Address.php

@TomasVotruba Could get rid of VarExporter by reformatting after prettyPrinting. So one dependency less.
Resolves: #2794

Do not use VarExporter anymore

---

.github/workflows/phpstan.yaml
composer.json
src/FileProcessor/Yaml/Form/Rector/TranslationFileRector.php
src/Rector/v9/v5/ExtbaseCommandControllerToSymfonyCommandRector.php
tests/FileProcessor/TypoScript/Fixture/TypoScript/conditions.typoscript

- bump to stable gemlich, since no Symfony 6 is supported
- bump helmich deps to Symfony 6 compatible one

[update] Use stable Hemlich with Symfony 6 support

---

composer.json
utils/composer-packages/tests/Rector/AddPackageVersionRector/config/configured_rule.php

Now rector-src and this package use the same tagger version, so we can drop the alias :slightly_smiling_face:

bump deps to remove dev-main

---

src/Rector/v10/v0/BackendUtilityGetViewDomainToPageRouterRector.php
src/Rector/v10/v0/ForceTemplateParsingInTsfeAndTemplateServiceRector.php
src/Rector/v10/v1/RefactorInternalPropertiesOfTSFERector.php
src/Rector/v10/v1/SendNotifyEmailToMailApiRector.php
src/Rector/v10/v2/InjectEnvironmentServiceIfNeededInResponseRector.php
src/Rector/v11/v0/ForwardResponseInsteadOfForwardMethodRector.php
src/Rector/v11/v5/FlexFormToolsArrayValueByPathRector.php
src/Rector/v8/v1/RefactorVariousGeneralUtilityMethodsRector.php
src/Rector/v8/v1/TypoScriptFrontendControllerCharsetConverterRector.php
src/Rector/v8/v5/ContentObjectRendererFileResourceRector.php
src/Rector/v8/v7/BackendUtilityGetRecordRawRector.php
src/Rector/v8/v7/BackendUtilityGetRecordsByFieldToQueryBuilderRector.php
src/Rector/v8/v7/RefactorGraphicalFunctionsTempPathAndCreateTemSubDirRector.php
src/Rector/v8/v7/RefactorPrintContentMethodsRector.php
src/Rector/v9/v0/DatabaseConnectionToDbalRector.php
src/Rector/v9/v0/SubstituteCacheWrapperMethodsRector.php
src/Rector/v9/v0/UseLogMethodInsteadOfNewLog2Rector.php
src/Rector/v9/v2/PageNotFoundAndErrorHandlingRector.php
src/Rector/v9/v3/CopyMethodGetPidForModTSconfigRector.php
src/Rector/v9/v4/RefactorDeprecatedConcatenateMethodsPageRendererRector.php
src/Rector/v9/v4/TemplateGetFileNameToFilePathSanitizerRector.php
src/Rector/v9/v4/UseClassSchemaInsteadReflectionServiceMethodsRector.php
src/Rector/v9/v4/UseGetMenuInsteadOfGetFirstWebPageRector.php
src/Rector/v9/v5/RefactorProcessOutputRector.php

To be able to remove deprecated methods addNodes?(?:Before|After)Node on AbstractRector, ref https://github.com/rectorphp/rector-src/pull/1879

Use $this->nodesToAddCollector-> call directly for addNodes?(?:Before|After)Node call

---

README.md
composer.json
docs/README.md

Hi Sebastian,
this PR is a suggestion to align your package documentation with the recently introduced [TYPO3 documentation standards](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/FileStructure.html).
I mainly reworked some content, moved your documentation TOC to /docs, added some badges in README and additional sources (TER, repository and docs.typo3.org) in composer.json.
Greetings, Alex
Relates: TYPO3-Documentation/T3DocTeam#182
Relates: TYPO3-Documentation/T3DocTeam#185

[TASK] Align with new TYPO3 documentation standards

---

composer.json

Fixing error in tests
```
380) Ssch\TYPO3Rector\Rules\Tests\Rector\Misc\AddCodeCoverageIgnoreToMethodRectorDefinitionRectorTest::test with data set #0 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
Symfony\Component\Config\Exception\LoaderLoadException: Call to undefined method "Rector\Config\RectorConfig::rule()" in /home/runner/work/rector-src/rector-src/vendor/rector/rector-nette/config/config.php (which is being imported from "/home/runner/work/rector-src/rector-src/vendor/rector/rector-src/src/Kernel/../../config/config.php").
```

Fix test Call to undefined method Rector\Config\RectorConfig::rule() error

---

ecs.php
rector.php
utils/composer-packages/config/config.php

Since 0.12.21 it is possible to use lighter RectorConfig class, that contains full method autocomplete and validation.
This way we have less dependency on Symfony and easier setup :+1:

Make use of RectorConfig and ECSConfig

---

phpstan.neon
src/Rector/Migrations/RenameClassMapAliasRector.php
src/Rector/v10/v4/UseIconsFromSubFolderInIconRegistryRector.php
src/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector.php
src/Rector/v11/v5/SubstituteGetIconFactoryAndGetPageRendererFromModuleTemplateRector.php
src/Rector/v8/v5/MoveLanguageFilesFromLocallangToResourcesRector.php
src/Rector/v8/v6/MoveRequestUpdateOptionFromControlToColumnsRector.php
src/Rector/v8/v6/MoveTypeGroupSuggestWizardToSuggestOptionsRector.php
src/Rector/v9/v2/PageNotFoundAndErrorHandlingRector.php
src/Rector/v9/v3/MoveLanguageFilesFromExtensionLangRector.php
src/Rector/v9/v3/ValidateAnnotationRector.php
utils/composer-packages/src/ComposerPackageParser.php

I've noticed we have a hacky services in Rector, that can be now solved in much cleaner way directly in the rule.
There are just 4 places that use it, 3 of them here. Let's clean :soap:  :)

[DX] Remove dependency on NodesToReplaceCollector, return nodes directly in transparent way instead

---

composer.json
src/FileProcessor/TypoScript/TypoScriptFileProcessor.php

I'm cleaning Rector from a code-formatting, to make it less widespread :) and better focused on refactoring itself
Ref https://github.com/rectorphp/rector-src/pull/2378

[DX] Remove TypoScriptFileProcessor dependency on editorconfig, rather use the current file spacing setup

---

.gitignore
composer.json
phpstan.neon
src/Rector/v9/v5/ExtbaseCommandControllerToSymfonyCommandRector.php
tests/bootstrap-phpstan.php
tests/bootstrap.php

Native php-parser is loaded from phpstan, which is now older version 4.14.
To test php-parser 5.0-dev, we need to preload if from local vendor.
See https://github.com/rectorphp/rector-src/pull/2437

[composer] remove php-cs-fixer, already in ECS, fix newer php-parser for tests

---

config/v12/typo3-120.php
stubs/TYPO3/CMS/Core/Messaging/AbstractMessage.php
stubs/TYPO3/CMS/Core/Messaging/FlashMessage.php
stubs/TYPO3/CMS/Core/Type/ContextualFeedbackSeverity.php
stubs/TYPO3/CMS/Reports/Status.php
tests/Rector/v12/v0/typo3/ReplaceSeveritiesFlashMessageAndReportsRector/Fixture/fixture.php.inc
tests/Rector/v12/v0/typo3/ReplaceSeveritiesFlashMessageAndReportsRector/ReplaceSeveritiesFlashMessageAndReportsRector.php
tests/Rector/v12/v0/typo3/ReplaceSeveritiesFlashMessageAndReportsRector/config/configured_rule.php

TASK: Add rector configuration

---

src/FileProcessor/Yaml/Form/FormYamlFileProcessor.php

this PR resolves the Issue 'Tags support is not enabled. Enable the "Yaml::PARSE_CUSTOM_TAGS"' when using custom tags in yaml.

[BUGFIX] enable parsing custom tags in yaml

---

config/v12/typo3-120.php
src/Rector/v12/v0/typo3/ImplementSiteLanguageAwareInterfaceRector.php
stubs/TYPO3/CMS/Core/Site/SiteLanguageAwareInterface.php
stubs/TYPO3/CMS/Core/Site/SiteLanguageAwareTrait.php
tests/Rector/v12/v0/typo3/ImplementSiteLanguageAwareInterfaceRector/Fixture/add_interface_only.php.inc
tests/Rector/v12/v0/typo3/ImplementSiteLanguageAwareInterfaceRector/Fixture/everything_ok.php.inc
tests/Rector/v12/v0/typo3/ImplementSiteLanguageAwareInterfaceRector/Fixture/remove_trait_and_add_interface.php.inc
tests/Rector/v12/v0/typo3/ImplementSiteLanguageAwareInterfaceRector/Fixture/remove_trait_only.php.inc
tests/Rector/v12/v0/typo3/ImplementSiteLanguageAwareInterfaceRector/ImplementSiteLanguageAwareInterfaceRectorTest.php
tests/Rector/v12/v0/typo3/ImplementSiteLanguageAwareInterfaceRector/config/configured_rule.php

TASK: Add SiteLanguageAwareInterface

---

config/v11/typo3-113.php
src/Rector/v11/v3/typo3/UseNormalizedParamsToGetRequestUrlRector.php
stubs/Psr/Http/Message/ServerRequestInterface.php
stubs/TYPO3/CMS/Extbase/Mvc/Controller/ActionController.php
stubs/TYPO3/CMS/Extbase/Mvc/Request.php
tests/Rector/v11/v3/typo3/UseNormalizedParamsToGetRequestUrlRector/Fixture/fixture.php.inc
tests/Rector/v11/v3/typo3/UseNormalizedParamsToGetRequestUrlRector/UseNormalizedParamsToGetRequestUrlRectorTest.php
tests/Rector/v11/v3/typo3/UseNormalizedParamsToGetRequestUrlRector/config/configured_rule.php

TASK: Add UseNormalizedParamsToGetRequestUrlRector

---

config/v11/typo3-110.php
src/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php
tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector/Fixture/extbase_controller_actions_return_response_interface.php.inc
tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector/config/configured_rule.php

TASK: Make rector configurable

---

config/v12/tca-120.php
src/Rector/v12/v0/tca/RemoveTableLocalPropertyRector.php
tests/Rector/v12/v0/tca/RemoveTableLocalPropertyRector/Fixture/fixture.php.inc
tests/Rector/v12/v0/tca/RemoveTableLocalPropertyRector/RemoveTableLocalPropertyRectorTest.php
tests/Rector/v12/v0/tca/RemoveTableLocalPropertyRector/config/configured_rule.php

TASK: Add rule RemoveTableLocalPropertyRector

---

composer.json
src/Rector/v12/v0/tca/MigrateRequiredFlagRector.php
tests/Rector/v10/v0/DatabaseRecordListRector/Fixture/database_record_list_renaming.php
tests/Rector/v12/v0/tca/MigrateRequiredFlagRector/Fixture/fixture.php.inc

fix: prevent double required config key in TCA

---

docs/all_rectors_overview.md
src/Rector/v12/v0/flexform/RemoveElementTceFormsRector.php
tests/Rector/v12/v0/flexform/RemoveElementTceFormsRector/Fixture/fixture.xml.inc
tests/Rector/v12/v0/flexform/RemoveElementTceFormsRector/Fixture/flexforms_no_change.xml.inc
tests/Rector/v12/v0/flexform/RemoveElementTceFormsRector/RemoveElementTceFormsRectorTest.php
tests/Rector/v12/v0/flexform/RemoveElementTceFormsRector/config/configured_rule.php

[TASK] Add RemoveElementTceFormsRector

---

config/v12/flexform-123.php
src/Rector/v12/v3/flexform/MigrateItemsToIndexedArrayKeysForFlexFormItemsRector.php
tests/Rector/v12/v3/flexform/MigrateItemsToIndexedArrayKeysForFlexFormItemsRector/Fixture/fixture.xml.inc
tests/Rector/v12/v3/flexform/MigrateItemsToIndexedArrayKeysForFlexFormItemsRector/Fixture/fixture_check.xml.inc
tests/Rector/v12/v3/flexform/MigrateItemsToIndexedArrayKeysForFlexFormItemsRector/Fixture/fixture_radio.xml.inc
tests/Rector/v12/v3/flexform/MigrateItemsToIndexedArrayKeysForFlexFormItemsRector/Fixture/fixture_with_all_keys.xml.inc
tests/Rector/v12/v3/flexform/MigrateItemsToIndexedArrayKeysForFlexFormItemsRector/MigrateItemsToIndexedArrayKeysForFlexFormItemsRectorTest.php
tests/Rector/v12/v3/flexform/MigrateItemsToIndexedArrayKeysForFlexFormItemsRector/config/configured_rule.php

This Rector Rule is sponsored by UDG Rhein-Main GmbH! Thank you!
Resolves: #3399

[TASK] Add MigrateItemsIndexedKeysToAssociativeRector

---

src/Rector/v12/v0/flexform/MigrateEvalIntAndDouble2ToTypeNumberFlexFormRector.php
src/Rector/v12/v0/tca/MigrateEvalIntAndDouble2ToTypeNumberRector.php
tests/Rector/v12/v0/flexform/MigrateEvalIntAndDouble2ToTypeNumberFlexFormRector/Fixture/fixture.xml.inc
tests/Rector/v12/v0/tca/MigrateEvalIntAndDouble2ToTypeNumberRector/Fixture/fixture.php.inc

An early return is added, in case the eval list doesn't contain neither `int` nor `double`.
Fixes: #3923

[BUGFIX] Prevent false migration from type input to type number

---

src/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector.php
tests/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector/Fixture/query_logical_and_with_variables_as_arguments_migrated.php.inc

I've added a test to ensure already migrated logicalAnd do not change if running the rector multiple times.

Add test for already migrated logicalAnd

---

config/v12/tca-120.php
src/Rector/v12/v0/tca/MigrateRenderTypeColorpickerToTypeColorRector.php
tests/Rector/v12/v0/tca/MigrateRenderTypeColorpickerToTypeColorRector/Fixture/fixture.php.inc
tests/Rector/v12/v0/tca/MigrateRenderTypeColorpickerToTypeColorRector/MigrateRenderTypeColorpickerToTypeColorRectorTest.php
tests/Rector/v12/v0/tca/MigrateRenderTypeColorpickerToTypeColorRector/config/configured_rule.php

[FEATURE] Add MigrateRenderTypeColorpickerToTypeColorRector

---

src/Rector/v8/v7/RefactorPrintContentMethodsRector.php
tests/Rector/v8/v7/RefactorPrintContentMethodsRector/Fixture/refactor_print_method_task_module_controller_rector.php.inc

TASK: Return nodes instead of using NodesToAddCollector

---

src/Contract/Helper/Database/Refactorings/DatabaseConnectionToDbalRefactoring.php
src/Helper/Database/Refactorings/ConnectionCallFactory.php
src/Helper/Database/Refactorings/DatabaseConnectionExecInsertQueryRefactoring.php
src/Helper/Database/Refactorings/DatabaseConnectionExecTruncateTableRefactoring.php
src/Rector/v9/v0/DatabaseConnectionToDbalRector.php
tests/Rector/Core/Database/Fixture/exec_insert_query.php.inc
tests/Rector/Core/Database/Fixture/exec_truncate_query.php.inc

TASK: Return node for DatabaseConnectionToDbalRector

---

src/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector.php

TASK: Refactor SubstituteBackendTemplateViewWithModuleTemplateRector

---

config/v10/typo3-100.php
config/v10/typo3-101.php
config/v10/typo3-104.php
config/v11/typo3-110.php
config/v11/typo3-114.php
config/v11/typo3-115.php
config/v12/typo3-123.php
config/v8/typo3-84.php
src/FileProcessor/TypoScript/Conditions/GlobalVarConditionMatcher.php
src/Rector/v12/v3/typo3/MigrateMagicRepositoryMethodsRector.php
stubs/TYPO3/CMS/Extbase/Persistence/ExampleRepository.php
tests/FileProcessor/TypoScript/config/configured_rule.php
tests/Rector/v10/v4/SubstituteObjectManagerGetWithGeneralUtilityMakeInstanceRector/config/configured_rule.php
tests/Rector/v12/v0/typo3/ReplaceExpressionBuilderMethodsRector/config/configured_rule.php
tests/Rector/v12/v0/typo3/ReplaceTSFEWithContextMethodsRector/config/configured_rule.php
tests/Rector/v12/v3/typo3/MigrateMagicRepositoryMethodsRector/Fixture/fixture.php.inc
tests/Rector/v12/v3/typo3/MigrateMagicRepositoryMethodsRector/MigrateMagicRepositoryMethodsRectorTest.php
tests/Rector/v12/v3/typo3/MigrateMagicRepositoryMethodsRector/config/configured_rule.php
tests/Rector/v9/v4/AdditionalFieldProviderRector/config/configured_rule.php

[FEATURE] Provide migration for extbase magic methods

---

composer.json
phpunit.xml

Also use a version-specific XSD in the PHPUnit configuration file to allow migrations.

[TASK] Bump the development dependencies

---

composer.json

The Symfony development dependencies do not need to be in sync with the TYPO3 Core Symfony dependencies as they are not installed in projects that have this package as a dependency. Instead, it suffices that the set of development dependencies is installable (and works) with the PHP versions we support.

[TASK] Narrow down the Symfony development dependencies

---

config/replace-vhs.php
src/FileProcessor/Fluid/Rector/vhs/ReplaceExtensionPathRelativeFluidRector.php
src/FileProcessor/Fluid/Rector/vhs/ReplaceFormatJsonEncodeFluidRector.php
src/FileProcessor/Fluid/Rector/vhs/ReplaceLFluidRector.php
src/FileProcessor/Fluid/Rector/vhs/ReplaceMediaImageFluidRector.php
src/FileProcessor/Fluid/Rector/vhs/ReplaceOrFluidRector.php
src/FileProcessor/Fluid/Rector/vhs/ReplaceUriImageFluidRector.php
src/FileProcessor/Fluid/Rector/vhs/ReplaceVariableSetFluidRector.php
src/Set/Extension/VhsSetList.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceFormatJsonEncodeFluidRector/Fixture/fixture.html.inc
tests/FileProcessor/Fluid/Rector/vhs/ReplaceFormatJsonEncodeFluidRector/ReplaceFormatJsonEncodeFluidRectorTest.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceFormatJsonEncodeFluidRector/config/configured_rule.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceLFluidRector/Fixture/fixture.html.inc
tests/FileProcessor/Fluid/Rector/vhs/ReplaceLFluidRector/ReplaceLFluidRectorTest.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceLFluidRector/config/configured_rule.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceMediaImageFluidRector/Fixture/fixture.html.inc
tests/FileProcessor/Fluid/Rector/vhs/ReplaceMediaImageFluidRector/ReplaceMediaImageFluidRectorTest.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceMediaImageFluidRector/config/configured_rule.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceOrFluidRector/Fixture/fixture.html.inc
tests/FileProcessor/Fluid/Rector/vhs/ReplaceOrFluidRector/ReplaceOrFluidRectorTest.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceOrFluidRector/config/configured_rule.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceUriImageFluidRector/Fixture/fixture.html.inc
tests/FileProcessor/Fluid/Rector/vhs/ReplaceUriImageFluidRector/ReplaceUriImageFluidRectorTest.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceUriImageFluidRector/config/configured_rule.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceVariableSetFluidRector/Fixture/fixture.html.inc
tests/FileProcessor/Fluid/Rector/vhs/ReplaceVariableSetFluidRector/ReplaceVariableSetFluidRectorTest.php
tests/FileProcessor/Fluid/Rector/vhs/ReplaceVariableSetFluidRector/config/configured_rule.php

* v:extension.path.relative -> f:uri.resource
* v:format.json.encode -> f:format.json
* v:media.image -> f:media.image
* v:uri.image -> f:uri.image
* v:l -> f:translate
* v:variable.set -> f:variable
* v:or -> inline ternary operator
t.b.c.

[FEATURE] Provide rules to migrate EXT:vhs viewhelpers

---

rules/TYPO312/v0/MigrateInputDateTimeRector.php
tests/Rector/v12/v0/tca/MigrateInputDateTimeRector/Fixture/fixture.php.inc

[BUGFIX] Fix wrong eval removal on TCA datetime migration

---

src/Rector/AbstractTcaRector.php

* AbstractTcaRector::removeArrayItemFromArrayByKey

[DOCS] Improve PHP doc comments

---

config/v12/tca-120.php
rules/TYPO312/v0/MigrateRenderTypeInputLinkToTypeLinkRector.php
src/Rector/AbstractTcaRector.php
tests/Rector/v12/v0/MigrateRenderTypeInputLinkToTypeLinkRector/Fixture/fixture.php.inc
tests/Rector/v12/v0/MigrateRenderTypeInputLinkToTypeLinkRector/Fixture_configurable/fixture.php.inc
tests/Rector/v12/v0/MigrateRenderTypeInputLinkToTypeLinkRector/MigrateRenderTypeInputLinkToTypeLinkRectorConfigurableTest.php
tests/Rector/v12/v0/MigrateRenderTypeInputLinkToTypeLinkRector/MigrateRenderTypeInputLinkToTypeLinkRectorTest.php
tests/Rector/v12/v0/MigrateRenderTypeInputLinkToTypeLinkRector/config/configured_rule.php
tests/Rector/v12/v0/MigrateRenderTypeInputLinkToTypeLinkRector/config/configured_rule_configurable.php

Needed to extend the AbstractTcaRector class to allow mixed data as expected value to support e.g. boolean values
Resolves: #3547

[FEATURE] New TCA type "link"

---

bin/typo3-init.php

Some rules like the ExtEmConfRector need the root files to work

[TASK] Include Extension root files for Rector to parse

---

docs/all_rectors_overview.md
rules/TYPO310/v0/UseTwoLetterIsoCodeFromSiteLanguageRector.php
rules/TYPO310/v3/SubstituteResourceFactoryRector.php
rules/TYPO310/v4/UseFileGetContentsForGetUrlRector.php

This fixes 3 typos in the descriptions of Rector rules and in the aggregated documentation.

Fix typos in Rector descriptions

---

rules/TYPO311/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php
rules/TYPO312/v2/MigrateGeneralUtilityGPMergedRector.php
stubs/TYPO3/CMS/Core/Http/RedirectResponse.php
tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector/Fixture/extbase_controller_actions_return_response_interface.php.inc
tests/Rector/v12/v0/MoveAllowTableOnStandardPagesToTCAConfigurationRector/MoveAllowTableOnStandardPagesToTCAConfigurationRectorTest.php
utils/generator/src/ValueObject/TcaRectorType.php
utils/generator/src/ValueObject/Typo3RectorType.php

[BUGFIX] Do not add return statement if already of type ResponseInterface

---

config/v11/typo3-115.php
rules/TYPO311/v5/RemoveTypeHintViewInterfaceRector.php
tests/Rector/v11/v5/RemoveTypeHintViewInterfaceRector/Fixture/already_migrated.php.inc
tests/Rector/v11/v5/RemoveTypeHintViewInterfaceRector/Fixture/fixture.php.inc
tests/Rector/v11/v5/RemoveTypeHintViewInterfaceRector/Fixture/standalone_view.php.inc
tests/Rector/v11/v5/RemoveTypeHintViewInterfaceRector/RemoveTypeHintViewInterfaceRectorTest.php
tests/Rector/v11/v5/RemoveTypeHintViewInterfaceRector/config/configured_rule.php

[FEATURE] Add RemoveTypeHintViewInterfaceRector

---

config/v13/typo3-130.php
rules/TYPO313/v0/MigrateAddPageTSConfigToPageTsConfigFileRector.php
src/ComposerExtensionKeyResolver.php
stubs/TYPO3/CMS/Core/Utility/ExtensionManagementUtility.php
tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/extension1/page.tsconfig
tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/extension2/page.tsconfig
tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/extension3/page.tsconfig
tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Fixture/extension1/ext_localconf.php.inc
tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Fixture/extension2/ext_localconf.php.inc
tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Fixture/extension3/ext_localconf.php.inc
tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/MigrateAddPageTSConfigToPageTsConfigFileRectorTest.php
tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/config/configured_rule.php

[FEATURE] Add MigrateAddPageTSConfigToPageTsConfigFileRector

---

templates/rector.php.dist

Importing classes in Configuration was possible with older TYPO3 versions already.
Resolves: #2644

[TASK] Import classes possible since TYPO3 11.4

---

rules/TYPO312/v0/MoveAllowTableOnStandardPagesToTCAConfigurationRector.php
tests/Rector/v12/v0/MoveAllowTableOnStandardPagesToTCAConfigurationRector/Assertions/tx_table_one.php.inc
tests/Rector/v12/v0/MoveAllowTableOnStandardPagesToTCAConfigurationRector/Assertions/tx_table_two.php.inc
tests/Rector/v12/v0/MoveAllowTableOnStandardPagesToTCAConfigurationRector/Fixture/ext_tables.php.inc
tests/Rector/v12/v0/MoveAllowTableOnStandardPagesToTCAConfigurationRector/MoveAllowTableOnStandardPagesToTCAConfigurationRectorTest.php

currently if you have a config like this:
````php
ExtensionManagementUtility::allowTableOnStandardPages('tx_table_one,tx_table_two');
````
That will create a file like this:
`Configuration/TCA/Overrides/tx_table_one,tx_table_two.php`
With this PR it will create 2 files instead.

[BUGFIX] fix usages of allowTableOnStandardPages with mutliple tablenames in one string

---

config/config.php

given:
file in `/app/src/extensions/aus_project/ext_tables.php` with content:
````php
<?php
\TYPO3\CMS\Core\Utility\ExtensionManagementUtility::allowTableOnStandardPages('tx_ausproject_domain_model_slide,tx_ausproject_domain_model_teaser');
````
running `rector process --debug src/extensions/aus_project/ext_tables.php` in /app directory.
Producess:
````
[ERROR] Could not process "src/extensions/aus_project/ext_tables.php" file, due to:
"System error: "Unable to create a directory at /src/extensions/aus_project/Configuration/TCA/Overrides.
mkdir(): Permission denied"
Stack trace:
#0 vendor/league/flysystem/src/Local/LocalFilesystemAdapter.php(297):
League\Flysystem\UnableToCreateDirectory::atLocation('/src/extensions...', 'mkdir(): Permis...')
#1 …
```

[BUGFIX] fix FilesystemInterface prefix

---

config/config.php

[BUGFIX] Use absolute file path without project prefix

---

config/typo3-13.php
config/v13/typo3-133.php
rules/TYPO313/v3/MigrateViewHelperRenderStaticRector.php
stubs/TYPO3Fluid/Fluid/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php
stubs/TYPO3Fluid/Fluid/Core/ViewHelper/Traits/CompileWithRenderStatic.php
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/Fixture/CallRenderChildrenClosureViewHelper.php.inc
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/Fixture/ContentArgumentNamePropertyViewHelper.php.inc
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/Fixture/ImplicitContentArgumentNameViewHelper.php.inc
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/Fixture/NonStaticViewHelper.php.inc
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/Fixture/PassRenderChildrenClosureViewHelper.php.inc
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/Fixture/ResolveContentArgumentNameViewHelper.php.inc
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/Fixture/StaticViewHelper.php.inc
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/Fixture/UseArgumentViewHelper.php.inc
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/Fixture/UseRenderingContextViewHelper.php.inc
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/MigrateViewHelperRenderStaticRectorTest.php
tests/Rector/v13/v3/MigrateViewHelperRenderStaticRector/config/configured_rule.php

This rector rule covers the majority of use cases where the now deprecated `renderStatic()` is used in Fluid ViewHelper classes. It's the same rule that has been used in the TYPO3 Core patch that migrated all existing ViewHelpers to `render()`. There were some edge cases in the TYPO3 Core which weren't covered, but those are rather old and don't follow recent best practices.
Core Patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/85834

[FEATURE] Add MigrateViewHelperRenderStaticRector

---

config/v12/typo3-120.php
ecs.php
rules/TYPO312/v0/MigrateBackendModuleRegistrationRector.php
src/Helper/ArrayUtility.php
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Assertions/beuser/Configuration/Backend/Modules.php
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Assertions/extbase/Configuration/Backend/Modules.php
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Assertions/extension1/Configuration/Backend/Modules.php
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Assertions/install/Configuration/Backend/Modules.php
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Assertions/setup/Configuration/Backend/Modules.php
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Assertions/viewpage/Configuration/Backend/Modules.php
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Fixture/beuser/ext_tables.php.inc
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Fixture/extbase/ext_tables.php.inc
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Fixture/extension1/ext_tables.php.inc
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Fixture/install/ext_tables.php.inc
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Fixture/setup/ext_tables.php.inc
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Fixture/viewpage/ext_tables.php.inc
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/MigrateBackendModuleRegistrationRectorTest.php
tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/config/configured_rule.php

[FEATURE] Add MigrateBackendModuleRegistrationRector

---

config/v12/typo3-120.php
rules/TYPO312/v0/MigrateContentObjectRendererGetTypoLinkUrlRector.php
stubs/TYPO3/CMS/Core/Utility/HttpUtility.php
stubs/TYPO3/CMS/Frontend/ContentObject/ContentObjectRenderer.php
tests/Rector/v12/v0/MigrateContentObjectRendererGetTypoLinkUrlRector/Fixture/fixture.php.inc
tests/Rector/v12/v0/MigrateContentObjectRendererGetTypoLinkUrlRector/MigrateContentObjectRendererGetTypoLinkUrlRectorTest.php
tests/Rector/v12/v0/MigrateContentObjectRendererGetTypoLinkUrlRector/config/configured_rule.php

[FEATURE] Add MigrateContentObjectRendererGetTypoLinkUrlRector

---

rules/CodeQuality/General/MethodGetInstanceToMakeInstanceCallRector.php
rules/TYPO310/v0/RemoveFormatConstantsEmailFinisherRector.php
rules/TYPO311/v2/SubstituteEnvironmentServiceWithApplicationTypeRector.php
rules/TYPO311/v3/SubstituteMethodRmFromListOfGeneralUtilityRector.php
rules/TYPO311/v4/AddSetConfigurationMethodToExceptionHandlerRector.php
rules/TYPO311/v4/UseNativeFunctionInsteadOfGeneralUtilityShortMd5Rector.php
rules/TYPO311/v5/SubstituteGetIconFactoryAndGetPageRendererFromModuleTemplateRector.php
rules/TYPO312/v0/ChangeExtbaseValidatorsRector.php
rules/TYPO312/v0/MigrateContentObjectRendererGetTypoLinkUrlRector.php
rules/TYPO312/v0/MigrateFetchAllToFetchAllAssociativeRector.php
rules/TYPO312/v0/MigrateFetchColumnToFetchOneRector.php
rules/TYPO312/v0/MigrateFetchToFetchAssociativeRector.php
rules/TYPO312/v0/UseConfigArrayForTSFEPropertiesRector.php
rules/TYPO312/v4/CommandConfigurationToAttributeRector.php
rules/TYPO313/v0/EventListenerConfigurationToAttributeRector.php
rules/TYPO313/v2/MigrateRegularExpressionValidatorValidatorOptionErrorMessageRector.php
rules/TYPO313/v3/MigrateViewHelperRenderStaticRector.php

Rector is removing use of protected property `nodeNameResolver` in rules, use `isName()`, `isNames()`, `getName()` directly instead. Ref PR:
- https://github.com/rectorphp/rector-src/pull/6875

Remove use of protected property NodeNameResolver on Rector Rules

---

rules/CodeQuality/General/InjectMethodToConstructorInjectionRector.php
tests/Rector/CodeQuality/General/InjectMethodToConstructorInjectionRector/Fixture/skip_if_constructor_in_parent_class.php.inc
tests/Rector/CodeQuality/General/InjectMethodToConstructorInjectionRector/Fixture/skip_if_constructor_in_same_class.php.inc
tests/Rector/CodeQuality/General/InjectMethodToConstructorInjectionRector/Source/AnotherService.php
tests/Rector/CodeQuality/General/InjectMethodToConstructorInjectionRector/Source/MyService.php
tests/Rector/CodeQuality/General/InjectMethodToConstructorInjectionRector/Source/YetAnotherService.php

[BUGFIX] Skip migration if target class already has a constructor

---

rules/CodeQuality/General/InjectMethodToConstructorInjectionRector.php
tests/Rector/CodeQuality/General/InjectMethodToConstructorInjectionRector/Fixture/skip_if_abstract_class.php.inc

In abstract classes method injection should be preferred over constructor injection (see https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/DependencyInjection/Index.html#method-injection)

[BUGFIX] Skip InjectMethodToConstructorInjectionRector for abstract classes

---

rules/TYPO312/v0/MigrateFileFieldTCAConfigToTCATypeFileRector.php
tests/Rector/v12/v0/MigrateFileFieldTCAConfigToTCATypeFileRector/Fixture/tca.php.inc

Other rector rules already use `TODO` to annotate manual tasks that need to be done after the rector process. This has the advantage that these will be highlighted and/or listed by supporting IDEs.

[TASK] Insert TODO comment to stay consistent with other rules
