sabbelasichon/typo3-rector

- config/typo3-80.yaml
- src/Fluid/View/ChangeMethodCallsForStandaloneViewRector.php
- stubs/Fluid/View/StandaloneView.php
- tests/Fluid/View/ChangeMethodCallsForStandaloneViewRectorTest.php
- tests/Fluid/View/Fixture/fluid_standaloneview.php.inc
- setLayoutRootPath => setLayoutRootPaths
- getLayoutRootPath => getLayoutRootPaths
- setPartialRootPath => setPartialRootPaths
- getPartialRootPath => getPartialRootPaths
> [TASK] Rename methods for fluid StandaloneView

- config/typo3-76.yaml
- src/IndexedSearch/Controller/RenamePiListBrowserResultsRector.php
- stubs/IndexedSearch/Controller/SearchFormController.php
- tests/IndexedSearch/Controller/Fixtures/rename_pi_list_browser_results_method.php.inc
- tests/IndexedSearch/Controller/RenamePiListBrowserResultsRectorTest.php
- tests/config/typo3_rectors.yaml
> [TASK] Rename pi_list_browseresults to renderPagination

- config/typo3-94.yaml
- src/Core/Page/RefactorDeprecatedConcatenateMethodsPageRendererRector.php
- stubs/Core/Page/PageRenderer.php
- tests/Core/Page/Fixture/refactor_deprecated_concatenate_methods.php.inc
- tests/Core/Page/RefactorDeprecatedConcatenateMethodsPageRendererRectorTest.php
- tests/config/typo3_rectors.yaml
- Methods getConcatenateFiles, enableConcatenateFiles, disableConcatenateFiles are deprecated. Call new methods on PageRenderer
Resolves: #1145
> [TASK] Add rector to call new methods in PageRenderer

- config/typo3-94.yaml
- stubs/Saltedpasswords/Salt/Argon2iSalt.php
> [TASK] Rename classes from saltedpasswords

- config/services.yaml
- config/typo3-76.yaml
- config/typo3-80.yaml
- config/typo3-86.yaml
- config/typo3-87.yaml
- config/typo3-94.yaml
- config/typo3-95.yaml
- src/Frontend/Controller/RemoveInitTemplateMethodCallRector.php
- src/Helper/Typo3NodeResolver.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Frontend/Controller/Fixture/remove_init_template_from_tsfe.php.inc
- tests/Frontend/Controller/RemoveInitTemplateMethodCallRectorTest.php
- tests/bootstrap.php
> [TASK] Remove initTemplate method call from TypoScriptFrontendController

- config/typo3-93.yaml
- src/Backend/Domain/Repository/Localization/RemoveColPosParameterRector.php
- stubs/Backend/Controller/Page/LocalizationController.php
- stubs/Backend/Domain/Repository/Localization/LocalizationRepository.php
- tests/Backend/Domain/Repository/Localization/Fixture/remove_colpos_parameter_localizationrepository_methods.php.inc
- tests/Backend/Domain/Repository/Localization/LocalizationRepositoryTest.php
- tests/config/typo3_rectors.yaml
> Remove colPos parameter from methods

- config/typo3-95.yaml
- src/Rector/Extbase/RemoveInternalAnnotationRector.php
- stubs/Extbase/Mvc/Controller/CommandController.php
- tests/Rector/Extbase/Fixture/keep_internal_annotation.php.inc
- tests/Rector/Extbase/Fixture/remove_internal_annotation.php.inc
- tests/Rector/Extbase/RemoveInternalAnnotationRectorTest.php
> [TASK] Remove annotation @internal

- config/typo3-95.yaml
- src/Helper/Typo3NodeResolver.php
- src/Rector/Core/Package/UsePackageManagerActivePackagesRector.php
- stubs/Core/Package/PackageManager.php
- tests/Core/Package/Fixture/package_manager_active_packages.php.inc
- tests/Core/Package/UsePackageManagerActivePackagesRectorTest.php
- tests/bootstrap.php
> [TASK] Use PackageManager->getActivePackages instead of "$GLOBALS['TYPO3-LOADED-EXT']"

- composer.json
- config/typo3-76.yaml
- config/typo3-80.yaml
- config/typo3-87.yaml
- config/typo3-93.yaml
- config/typo3-94.yaml
- config/typo3-95.yaml
To be able to use this package, I had to do some adjustments
> Allow composer install and including through rector.yaml in other project

- config/typo3-90.yaml
- src/Rector/Core/CheckForExtensionInfoRector.php
- stubs/Core/Package/PackageManager.php
- stubs/Core/Utility/ExtensionManagementUtility.php
- tests/Rector/Core/CheckForExtensionInfoRectorTest.php
- tests/Rector/Core/Fixture/check_for_info_instead_of_infopagetsconfig.php.inc
- tests/config/typo3_rectors.yaml
> [TASK] Change extension key "info_pagetsconfig" to "info"

- config/typo3-80.yaml
- src/Rector/Extbase/RemovePropertyUserAuthenticationRector.php
- stubs/Extbase/Mvc/Controller/CommandController.php
- tests/Rector/Extbase/Fixture/remove_user_authentication_property.php.inc
- tests/Rector/Extbase/RemovePropertyUserAuthenticationRectorTest.php
> [TASK] Property userAuthentication removed from CommandController

- config/typo3-93.yaml
- config/typo3-95.yaml
> [TASK] Add correct configuration for RenameMethodCallRector

- config/typo3-90.yaml
- src/Rector/Core/Utility/RefactorMethodsFromExtensionManagementUtilityRector.php
- stubs/Core/Core/CacheManager.php
- stubs/Core/Utility/ExtensionManagementUtility.php
- stubs/Core/Utility/PathUtility.php
- tests/Rector/Core/Utility/Fixture/refactor_extensionmanagement_utility_methods.php.inc
- tests/Rector/Core/Utility/RefactorMethodsFromExtensionManagementUtilityRectorTest.php
> [TASK] Refactor deprecated methods from "ExtensionManagementUtility"

- config/typo3-100.yaml
- src/Rector/Extbase/RemovePropertyExtensionNameRector.php
- stubs/Extbase/Mvc/Controller/AbstractController.php
- stubs/Extbase/Mvc/Request.php
- tests/Rector/Extbase/Fixture/remove_extensionname_property.php.inc
- tests/Rector/Extbase/RemovePropertyExtensionNameRectorTest.php
- tests/config/typo3_rectors.yaml
- Use getControllerExtensionName from Request property instead.
- Resolves: #1271
> [TASK] Remove Property extensionName of AbstractController

- config/typo3-101.yaml
- src/Rector/Extbase/RegisterPluginWithVendorNameRector.php
- stubs/Extbase/Utility/ExtensionUtility.php
- tests/Rector/Extbase/Fixture/register_plugin_with_vendor_name.php.inc
- tests/Rector/Extbase/RegisterPluginWithVendorNameRectorTest.php
- tests/config/typo3_rectors.yaml
> [TASK] Remove vendorName from registerPlugin call

- config/typo3-80.yaml
- src/Helper/Typo3NodeResolver.php
- src/Rector/Core/TimeTracker/TimeTrackerGlobalsToSingletonRector.php
- src/Rector/Frontend/Controller/RemoveInitTemplateMethodCallRector.php
- stubs/Core/TimeTracker/TimeTracker.php
- tests/Rector/Core/TimeTracker/Fixture/time_tracker_direct_call.php.inc
- tests/Rector/Core/TimeTracker/TimeTrackerGlobalsToSingletonRectorTest.php
- tests/bootstrap.php
> [TASK] Remove calls from $GLOBALS['TT']

- config/typo3-101.yaml
- src/Rector/Backend/Utility/BackendUtilityEditOnClickRector.php
- stubs/Backend/Routing/UriBuilder.php
- stubs/Backend/Utility/BackendUtility.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/Backend/Utility/BackendUtilityEditOnClickRectorTest.php
- tests/Rector/Backend/Utility/Fixture/backend_utility_edit_on_click.php.inc
> [TASK] Refactor BackendUtility::editOnClick

- config/typo3-90.yaml
- src/Rector/SysNote/Domain/Repository/FindByPidsAndAuthorIdRector.php
- stubs/Extbase/Domain/Model/BackendUser.php
- stubs/SysNote/Domain/Repository/SysNoteRepository.php
- tests/Rector/SysNote/Domain/Repository/FindByPidsAndAuthorIdRectorTest.php
- tests/Rector/SysNote/Domain/Repository/Fixture/sys_repository_find_by_pids_and_author.php.inc
- Change second argument to get uid from backendUser
- Resolves: #956
> [TASK] Rename method findByPidsAndAuthor to findByPidsAndAuthorId

- config/typo3-90.yaml
- src/Rector/Core/TypoScript/TemplateServiceSplitConfArrayRector.php
- stubs/Core/Authentication/AbstractAuthenticationService.php
- stubs/Core/Authentication/AuthenticationService.php
- stubs/Core/DataHandling/DataHandler.php
- stubs/Core/TypoScript/TemplateService.php
- stubs/Sv/AbstractAuthenticationService.php
- stubs/Sv/AuthenticationService.php
- tests/Rector/Core/DataHandling/DataHandlerRmCommaRectorTest.php
- tests/Rector/Sv/Fixture/sv_change_namespace.php.inc
- tests/Rector/Sv/SvChangeNamespaceRectorTest.php
> [TASK] Change namespace for old extension sv

- config/typo3-90.yaml
- src/Rector/Fluid/ViewHelpers/UseRenderingContextGetControllerContextRector.php
- stubs/Fluid/Core/Rendering/RenderingContext.php
- tests/Rector/Fluid/ViewHelpers/Fixture/use_rendering_context_get_controller_context.php.inc
- tests/Rector/Fluid/ViewHelpers/UseRenderingContextGetControllerContextRectorTest.php
- Instead of accessing the property controllerContext we get the controllerContext from the property renderingContext
Resolves: #926
> [TASK] Use renderingContext->getControllerContext

- config/typo3-94.yaml
- config/typo3-95.yaml
- src/Rector/Extbase/ConfigurationManagerAddControllerConfigurationMethodRector.php
- stubs/Extbase/Configuration/AbstractConfigurationManager.php
- tests/Rector/Extbase/ConfigurationManagerAddControllerConfigurationMethodRectorTest.php
- tests/Rector/Extbase/Fixture/configuration_manager_add_controller_configuration_method.php.inc
- We add this rector for version 9.5 alreay. Otherwise we would get a fatal error in version 10
Resolves: #1222
> [TASK] Add new method getControllerConfiguration

- config/typo3-90.yaml
- src/Helper/Typo3NodeResolver.php
- src/Rector/Core/SubstituteConstantParsetimeStartRector.php
- tests/Rector/Core/Fixture/substitute_globals_parsetime.php.inc
- tests/Rector/Core/SubstituteConstantParsetimeStartRectorTest.php
- tests/bootstrap.php
> [TASK] Substitute global variable PARSETIME_START

- config/typo3-90.yaml
- src/Rector/Core/Utility/RemoveSecondArgumentGeneralUtilityMkdirDeepRector.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/Core/Utility/Fixture/remove_second_argument_mkdir_deep.php.inc
- tests/Rector/Core/Utility/RemoveSecondArgumentGeneralUtilityMkdirDeepRectorTest.php
- tests/bootstrap.php
> [TASK] Concat second parameter with first one

- config/typo3-94.yaml
- src/Console/ConsoleKernel.php
- src/Rector/Core/Utility/RefactorExplodeUrl2ArrayFromGeneralUtilityRector.php
- src/Rector/Frontend/ContentObject/RefactorRemovedMarkerMethodsFromContentObjectRendererRector.php
- stubs/Core/Service/MarkerBasedTemplateService.php
- stubs/Core/Utility/GeneralUtility.php
- stubs/Frontend/ContentObject/ContentObjectRenderer.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/Core/Utility/Fixture/explode_url2_array.php.inc
- tests/Rector/Core/Utility/RefactorExplodeUrl2ArrayFromGeneralUtilityRectorTest.php
> [TASK] Refactor GeneralUtility::explodeUrl2Array if 2nd argument is given

- Migrations/Core/v10/ClassAliasMap.php
- config/typo3-100.yaml
> [TASK] Move frontend page repository to core

- config/typo3-100.yaml
- docs/AllRectorsOverview.md
- src/Rector/Core/DataHandling/DataHandlerRmCommaRector.php
- src/Rector/Extbase/Utility/UseNativePhpHex2binMethodRector.php
- src/Rector/Fluid/ViewHelpers/MoveRenderArgumentsToInitializeArgumentsMethodRector.php
- stubs/Extbase/Utility/TypeHandlingUtility.php
- tests/Rector/Extbase/Utility/Fixture/native_hex2bin.php.inc
- tests/Rector/Extbase/Utility/UseNativePhpHex2binMethodRectorTest.php
> [TASK] Refactor TypeHandlingUtility::hex2bin to hex2bin

- config/typo3-90.yaml
- docs/AllRectorsOverview.md
- src/Rector/Backend/Controller/RemovePropertiesFromSimpleDataHandlerControllerRector.php
- stubs/Backend/Controller/SimpleDataHandlerController.php
- stubs/Extbase/Service/EnvironmentService.php
- tests/Rector/Backend/Controller/Fixture/remove_properties_fetch_simpledatahandlercontroller.inc
- tests/Rector/Backend/Controller/RemovePropertiesFromSimpleDataHandlerControllerRectorTest.php
- Remove node if assigning or accessing properties uPT or prErr from class SimpleDataHandlerController
Resolves: #872
> [TASK] Remove assignment or fetching for prErr or uPT

- config/typo3-80.yaml
> [TASK] Rename changed method calls

- Migrations/Workspaces/v9/ClassAliasMap.php
- config/typo3-90.yaml
- docs/AllRectorsOverview.md
- src/Rector/Core/CheckForExtensionVersionRector.php
- tests/Rector/Core/CheckForExtensionVersionRectorTest.php
- tests/Rector/Core/Fixture/check_for_workspaces_instead_of_version.php.inc
> [TASK] Migrate version into workspaces

- config/typo3-81.yaml
- docs/AllRectorsOverview.md
- src/Rector/Core/RefactorDbConstantsRector.php
- tests/Rector/Core/Fixture/change_db_constants.php.inc
- tests/Rector/Core/RefactorDbConstantsRectorTest.php
- tests/bootstrap.php
- tests/config/typo3_rectors.yaml
> [TASK] Substitute removed TYPO3_db constants with

- config/typo3-80.yaml
> [TASK] Change method calls for some classes

- config/typo3-102.yaml
- src/Rector/Core/Utility/MoveApplicationContextToEnvironmentApiRector.php
- stubs/Core/Environment.php
- tests/Rector/Core/Utility/Fixture/use-environment-api.php.inc
- tests/Rector/Core/Utility/MoveApplicationContextToEnvironmentApiRectorTest.php
> [TASK] Use Environment API to fetch application context

- config/typo3-102.yaml
- src/Rector/Backend/Controller/RemovePropertiesFromSimpleDataHandlerControllerRector.php
- src/Rector/Core/ExcludeServiceKeysToArrayRector.php
- src/Rector/Core/Utility/RefactorDeprecationLogRector.php
- stubs/Core/Utility/ExtensionManagementUtility.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/Core/ExcludeServiceKeysToArrayRectorTest.php
- tests/Rector/Core/Fixture/exclude_service_keys_to_array.php.inc
- tests/config/typo3_rectors.yaml
> [TASK] ServiceChains require an array for excluded Service keys

- config/typo3-102.yaml
- src/Rector/Extbase/UseActionControllerRector.php
- stubs/Extbase/Mvc/Controller/ActionController.php
- tests/Rector/Extbase/Fixture/remove_extensionname_property.php.inc
- tests/Rector/Extbase/Fixture/use_action_controller_class.php.inc
- tests/Rector/Extbase/UseActionControllerRectorTest.php
> [TASK] Use ActionController instead of AbstractController

- src/Rector/Backend/Controller/RemovePropertiesFromSimpleDataHandlerControllerRector.php
- src/Rector/Core/RefactorDbConstantsRector.php
- src/Rector/Core/SubstituteConstantParsetimeStartRector.php
- src/Rector/Core/Utility/RefactorExplodeUrl2ArrayFromGeneralUtilityRector.php
- src/Rector/Core/Utility/RemoveSecondArgumentGeneralUtilityMkdirDeepRector.php
- src/Rector/Extbase/ConfigurationManagerAddControllerConfigurationMethodRector.php
- src/Rector/Extbase/UseActionControllerRector.php
- src/Rector/Extbase/Utility/UseNativePhpHex2binMethodRector.php
- src/Rector/Fluid/ViewHelpers/UseRenderingContextGetControllerContextRector.php
- It is not necessary to test the getDefinition method of a rector. Just add @codeCoverageIgnore docblock
> [TASK] Add missing docblock for code coverage ignore

- config/typo3-102.yaml
- src/Rector/Backend/Utility/UseTypo3InformationForCopyRightNoticeRector.php
- stubs/Backend/Utility/BackendUtility.php
- stubs/Core/Information/Typo3Information.php
- tests/Rector/Backend/Utility/Fixture/use_typo3_information.php.inc
- tests/Rector/Backend/Utility/UseTypo3InformationForCopyRightNoticeRectorTest.php
> [TASK] Use Typo3Information API for copyright notice

- config/typo3-100.yaml
- src/Rector/Core/Utility/RefactorIdnaEncodeMethodToNativeFunctionRector.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/Core/Utility/Fixture/idna_convert_to_idn_to_ascii.php.inc
- tests/Rector/Core/Utility/RefactorIdnaEncodeMethodToNativeFunctionRectorTest.php
> [TASK] Replace GeneralUtility::idnaEncode with function idn_to_ascii

- config/typo3-95.yaml
- src/Rector/Frontend/Page/RemoveInitMethodFromPageRepositoryRector.php
- stubs/Frontend/Page/PageRepository.php
- tests/Rector/Frontend/Page/Fixture/remove_init_method_call_from_page_repository.php.inc
- tests/Rector/Frontend/Page/RemoveInitMethodFromPageRepositoryRectorTest.php
> [TASK] Remove init method call from PageRepository

- composer.json
- config/typo3-102.yaml
- phpstan.neon
- src/Rector/Extbase/InjectEnvironmentServiceIfNeededInResponseRector.php
- stubs/Extbase/Mvc/Web/Response.php
- tests/Rector/Extbase/Fixture/inject_environment_service_if_needed.php.inc
- tests/Rector/Extbase/InjectEnvironmentServiceIfNeededInResponseRectorTest.php
> [TASK] Inject EnvironmentService in subclass of Response

- config/typo3-100.yaml
> [TASK] File related controllers moved to EXT:filelist

- config/typo3-100.yaml
- src/Rector/Core/Resource/UseMetaDataAspectRector.php
- stubs/Core/Resource/File.php
- stubs/Core/Resource/MetaDataAspect.php
- stubs/Core/Service/MarkerBasedTemplateService.php
- tests/Rector/Core/Resource/Fixture/use_metadata_aspect.php.inc
- tests/Rector/Core/Resource/UseMetaDataAspectRectorTest.php
> [TASK] Use getMetaData()->get() instead of _getMetaData

- classes/ParameterInImportResolver.php
- composer.json
> [BUGFIX] Set fixed version for rector

- .github/workflows/code_coverage.yaml
- .github/workflows/coding_standard.yaml
- .github/workflows/docs.yaml
- .github/workflows/rector.yaml
- .github/workflows/tests.yaml
- composer.json
- fixes/EolConfiguration.php
- src/Helper/Typo3NodeResolver.php
- src/Rector/Backend/Utility/BackendUtilityEditOnClickRector.php
- src/Rector/Backend/Utility/BackendUtilityGetRecordRawRector.php
- src/Rector/Backend/Utility/UseTypo3InformationForCopyRightNoticeRector.php
- src/Rector/Core/Package/UsePackageManagerActivePackagesRector.php
- src/Rector/Core/TimeTracker/TimeTrackerGlobalsToSingletonRector.php
- src/Rector/Core/TypoScript/TemplateServiceSplitConfArrayRector.php
- src/Rector/Core/Utility/RefactorMethodsFromExtensionManagementUtilityRector.php
- src/Rector/Extbase/ChangeAttemptsParameterConsoleOutputRector.php
- src/Rector/Extbase/InjectEnvironmentServiceIfNeededInResponseRector.php
- src/Rector/Frontend/ContentObject/CallEnableFieldsFromPageRepositoryRector.php
- src/Rector/Frontend/ContentObject/RefactorRemovedMarkerMethodsFromContentObjectRendererRector.php
- Always do a composer install with option prefer-lowest
> [TASK] Bump rector to version 0.7.26

- config/typo3-104.php
- stubs/Core/Environment.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/Core/Utility/Fixture/remove_second_argument_mkdir_deep.php.inc
- tests/Rector/Core/Utility/Fixture/use-environment-api2.php.inc
- tests/Rector/Core/Utility/MoveIsRunningOnCgiServerApiToEnvironmentApiRectorTest.php
- tests/Rector/Core/Utility/RemoveSecondArgumentGeneralUtilityMkdirDeepRectorTest.php
> [TASK] Use class Environment for method isRunningOnCgiServer

- config/typo3-80.php
- src/Rector/Core/Html/RteHtmlParserRector.php
- stubs/Core/Html/RteHtmlParser.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/Core/Html/Fixture/rtehtmlparser.php.inc
- tests/Rector/Core/Html/RteHtmlParserTest.php
> [TASK] Refactor class RteHtmlParser

- config/typo3-103.php
- src/Rector/Core/Resource/SubstituteResourceFactoryRector.php
- stubs/Core/Resource/ResourceFactory.php
- tests/Rector/Core/Resource/Fixture/substitute_resource_factory.php.inc
- tests/Rector/Core/Resource/SubstituteResourceFactoryRectorTest.php
- tests/Rector/Core/Resource/UseMetaDataAspectRectorTest.php
> [TASK] Use GeneralUtility::makeInstance(ResourceFactory::class)

- src/Rector/Core/Environment/ConstantToEnvironmentCallRector.php
- tests/Rector/Core/Environment/Fixture/environment_constants.php.inc
- tests/Rector/Core/Utility/Fixture/remove_second_argument_mkdir_deep.php.inc
> [BUGFIX] Add trailing slash for method publicPath

- config/typo3-104.php
- phpstan-baseline.neon
- src/Rector/v10_4/UnifiedFileNameValidatorRector.php
- stubs/Core/Resource/Security/FileNameValidator.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/v10_4/Fixture/unified_file_name_validator.php.inc
- tests/Rector/v10_4/UnifiedFileNameValidatorRectorTest.php
- tests/bootstrap.php
> [TASK] Use FileNameValidator

- config/typo3-103.php
- stubs/Linkvalidator/Repository/BrokenLinkRepository.php
> [TASK] Use method isLinkTargetBrokenLink

- config/typo3-104.php
- src/Rector/v10/v3/UseClassTypo3VersionRector.php
- stubs/Core/Information/Typo3Version.php
- tests/Rector/v10/v3/Fixture/use_class_typo3_version.php.inc
- tests/Rector/v10/v3/UseClassTypo3VersionRectorTest.php
- tests/bootstrap.php
> [TASK] Use class Typo3Version

- config/typo3-85.php
- stubs/Backend/Clipboard/ClipBoard.php
> [TASK] Change method name for class Clipboard

- config/typo3-90.php
- src/Rector/v9/v0/MetaTagManagementRector.php
- stubs/Backend/Template/DocumentTemplate.php
- stubs/Core/Page/PageRenderer.php
- tests/Rector/v9/v0/MetaTagManagement/Fixture/metatag_management.php.inc
- tests/Rector/v9/v0/MetaTagManagement/MetaTagManagementRectorTest.php
> [TASK] Add API for meta tag management

- config/typo3-90.php
- src/Rector/v9/v0/RemoveMethodInitTCARector.php
- stubs/Frontend/Utility/EidUtility.php
- tests/Rector/v9/v0/RemoveMethodInitTCA/Fixture/remove_init_tca.php.inc
- tests/Rector/v9/v0/RemoveMethodInitTCA/RemoveMethodInitTCARectorTest.php
> [TASK] Remove call EidUtility::initTCA

- config/typo3-90.php
- src/Rector/v9/v0/SubstituteCacheWrapperMethodsRector.php
- stubs/Backend/Utility/BackendUtility.php
- stubs/Core/Cache/CacheManager.php
- stubs/Core/Cache/Frontend/FrontendInterface.php
- tests/Rector/v9/v0/SubstituteCacheMethods/Fixture/substitute_cache_get_method.php.inc
- tests/Rector/v9/v0/SubstituteCacheMethods/Fixture/substitute_cache_set_method.php.inc
- tests/Rector/v9/v0/SubstituteCacheMethods/SubstituteCacheWrapperMethodsRectorTest.php
> [TASK] Caching framework wrapper methods in BackendUtility

- config/typo3-90.php
- src/Rector/v9/v0/UseLogMethodInsteadOfNewLog2Rector.php
- stubs/Core/DataHandling/DataHandler.php
- tests/Rector/v9/v0/UseLogMethod/Fixture/use_log_instead_of_new2log.php.inc
- tests/Rector/v9/v0/UseLogMethod/Fixture/use_log_instead_of_new2log_in_class.php.inc
- tests/Rector/v9/v0/UseLogMethod/UseLogMethodInsteadOfNewLog2RectorTest.php
> [TASK] Use log methd instead of newlog2

- config/typo3-90.php
- src/Rector/v9/v0/GeneratePageTitleRector.php
- stubs/Frontend/Page/PageGenerator.php
- tests/Rector/v9/v0/GeneratePageTitle/Fixture/generate_page_title.php.inc
- tests/Rector/v9/v0/GeneratePageTitle/GeneratePageTitleRectorTest.php
> [TASK] Use method generatePageTitle from TSFE

- config/typo3-90.php
- stubs/Core/Utility/GeneralUtility.php
> [TASK] Use makeInstance instead of getUserObj

- config/typo3-94.php
- src/Helper/Typo3NodeResolver.php
- src/Rector/v9/v4/UseContextApiRector.php
- stubs/Core/Context/Context.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v9/v4/UseContextApi/Fixture/use_context_api.php.inc
- tests/Rector/v9/v4/UseContextApi/Fixture/use_context_api_class_context.php.inc
- tests/Rector/v9/v4/UseContextApi/UseContextApiRectorTest.php
> [TASK] Various public properties in favor of Context API

- config/typo3-80.php
- src/Rector/Annotation/InjectAnnotationRector.php
- src/Rector/v8/v0/RemoveWakeupCallFromEntityRector.php
- stubs/Extbase/DomainObject/AbstractDomainObject.php
- tests/Rector/v8/v0/RemoveWakeupCallFromEntity/Fixture/keep_parent_wakeup_call.php.inc
- tests/Rector/v8/v0/RemoveWakeupCallFromEntity/Fixture/remove_parent_wakeup_call.php.inc
- tests/Rector/v8/v0/RemoveWakeupCallFromEntity/RemoveWakeupCallFromEntityRectorTest.php
> [TASK] Remove method __wakeup

- config/typo3-103.php
- stubs/Extbase/Mvc/Response.php
- stubs/Extbase/Mvc/Web/Request.php
- tests/Rector/Extbase/Fixture/inject_environment_service_if_needed.php.inc
- tests/Rector/Extbase/InjectEnvironmentServiceIfNeededInResponseRectorTest.php
> [TASK] Change Request and Response classes from extbase

- src/Rector/v10/v0/ForceTemplateParsingInTsfeAndTemplateServiceRector.php
> [BUGFIX] fix argument within ForceTemplateParsingInTsfeAndTemplateServiceRector

- config/typo3-95.php
- src/Rector/v9/v5/RefactorProcessOutputRector.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v9/v5/ProcessOutput/Fixture/instance_of_tsfe_process_output.php.inc
- tests/Rector/v9/v5/ProcessOutput/Fixture/process_output.php.inc
- tests/Rector/v9/v5/ProcessOutput/RefactorProcessOutputRectorTest.php
> [TASK] Refactor method processOutput of TSFE

- config/typo3-100.php
- src/Rector/v10/v0/BackendUtilityGetViewDomainToPageRouterRector.php
- stubs/Backend/Utility/BackendUtility.php
- stubs/Core/Routing/PageRouter.php
- stubs/Core/Service/MarkerBasedTemplateService.php
- stubs/Core/Site/Entity/Site.php
- stubs/Core/Site/SiteFinder.php
- tests/Rector/v10/v0/BackendUtilityViewDomainToPageRouter/BackendUtilityGetViewDomainToPageRouterRectorTest.php
- tests/Rector/v10/v0/BackendUtilityViewDomainToPageRouter/Fixture/backend_utility_get_view_domain.php.inc
> [TASK] Use PageRouter instead of BackendUtility::getViewDomain

- config/typo3-94.php
- src/Rector/v9/v4/UseContextApiForVersioningWorkspaceIdRector.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- stubs/Frontend/Page/PageRepository.php
- tests/Rector/v9/v4/UseContextApiForVersioningWorkspaceId/Fixture/use_context_api.php.inc
- tests/Rector/v9/v4/UseContextApiForVersioningWorkspaceId/Fixture/use_context_api_tsfe.php.inc
- tests/Rector/v9/v4/UseContextApiForVersioningWorkspaceId/UseContextApiForVersioningWorkspaceIdRectorTest.php
> [TASK] Use context api instead of versioningWorkspaceId

- config/typo3-104.php
- src/Rector/v10/v4/RemoveFormatConstantsEmailFinisherRector.php
- stubs/Form/Domain/Finishers/EmailFinisher.php
- tests/Rector/v10/v4/RemoveFormatConstantsEmailFinisher/Fixture/remove_format_constants.php.inc
- tests/Rector/v10/v4/RemoveFormatConstantsEmailFinisher/RemoveFormatConstantsEmailFinisherRectorTest.php
> [TASK] Refactor option format to addHtmlPart

- config/typo3-100.php
- src/Rector/v10/v0/SetSystemLocaleFromSiteLanguageRector.php
- stubs/Core/Localization/Locales.php
- stubs/Core/Site/Entity/SiteLanguage.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v10/v0/SetSystemLocaleFromSiteLanguage/Fixture/set_system_locale_from_site_language.php.inc
- tests/Rector/v10/v0/SetSystemLocaleFromSiteLanguage/SetSystemLocaleFromSiteLanguageRectorTest.php
Refactor method settingLocale from TSFE to Locales::setSystemLocaleFromSiteLanguage()
Resolves: #1287
> [TASK] Refactor method settingLocale from TSFE

- config/typo3-104.php
- src/Rector/v10/v4/UseFileGetContentsForGetUrlRector.php
- stubs/Core/Http/RequestFactory.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/v10/v4/UseFileGetContentsForGetUrl/Fixture/use_file_get_contents.php.inc
- tests/Rector/v10/v4/UseFileGetContentsForGetUrl/UseFileGetContentsForGetUrlRectorTest.php
> [TASK] Refactor GeneralUtility::getUrl if possible

- composer.json
> [TASK] Add package nette/utils

- captainhook.json
- composer.json
> [TASK] Install captain hook

- README.md
> [TASK] Add some more examples in README.md

- config/typo3-100.php
- src/Rector/v10/v0/UseTwoLetterIsoCodeFromSiteLanguageRector.php
- stubs/Core/Localization/LanguageService.php
- stubs/Core/Site/Entity/SiteLanguage.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v10/v0/UseTwoLetterIsoCodeFromSiteLanguage/Fixture/use_two_letter_iso_code_from_site_language.php.inc
- tests/Rector/v10/v0/UseTwoLetterIsoCodeFromSiteLanguage/UseTwoLetterIsoCodeFromSiteLanguageRectorTest.php
- tests/bootstrap.php
Use method getTwoLetterIsoCode of class SiteLanguage instead of property sys_language_isocode
Resolves: #1259
> [TASK] Use method getTwoLetterIsoCode

- .gitattributes
> [TASK] Add more files and folders to .gitattributes

- config/v8/typo3-80.php
- src/Rector/v8/v0/RandomMethodsToRandomClassRector.php
- stubs/Core/Crypto/Random.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/v8/v0/RandomMethodsToRandomClass/Fixture/random_methods_to_random_class.php.inc
- tests/Rector/v8/v0/RandomMethodsToRandomClass/RandomMethodsToRandomClassRectorTest.php
> [TASK] Deprecated random generator methods in GeneralUtility

- config/v8/typo3-80.php
- src/Rector/v8/v0/RandomMethodsToRandomClassRector.php
- src/Rector/v8/v0/RequireMethodsToNativeFunctionsRector.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/v8/v0/RequireMethodsToNativeFunctions/Fixture/require_methods_to_native_functions.php.inc
- tests/Rector/v8/v0/RequireMethodsToNativeFunctions/Fixture/some_other_file.php
- tests/Rector/v8/v0/RequireMethodsToNativeFunctions/Fixture/somefile.php
- tests/Rector/v8/v0/RequireMethodsToNativeFunctions/RequireMethodsToNativeFunctionsRectorTest.php
> [TASK] Refactor requireOnce and requireFile

- config/v8/typo3-80.php
- src/Rector/v8/v0/GetPreferredClientLanguageRector.php
- stubs/Core/Charset/CharsetConverter.php
- stubs/Core/Localization/Locales.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v8/v0/GetPreferredClientLanguage/Fixture/get_preferred_client_language.php.inc
- tests/Rector/v8/v0/GetPreferredClientLanguage/Fixture/get_preferred_client_language_tsfe.php.inc
- tests/Rector/v8/v0/GetPreferredClientLanguage/Fixture/get_preferred_client_language_tsfe_with_helper_call.php.inc
- tests/Rector/v8/v0/GetPreferredClientLanguage/GetPreferredClientLanguageRectorTest.php
> [TASK] Use getPreferredClientLanguage from Locales

- src/Rector/v8/v1/GeneralUtilityToUpperAndLowerRector.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/v8/v1/GeneralUtilityToUpperAndLower/Fixture/str_to_upper_and_lower.php.inc
- tests/Rector/v8/v1/GeneralUtilityToUpperAndLower/GeneralUtilityToUpperAndLowerRectorTest.php
> [TASK] Use mb_strtoupper and mb_strtolower

- config/v7/typo3-70.php
- stubs/Backend/Template/BigDocumentTemplate.php
- stubs/Backend/Template/MediumDocumentTemplate.php
- stubs/Backend/Template/SmallDocumentTemplate.php
- stubs/Backend/Template/StandardDocumentTemplate.php
> [TASK] Use DocumentTemplate for deprecated template classes

- config/v7/typo3-70.php
- src/Rector/v7/v0/RemoveMethodCallLoadTcaRector.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/v7/v0/RemoveMethodCallLoadTca/Fixture/remove_method_load_tca.php.inc
- tests/Rector/v7/v0/RemoveMethodCallLoadTca/RemoveMethodCallLoadTcaRectorTest.php
> [TASK] Remove GeneralUtility::loadTCA() method call

- config/v7/typo3-70.php
- stubs/Core/Utility/GeneralUtility.php
- stubs/Core/Utility/VersionNumberUtility.php
> [TASK] Replace int_from_ver to convertVersionNumberToInteger

- config/v7/typo3-70.php
- src/Rector/v7/v0/RemoveMethodCallConnectDbRector.php
- stubs/Frontend/Utility/EidUtility.php
- tests/Rector/v7/v0/RemoveMethodCallConnectDb/Fixture/remove_method_connect_db.php.inc
- tests/Rector/v7/v0/RemoveMethodCallConnectDb/RemoveMethodCallConnectDbRectorTest.php
> [TASK] Remove EidUtility::connectDB method call

- config/v8/typo3-81.php
- src/Rector/v8/v1/Array2XmlCsToArray2XmlRector.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/v8/v1/Array2XmlCsToArray2Xml/Array2XmlCsToArray2XmlRectorTest.php
- tests/Rector/v8/v1/Array2XmlCsToArray2Xml/Fixture/array2xmlcs_to_array2xml.php.inc
- tests/bootstrap.php
> [TASK] array2xml_cs to array2xml

- config/v7/typo3-71.php
- src/Rector/v7/v1/GetTemporaryImageWithTextRector.php
- stubs/Core/Resource/Processing/LocalImageProcessor.php
- tests/Rector/v7/v1/GetTemporaryImageWithText/Fixture/get_temporary_image_with_text.php.inc
- tests/Rector/v7/v1/GetTemporaryImageWithText/GetTemporaryImageWithTextRectorTest.php
> [TASK] Refactor method getTemporaryImageWithText

- config/v7/typo3-74.php
- src/Rector/v7/v4/InstantiatePageRendererExplicitlyRector.php
- stubs/Backend/Controller/BackendController.php
- stubs/Backend/Template/DocumentTemplate.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v7/v4/InstantiatePageRendererExplicitly/Fixture/backend_controller_pagerenderer.php.inc
- tests/Rector/v7/v4/InstantiatePageRendererExplicitly/Fixture/document_template_pagerenderer.php.inc
- tests/Rector/v7/v4/InstantiatePageRendererExplicitly/Fixture/tsfe_pagerenderer.php.inc
- tests/Rector/v7/v4/InstantiatePageRendererExplicitly/InstantiatePageRendererExplicitlyRectorTest.php
> [TASK] Instantiate PageRenderer explicitly

- config/v7/typo3-76.php
> [TASK] Method issueCommand to getLinkToDataHandlerAction

- config/v7/typo3-76.php
- stubs/IndexedSearch/Controller/SearchFormController.php
- stubs/IndexedSearch/Domain/Repository/IndexSearchRepository.php
- stubs/IndexedSearch/Utility/LikeWildcard.php
> [TASK] Escape strings properly

- src/Rector/v8/v6/ArrayUtilityInArrayToFuncInArrayRector.php
- stubs/Core/Utility/ArrayUtility.php
- tests/Rector/v8/v6/ArrayUtilityInArrayToFuncInArray/ArrayUtilityInArrayToFuncInArrayRectorTest.php
- tests/Rector/v8/v6/ArrayUtilityInArrayToFuncInArray/Fixture/array_utility_in_array.php.inc
> [TASK] ArrayUtility::inArray to in_array

- src/Rector/v9/v3/PhpOptionsUtilityRector.php
- stubs/Core/Utility/PhpOptionsUtility.php
- tests/Rector/v9/v3/PhpOptionsUtility/Fixture/php_options_utility.php.inc
- tests/Rector/v9/v3/PhpOptionsUtility/PhpOptionsUtilityRectorTest.php
> [TASK] Refactor methods from PhpOptionsUtility

- config/v8/typo3-87.php
- stubs/Core/Utility/CsvUtility.php
- stubs/Core/Utility/GeneralUtility.php
> [TASK] Move method csvValues

- src/Rector/v9/v4/ConstantToEnvironmentCallRector.php
- tests/Rector/v9/v4/ConstantToEnvironmentCall/Fixture/environment_constants.php.inc
- tests/bootstrap.php
> [BUGFIX] Correct replacement for isCli

- config/v7/typo3-70.php
- src/Rector/v7/v0/TypeHandlingServiceToTypeHandlingUtilityRector.php
- stubs/Extbase/Service/TypeHandlingService.php
- stubs/Extbase/Utility/TypeHandlingUtility.php
- tests/Rector/v7/v0/TypeHandlingServiceToTypeHandlingUtility/Fixture/type_handling_utility.php.inc
- tests/Rector/v7/v0/TypeHandlingServiceToTypeHandlingUtility/TypeHandlingServiceToTypeHandlingUtilityRectorTest.php
> [TASK] TypeHandlingUtility instead of TypeHandlingService

- config/v7/typo3-76.php
- src/Rector/v7/v6/WrapClickMenuOnIconRector.php
- stubs/Backend/Template/DocumentTemplate.php
- stubs/Backend/Utility/BackendUtility.php
- tests/Rector/v7/v6/WrapClickMenuOnIcon/Fixture/wrap_click_menu_on_icon.php.inc
- tests/Rector/v7/v6/WrapClickMenuOnIcon/WrapClickMenuOnIconRectorTest.php
> [TASK] Use wrapClickMenuOnIcon of BackendUtility

- config/v9/typo3-94.php
- src/Rector/v9/v4/BackendUtilityShortcutExistsRector.php
- stubs/Backend/Backend/Shortcut/ShortcutRepository.php
- stubs/Backend/Utility/BackendUtility.php
- tests/Rector/v9/v4/BackendUtilityShortcutExists/BackendUtilityShortcutExistsRectorTest.php
- tests/Rector/v9/v4/BackendUtilityShortcutExists/Fixture/backend_utility_shortcut_exists.php.inc
> [TASK] Deprecation BackendUtility::shortcutExists

- config/v8/typo3-85.php
- src/Rector/v8/v5/CharsetConverterToMultiByteFunctionsRector.php
- stubs/Core/Charset/CharsetConverter.php
- tests/Rector/v8/v5/CharsetConverterToMultiByteFunctions/CharsetConverterToMultiByteFunctionsRectorTest.php
- tests/Rector/v8/v5/CharsetConverterToMultiByteFunctions/Fixture/charset_converter_to_multi_byte_functions.php.inc
> [TASK] CharsetConverter methods to mb_* function calls

- src/Helper/Typo3NodeResolver.php
- src/Rector/v9/v3/PropertyUserTsToMethodGetTsConfigOfBackendUserAuthenticationRector.php
- stubs/Core/Authentication/BackendUserAuthentication.php
- stubs/Core/Charset/CharsetConverter.php
- tests/Rector/v9/v3/PropertyUserTsToMethodGetTsConfigOfBackendUserAuthentication/Fixture/backend_user_user_ts_config.php.inc
- tests/Rector/v9/v3/PropertyUserTsToMethodGetTsConfigOfBackendUserAuthentication/Fixture/backend_user_user_ts_config_in_class.php.inc
- tests/Rector/v9/v3/PropertyUserTsToMethodGetTsConfigOfBackendUserAuthentication/PropertyUserTsToMethodGetTsConfigOfBackendUserAuthenticationRectorTest.php
- tests/bootstrap.php
> [TASK] Use method getTSConfig instead of property userTS

- config/v9/typo3-93.php
- src/Rector/v9/v3/UseMethodGetPageShortcutDirectlyFromSysPageRector.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- stubs/Frontend/Page/PageRepository.php
- tests/Rector/v9/v3/UseMethodGetPageShortcutDirectlyFromSysPage/Fixture/use_get_page_shortcut_from_sys_page.php.inc
- tests/Rector/v9/v3/UseMethodGetPageShortcutDirectlyFromSysPage/Fixture/use_get_page_shortcut_from_sys_page_in_class.php.inc
- tests/Rector/v9/v3/UseMethodGetPageShortcutDirectlyFromSysPage/UseMethodGetPageShortcutDirectlyFromSysPageRectorTest.php
> [TASK] Use method getPageShortcut directly from PageRepository

- config/v9/typo3-93.php
- src/Rector/v9/v3/CopyMethodGetPidForModTSconfigRector.php
- stubs/Backend/Utility/BackendUtility.php
- stubs/Core/Utility/MathUtility.php
- tests/Rector/v9/v3/CopyMethodGetPidForModTSconfig/CopyMethodGetPidForModTSconfigRectorTest.php
- tests/Rector/v9/v3/CopyMethodGetPidForModTSconfig/Fixture/copy_method_get_pid_for_mod_tsconfig.php.inc
- tests/Rector/v9/v3/CopyMethodGetPidForModTSconfig/Fixture/copy_method_get_pid_for_mod_tsconfig_in_class_context.php.inc
> [TASK] Copy method getPidForModTSconfig over

- config/v9/typo3-94.php
- src/Rector/v9/v4/UseSignalTablesDefinitionIsBeingBuiltSqlExpectedSchemaServiceRector.php
- stubs/Extbase/SignalSlot/Dispatcher.php
- stubs/Extensionmanager/Utility/InstallUtility.php
- stubs/Install/Service/SqlExpectedSchemaService.php
- tests/Rector/v9/v4/UseSignalTablesDefinitionIsBeingBuiltSqlExpectedSchemaService/Fixture/tables_definition_is_being_built.php.inc
- tests/Rector/v9/v4/UseSignalTablesDefinitionIsBeingBuiltSqlExpectedSchemaService/UseSignalTablesDefinitionIsBeingBuiltSqlExpectedSchemaServiceRectorTest.php
> [TASK] Change class callee of tablesDefinitionIsBeingBuilt

- config/v9/typo3-94.php
- src/Rector/v9/v4/UseGetMenuInsteadOfGetFirstWebPageRector.php
- stubs/Frontend/Page/PageRepository.php
- tests/Rector/v9/v4/UseGetMenuInsteadOfGetFirstWebPage/Fixture/use_get_menu_instead_of_get_first_web_page.php.inc
- tests/Rector/v9/v4/UseGetMenuInsteadOfGetFirstWebPage/Fixture/use_get_menu_instead_of_get_first_web_page_tsfe.php.inc
- tests/Rector/v9/v4/UseGetMenuInsteadOfGetFirstWebPage/UseGetMenuInsteadOfGetFirstWebPageRectorTest.php
> [TASK] Use method getMenu instead of getFirstWebPage

- config/v8/typo3-80.php
> [TASK] Use method getVariableProvider

- config/v9/typo3-94.php
- src/Rector/v9/v4/UseAddJsFileInsteadOfLoadJavascriptLibRector.php
- stubs/Backend/Template/ModuleTemplate.php
- stubs/Core/Page/PageRenderer.php
- tests/Rector/v9/v4/UseAddJsFileInsteadOfLoadJavascriptLib/Fixture/use_add_js_file.php.inc
- tests/Rector/v9/v4/UseAddJsFileInsteadOfLoadJavascriptLib/UseAddJsFileInsteadOfLoadJavascriptLibRectorTest.php
> [TASK] Use addJsFile instead of loadJavascriptLib

- config/v9/typo3-94.php
- src/Rector/v9/v4/UseRootlineUtilityInsteadOfGetRootlineMethodRector.php
- stubs/Core/Utility/RootlineUtility.php
- stubs/Frontend/Page/PageRepository.php
- tests/Rector/v9/v4/UseRootlineUtilityInsteadOfGetRootlineMethod/Fixture/use_rootline_utility.php.inc
- tests/Rector/v9/v4/UseRootlineUtilityInsteadOfGetRootlineMethod/UseRootlineUtilityInsteadOfGetRootlineMethodRectorTest.php
> [TASK] Use RootlineUtility instead of getRootLine method

- config/v9/typo3-92.php
- stubs/Core/Cache/Frontend/StringFrontend.php
- stubs/Core/Cache/Frontend/VariableFrontend.php
> [TASK] Use VariableFrontend instead of StringFrontend

- bin/typo3-rector
- composer.json
- config/services.php
- src/DependencyInjection/Typo3RectorContainerFactory.php
- src/HttpKernel/Typo3RectorKernel.php
- src/Set/Typo3RectorSetProvider.php
> [TASK] Add custom container and kernel

- build/box.json
- config/services.php
- src/DependencyInjection/PHPStanServicesFactory.php
- utils/phpstan/config/extension.neon
- utils/phpstan/config/rules.neon
- utils/phpstan/config/typo3-rector.neon
> [TASK] Add extension.neon automatically

- config/v9/typo3-94.php
- src/Rector/v8/v5/ContentObjectRendererFileResourceRector.php
- src/Rector/v9/v4/TemplateGetFileNameToFilePathSanitizerRector.php
- stubs/Core/Resource/Exception/FileDoesNotExistException.php
- stubs/Core/Resource/Exception/InvalidFileException.php
- stubs/Core/Resource/Exception/InvalidFileNameException.php
- stubs/Core/Resource/Exception/InvalidPathException.php
- stubs/Frontend/Resource/FilePathSanitizer.php
- tests/Rector/v9/v4/TemplateGetFileNameToFilePathSanitizer/Fixture/template_get_file_name_to_file_path_sanitizer.php.inc
- tests/Rector/v9/v4/TemplateGetFileNameToFilePathSanitizer/TemplateGetFileNameToFilePathSanitizerRectorTest.php
> [TASK] Use FilePathSanitizer->sanitize instead of getFileName

- config/v9/typo3-90.php
- src/Rector/v9/v0/UseNewComponentIdForPageTreeRector.php
- stubs/Extbase/Utility/ExtensionUtility.php
- tests/Rector/v9/v0/UseNewComponentIdForPageTree/Fixture/use_new_component_id_for_page_tree.php.inc
- tests/Rector/v9/v0/UseNewComponentIdForPageTree/UseNewComponentIdForPageTreeRectorTest.php
> [TASK] Use new navigationComponentId for typo3-pagetree

- config/v8/typo3-85.php
- stubs/Core/Utility/ArrayUtility.php
- stubs/Core/Utility/GeneralUtility.php
- stubs/Extbase/Utility/ArrayUtility.php
- Use the appropriate methods from ArrayUtility of core
- Method arrayMergeRecursiveOverrule is not refactored
Resolves: #631
> [TASK] Resolves methods of extbase ArrayUtility class

- config/v9/typo3-93.php
- src/Rector/v9/v3/MoveLanguageFilesFromExtensionLangRector.php
- stubs/Core/Localization/LanguageService.php
- tests/Rector/v9/v3/MoveLanguageFilesFromExtensionLang/Fixture/move_language_files.php.inc
- tests/Rector/v9/v3/MoveLanguageFilesFromExtensionLang/MoveLanguageFilesFromExtensionLangRectorTest.php
> [TASK] Use alternative language paths for locallang

- src/Rector/v10/v4/UseFileGetContentsForGetUrlRector.php
- tests/Rector/v10/v4/UseFileGetContentsForGetUrl/Fixture/use_file_get_contents.php.inc
> [BUGFIX] If value cannot be resolved nothing is changed

- config/v9/typo3-92.php
- src/Rector/v9/v2/GeneralUtilityGetUrlRequestHeadersRector.php
- tests/Rector/v9/v2/GeneralUtilityGetUrlRequestHeaders/Fixture/general_utility_get_url.php.inc
- tests/Rector/v9/v2/GeneralUtilityGetUrlRequestHeaders/GeneralUtilityGetUrlRequestHeadersRectorTest.php
> GeneralUtility::getUrl RequestHeaders as associative array 

- src/Rector/v9/v4/UseSignalTablesDefinitionIsBeingBuiltSqlExpectedSchemaServiceRector.php
Small not important change, but didn't wanted to add it together with antoher fix.
> [TASK] Adjust CGL

- config/v10/typo3-100.php
- rector.php
- src/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModulesRector.php
- src/Rector/v9/v2/GeneralUtilityGetUrlRequestHeadersRector.php
- stubs/Beuser/Controller/BackendUserController.php
- stubs/Beuser/Controller/BackendUserGroupController.php
- stubs/Core/Utility/ExtensionManagementUtility.php
- stubs/Extbase/Utility/ExtensionUtility.php
- stubs/Form/Controller/FormFrontendController.php
- tests/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModules/Fixture/refactor_configure_plugin.php.inc
- tests/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModules/Fixture/refactor_register_module.php.inc
- tests/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModules/UseControllerClassesInExtbasePluginsAndModulesRectorTest.php
- tests/bootstrap.php
> [TASK] Use controller classes when registering plugins/modules

- phpstan-baseline.neon
- src/Rector/v9/v4/UseSignalAfterExtensionInstallInsteadOfHasInstalledExtensionsRector.php
- stubs/Extensionmanager/Service/ExtensionManagementService.php
- tests/Rector/v9/v4/UseSignalAfterExtensionInstallInsteadOfHasInstalledExtensions/Fixture/after_extension_install.php.inc
- tests/Rector/v9/v4/UseSignalAfterExtensionInstallInsteadOfHasInstalledExtensions/UseSignalAfterExtensionInstallInsteadOfHasInstalledExtensionsRectorTest.php
> [TASK] Use signal afterExtensionInstall instead of hasInstalledExtensions (#1139)

- config/v9/typo3-94.php
Didn't think about added it to the config
> [TASK] Add UseSignalAfterExtensionInstall to TYPO3 9.4 Config

- config/v10/typo3-100.php
- src/Rector/v10/v0/ChangeDefaultCachingFrameworkNamesRector.php
- tests/Rector/v10/v0/ChangeDefaultCachingFrameworkNames/ChangeDefaultCachingFrameworkNamesRectorTest.php
- tests/Rector/v10/v0/ChangeDefaultCachingFrameworkNames/Fixture/change_default_caching_framework_names.php.inc
> [TASK] Change default caching framework names (#1253)

- config/v8/typo3-87.php
- src/Rector/v10/v0/ChangeDefaultCachingFrameworkNamesRector.php
- src/Rector/v8/v7/BackendUtilityGetRecordsByFieldToQueryBuilderRector.php
- stubs/Backend/Utility/BackendUtility.php
- stubs/Core/Database/ConnectionPool.php
- stubs/Core/Database/Query/QueryHelper.php
- stubs/Core/Database/Query/Restriction/BackendWorkspaceRestriction.php
- stubs/Core/Database/Query/Restriction/DeletedRestriction.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/v8/v7/BackendUtilityGetRecordsByFieldToQueryBuilder/BackendUtilityGetRecordsByFieldToQueryBuilderRectorTest.php
- tests/Rector/v8/v7/BackendUtilityGetRecordsByFieldToQueryBuilder/Fixture/get_records_by_field_to_query_builder.php.inc
- tests/Rector/v8/v7/BackendUtilityGetRecordsByFieldToQueryBuilder/Fixture/get_records_by_field_to_query_builder_simple.php.inc
> [TASK] Use QueryBuilder instead of BackendUtility::getRecordsByField

- config/v9/typo3-93.php
- stubs/Extbase/Mvc/Controller/Argument.php
- stubs/Extbase/Mvc/Controller/Arguments.php
> [TASK] Rename method getValidationResults

- config/v8/typo3-80.php
- src/Rector/v8/v0/RemoveCharsetConverterParametersRector.php
- tests/Rector/v8/v0/RemoveCharsetConverterParameters/Fixture/remove_charset_converter_parameters.php.inc
- tests/Rector/v8/v0/RemoveCharsetConverterParameters/RemoveCharsetConverterParametersRectorTest.php
> [TASK] Remove CharsetConvert Parameters (#503)

- config/v8/typo3-87.php
- src/Rector/v8/v7/RefactorPrintContentMethodsRector.php
- stubs/Backend/Controller/PageLayoutController.php
- stubs/Backend/Template/ModuleTemplate.php
- stubs/Taskcenter/Controller/TaskModuleController.php
- tests/Rector/v8/v7/RefactorPrintContentMethods/Fixture/refactor_print_method_page_layout_controller_rector.php.inc
- tests/Rector/v8/v7/RefactorPrintContentMethods/Fixture/refactor_print_method_task_module_controller_rector.php.inc
- tests/Rector/v8/v7/RefactorPrintContentMethods/RefactorPrintContentMethodsRectorTest.php
> [TASK] Deprecate printContent methods

- config/v8/typo3-83.php
- src/Rector/v8/v3/RefactorMethodFileContentRector.php
- stubs/Core/TypoScript/TemplateService.php
- tests/Rector/v8/v3/RefactorMethodFileContent/Fixture/refactor_method_file_content.php.inc
- tests/Rector/v8/v3/RefactorMethodFileContent/RefactorMethodFileContentRectorTest.php
> [TASK] Refactor method fileContent of class TemplateService

- src/Rector/v8/v5/MoveLanguageFilesFromLocallangToResourcesRector.php
- tests/Rector/v8/v5/MoveLanguageFilesFromLocallangToResources/Fixture/move_language_files.php.inc
- tests/Rector/v8/v5/MoveLanguageFilesFromLocallangToResources/MoveLanguageFilesFromLocallangToResourcesRectorTest.php
> [TASK] Move language files from EXT:lang

- config/v8/typo3-81.php
- src/Rector/v8/v1/TypoScriptFrontendControllerCharsetConverterRector.php
- stubs/Core/Charset/CharsetConverter.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v8/v1/TypoScriptFrontendControllerCharsetConverter/Fixture/method_csconv_tsfe.php.inc
- tests/Rector/v8/v1/TypoScriptFrontendControllerCharsetConverter/Fixture/property_csconv_cobj_tsfe.php.inc
- tests/Rector/v8/v1/TypoScriptFrontendControllerCharsetConverter/TypoScriptFrontendControllerCharsetConverterRectorTest.php
> [TASK] Refactor ->csConvObj and ->csConv()

- config/v8/typo3-80.php
> [TASK] ArrayUtility::filterAndSortByNumericKeys

- config/v8/typo3-80.php
- src/Rector/v8/v0/GetFileAbsFileNameRemoveDeprecatedArgumentsRector.php
- stubs/Core/Utility/CommandUtility.php
- tests/Rector/v8/v0/GetFileAbsFileNameRemoveDeprecatedArguments/Fixture/remove_arguments.php.inc
- tests/Rector/v8/v0/GetFileAbsFileNameRemoveDeprecatedArguments/GetFileAbsFileNameRemoveDeprecatedArgumentsRectorTest.php
> [TASK] Refactor various methods GeneralUtility

- config/v8/typo3-87.php
- src/Rector/v8/v7/RefactorArrayBrowserWrapValueRector.php
- stubs/Lowlevel/Utility/ArrayBrowser.php
- tests/Rector/v8/v7/RefactorArrayBrowserWrapValue/Fixture/refactor_array_browser_wrap_value.php.inc
- tests/Rector/v8/v7/RefactorArrayBrowserWrapValue/RefactorArrayBrowserWrapValueRectorTest.php
> [TASK] Refactor ArrayBrowser->wrapValue (#738)

- config/v8/typo3-83.php
- src/Rector/v8/v3/RefactorQueryViewTableWrapRector.php
- stubs/Core/Database/QueryView.php
- tests/Rector/v8/v3/RefactorQueryViewTableWrap/Fixture/refactor_query_view_table_wrap.php.inc
- tests/Rector/v8/v3/RefactorQueryViewTableWrap/RefactorQueryViewTableWrapRectorTest.php
Resolves #578
This is still WIP, but pushed in the hope of getting some help :)
> [TASK] Refactor QueryView->tableWrap to <pre> (#578)

- src/Rector/v8/v7/DataHandlerVariousMethodsAndMethodArgumentsRector.php
- tests/Rector/v8/v7/DataHandlerVariousMethodsAndMethodArguments/DataHandlerVariousMethodsAndMethodArgumentsRectorTest.php
- tests/Rector/v8/v7/DataHandlerVariousMethodsAndMethodArguments/Fixture/data_handler_various_methods_and_method_arguments.php.inc
> [TASK] DataHandler Various methods and method arguments (#762)

- config/v7/typo3-70.php
- stubs/Extbase/Persistence/Generic/Typo3QuerySettings.php
> [TASK] Deprecated extbase code is removed

- src/Console/Application.php
- src/Rector/v7/v4/MethodReadLLFileToLocalizationFactoryRector.php
- stubs/Core/Localization/LocalizationFactory.php
- stubs/Core/Utility/GeneralUtility.php
- tests/Rector/v7/v4/MethodReadLLFileToLocalizationFactory/Fixture/read_ll_file.php.inc
- tests/Rector/v7/v4/MethodReadLLFileToLocalizationFactory/MethodReadLLFileToLocalizationFactoryRectorTest.php
> [TASK] Use LocalizationFactory->getParsedData instead of readLLfile

- config/v9/typo3-90.php
- src/Helper/Typo3NodeResolver.php
- src/Rector/v9/v0/UseExtensionConfigurationApiRector.php
- stubs/Core/Configuration/ExtensionConfiguration.php
- stubs/Core/Utility/ExtensionManagementUtility.php
- tests/Rector/v9/v0/UseExtensionConfigurationApi/Fixture/use_extension_configuration_api.php.inc
- tests/Rector/v9/v0/UseExtensionConfigurationApi/UseExtensionConfigurationApiRectorTest.php
- tests/bootstrap.php
> [TASK] Use the new ExtensionConfiguration API

- README.md
- composer.json
- config/services.php
- ecs.php
- utils/generator/config/config.php
- utils/generator/src/Command/Typo3GenerateCommand.php
- utils/generator/src/FileSystem/TemplateFileSystem.php
- utils/generator/src/Finder/TemplateFinder.php
- utils/generator/src/Generator/FileGenerator.php
- utils/generator/src/ValueObject/Description.php
- utils/generator/src/ValueObject/Name.php
- utils/generator/src/ValueObject/Typo3RectorRecipe.php
- utils/generator/src/ValueObject/Typo3Version.php
- utils/generator/src/ValueObject/Url.php
- utils/generator/templates/src/Rector/__Major__/__Minor__/__Name__.php
- utils/generator/templates/tests/Rector/__Major__/__Minor__/__Name__/Fixture/fixture.php.inc
- utils/generator/templates/tests/Rector/__Major__/__Minor__/__Name__/__Name__Test.php.inc
- utils/generator/tests/ValueObject/Typo3RectorRecipeTest.php
> [TASK] Create generate command for TYPO3 Rector

- config/v8/typo3-84.php
- stubs/Backend/Form/FormResultCompiler.php
> [TASK] Replace JStop with addCssFiles in FormResultCompiler (#624)

- src/Rector/v10/v0/ChangeDefaultCachingFrameworkNamesRector.php
- tests/Rector/v10/v0/ChangeDefaultCachingFrameworkNames/Fixture/change_default_caching_framework_names.php.inc
> [BUGFIX] Wrong replacement of cache prefix

- tests/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModules/Fixture/refactor_configure_plugin.php.inc
> [BUGFIX] Add new test case

- config/v7/typo3-75.php
- src/Rector/v7/v5/UseExtPrefixForTcaIconFileRector.php
- tests/Rector/v7/v5/UseExtPrefixForTcaIconFile/Fixture/fixture.php.inc
- tests/Rector/v7/v5/UseExtPrefixForTcaIconFile/UseExtPrefixForTcaIconFileRectorTest.php
- utils/generator/templates/src/Rector/__Major__/__Minor__/__Name__.php
> [TASK] Use EXT: prefix for iconfile in TCA

- composer.json
> [TASK] Update rector to version 0.8.52

- README.md
- build/box.json
- src/DependencyInjection/Typo3RectorContainerFactory.php
- tests/bootstrap.php
- typo3.constants.php
> [TASK] Add file TYPO3 constants

- README.md
- src/Console/Command/Typo3InitCommand.php
- templates/rector.php.dist
> [TASK] Add init command to generate configuration file

- src/Rector/v8/v0/RefactorRemovedMethodsFromContentObjectRendererRector.php
- tests/Rector/v8/v0/RefactorRemovedMethodsFromContentObjectRenderer/Fixture/refactor_contentobjectrenderer_methods.php.inc
- tests/Rector/v8/v0/RefactorRemovedMethodsFromContentObjectRenderer/Fixture/refactor_contentobjectrenderer_methods_frontend_controller.php.inc
> [TASK] Check for array_shift(->args). Code cleanup

- build/box.json
- src/DependencyInjection/Typo3RectorContainerFactory.php
- templates/rector.php.dist
> [TASK] Fix phar build

- src/Configuration/Typo3Option.php
- src/PostRector/NameImportingPostRector.php
- templates/rector.php.dist
> [TASK] Add custom NameImportingPostRector

- src/Rector/v8/v7/RefactorGraphicalFunctionsTempPathAndCreateTemSubDirRector.php
- tests/Rector/v8/v7/RefactorGraphicalFunctionsTempPathAndCreateTemSubDirRector/Fixture/refactor_graphical_functions_temp_path_and_create_temp_subdir.php.inc
- tests/Rector/v8/v7/RefactorGraphicalFunctionsTempPathAndCreateTemSubDirRector/RefactorGraphicalFunctionsTempPathAndCreateTemSubDirRectorTest.php
> [TASK] Refactor GraphicalFunctions function and property (#763)

- utils/generator/templates/tests/Rector/__Major__/__Minor__/__Test_Directory__/Fixture/fixture.php.inc
> [BUGFIX] Add fixture file for generator

- config/v10/typo3-101.php
- stubs/Backend/History/RecordHistory.php
> [TASK Cleanup RecordHistory handling

- config/v7/typo3-74.php
- src/Rector/v7/v4/MoveLanguageFilesFromRemovedCmsExtensionRector.php
- src/Rector/v8/v5/MoveLanguageFilesFromLocallangToResourcesRector.php
- src/Rector/v8/v7/RefactorGraphicalFunctionsTempPathAndCreateTemSubDirRector.php
- src/Rector/v9/v3/MoveLanguageFilesFromExtensionLangRector.php
- tests/Rector/v7/v4/MoveLanguageFilesFromRemovedCmsExtension/Fixture/cms_language_files.php.inc
- tests/Rector/v7/v4/MoveLanguageFilesFromRemovedCmsExtension/MoveLanguageFilesFromRemovedCmsExtensionRectorTest.php
> [TASK] Move language files from EXT:cms

- config/v8/typo3-84.php
- stubs/Rtehtmlarea/Controller/SpellCheckingController.php
> [TASK] Change RTEHtmlArea Spellchecker entrypoint (#622)

- config/v8/typo3-80.php
- src/Rector/v8/v0/RemoveLangCsConvObjAndParserFactoryRector.php
- tests/Rector/v8/v0/RemoveLangCsConvObjAndParserFactory/Fixture/remove_lang_csconv_and_parser_factory.php.inc
- tests/Rector/v8/v0/RemoveLangCsConvObjAndParserFactory/RemoveLangCsConvObjAndParserFactoryRectorTest.php
> [TASK] Remove CsConvObj and ParserFactory from LanguageService::class (#474)

- config/v9/typo3-94.php
- src/Rector/v9/v4/UseClassSchemaInsteadReflectionServiceMethodsRector.php
- stubs/Extbase/Reflection/ClassSchema.php
- stubs/Extbase/Reflection/ReflectionService.php
- tests/Rector/v9/v4/UseClassSchemaInsteadReflectionServiceMethods/Fixture/class.php.inc
- tests/Rector/v9/v4/UseClassSchemaInsteadReflectionServiceMethods/Fixture/method.php.inc
- tests/Rector/v9/v4/UseClassSchemaInsteadReflectionServiceMethods/Fixture/properties.php.inc
- tests/Rector/v9/v4/UseClassSchemaInsteadReflectionServiceMethods/UseClassSchemaInsteadReflectionServiceMethodsRectorTest.php
> [TASK] Deprecate methods in ReflectionService

- build/box.json
- src/DependencyInjection/Typo3RectorContainerFactory.php
> [TASK] Include stubs in phar file

- config/v10/typo3-101.php
- src/Rector/v10/v1/SendNotifyEmailToMailApiRector.php
- stubs/Core/Mail/MailMessage.php
- stubs/Core/Utility/MailUtility.php
- stubs/Frontend/ContentObject/ContentObjectRenderer.php
- stubs/Frontend/Plugin/AbstractPlugin.php
- stubs/Symfony/Mime/Address.php
- tests/Rector/v10/v1/SendNotifyEmailToMailApi/Fixture/send_notify_email_to_mail_api.php.inc
- tests/Rector/v10/v1/SendNotifyEmailToMailApi/Fixture/send_notify_tsfe_cobj.php.inc
- tests/Rector/v10/v1/SendNotifyEmailToMailApi/SendNotifyEmailToMailApiRectorTest.php
> [TASK] ContentObjectRenderer::sendNotifyEmail to Mail API

- config/services.php
- src/Configuration/Typo3Option.php
- src/Console/Output/DecoratedConsoleOutputFormatter.php
- templates/rector.php.dist
- utils/phpstan/src/Rules/AddSeeDocBlockForRectorClass.php
> [TASK] Output changelog url when rector is applied

- config/v9/typo3-93.php
- src/Helper/Typo3NodeResolver.php
- src/Rector/v9/v3/RefactorTsConfigRelatedMethodsRector.php
- stubs/Core/Authentication/BackendUserAuthentication.php
- tests/Rector/v9/v3/RefactorTsConfigRelatedMethods/Fixture/get_user_ts_config.php.inc
- tests/Rector/v9/v3/RefactorTsConfigRelatedMethods/RefactorTsConfigRelatedMethodsRectorTest.php
> [TASK] Deprecate some TSconfig related methods

- config/v10/typo3-101.php
- src/Rector/v10/v1/RefactorInternalPropertiesOfTSFERector.php
- stubs/Core/Utility/GeneralUtility.php
- stubs/Core/Utility/HttpUtility.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- stubs/Frontend/Page/CacheHashCalculator.php
- tests/Rector/v10/v1/RefactorInternalPropertiesOfTSFE/Fixture/fixture.php.inc
- tests/Rector/v10/v1/RefactorInternalPropertiesOfTSFE/RefactorInternalPropertiesOfTSFERectorTest.php
> [TASK] Refactor Internal public TSFE properties

- config/v9/typo3-92.php
- src/Rector/v9/v2/PageNotFoundAndErrorHandlingRector.php
- stubs/Core/Controller/ErrorPageController.php
- stubs/Core/Http/ImmediateResponseException.php
- stubs/Core/Utility/GeneralUtility.php
- stubs/Frontend/Controller/ErrorController.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v9/v2/PageNotFoundAndErrorHandling/Fixture/check_page_unavailable_handler.php.inc
- tests/Rector/v9/v2/PageNotFoundAndErrorHandling/Fixture/page_error_handler.php.inc
- tests/Rector/v9/v2/PageNotFoundAndErrorHandling/Fixture/page_not_found_action.php.inc
- tests/Rector/v9/v2/PageNotFoundAndErrorHandling/PageNotFoundAndErrorHandlingRectorTest.php
> [TASK] Page Not Found And Error handling in Frontend

- src/Rector/v9/v0/InjectAnnotationRector.php
- tests/Rector/v9/v0/InjectAnnotation/Fixture/inject.php.inc
- tests/Rector/v9/v0/InjectAnnotation/Source/ShortInjectionClass.php
> [BUGFIX] InjectRules works also for already ShortClassName

- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
- tests/Rector/v9/v0/MoveRenderArgumentsToInitializeArgumentsMethod/Fixture/my_privacy_text_view_helper.php.inc
- tests/Rector/v9/v0/MoveRenderArgumentsToInitializeArgumentsMethod/Fixture/my_second_viewhelper.php.inc
- tests/Rector/v9/v0/MoveRenderArgumentsToInitializeArgumentsMethod/Fixture/my_viewhelper.php.inc
> [BUGFIX] Add correct type infered by type declarations

- config/v9/typo3-90.php
- src/Rector/v9/v0/ReplaceExtKeyWithExtensionKeyRector.php
- tests/Rector/v9/v0/ReplaceExtKeyWithExtensionKey/Fixture/ext_localconf.php.inc
- tests/Rector/v9/v0/ReplaceExtKeyWithExtensionKey/Fixture/ext_tables.php.inc
- tests/Rector/v9/v0/ReplaceExtKeyWithExtensionKey/ReplaceExtKeyWithExtensionKeyRectorTest.php
- utils/generator/src/Command/Typo3GenerateCommand.php
> [TASK] Replace  in ext_localconf.php and ext_tables.php

- Migrations/TYPO3/8.7/typo3/sysext/core/Migrations/TcaMigration.php
- config/v7/typo3-76.php
- config/v8/typo3-84.php
- src/Rector/v8/v4/SubstituteOldWizardIconsRector.php
- tests/Rector/v8/v4/SubstituteOldWizardIcons/Fixture/substitute_old_wizard_icons.php.inc
- tests/Rector/v8/v4/SubstituteOldWizardIcons/SubstituteOldWizardIconsRectorTest.php
> [TASK] Substitute wizard icons with new ones

- Migrations/TYPO3/9.5/typo3/sysext/core/Migrations/TcaMigration.php
- config/v7/typo3-76.php
- src/Rector/v7/v6/AddRenderTypeToSelectFieldRector.php
- tests/Rector/v7/v6/AddRenderTypeToSelectField/AddRenderTypeToSelectFieldRectorTest.php
- tests/Rector/v7/v6/AddRenderTypeToSelectField/Fixture/add_render_type.php.inc
> [TASK] Add renderType for select fields

- Migrations/TYPO3/7.6/typo3/sysext/core/Migrations/TcaMigration.php
- config/v7/typo3-76.php
- src/Rector/v7/v6/RemoveIconOptionForRenderTypeSelectRector.php
- tests/Rector/v7/v6/RemoveIconOptionForRenderTypeSelect/Fixture/remove_icon_option_for_select.php.inc
- tests/Rector/v7/v6/RemoveIconOptionForRenderTypeSelect/RemoveIconOptionForRenderTypeSelectRectorTest.php
> [TASK] TCA icon options have been removed

- Migrations/TYPO3/7.6/typo3/sysext/core/Migrations/TcaMigration.php
- config/v7/typo3-75.php
- src/Rector/v7/v5/RemoveIconsInOptionTagsRector.php
- tests/Rector/v7/v5/RemoveIconsInOptionTags/Fixture/remove_icons_in_option_tags.php.inc
- tests/Rector/v7/v5/RemoveIconsInOptionTags/RemoveIconsInOptionTagsRectorTest.php
> [TASK] Remove option iconsInOptionTags

- Migrations/TYPO3/8.7/typo3/sysext/core/Migrations/TcaMigration.php
- config/v8/typo3-83.php
- src/Rector/v8/v3/RemovedTcaSelectTreeOptionsRector.php
- tests/Rector/v8/v3/RemovedTcaSelectTreeOptions/Fixture/removed_tca_select_tree_options.php.inc
- tests/Rector/v8/v3/RemovedTcaSelectTreeOptions/RemovedTcaSelectTreeOptionsRectorTest.php
> [TASK] Removed TCA tree options: width, allowRecursiveMode, autoSizeMax

- Migrations/TYPO3/8.7/typo3/sysext/core/Migrations/TcaMigration.php
- config/v8/typo3-84.php
- src/Rector/v8/v4/RemoveOptionShowIfRteRector.php
- tests/Rector/v8/v4/RemoveOptionShowIfRte/Fixture/remove_option_show_if_rte.php.inc
- tests/Rector/v8/v4/RemoveOptionShowIfRte/RemoveOptionShowIfRteRectorTest.php
> [TASK] Dropped TCA option showIfRTE in type=check

- config/v8/typo3-85.php
- src/Rector/v8/v5/RemoveOptionVersioningFollowPagesRector.php
- tests/Rector/v8/v5/RemoveOptionVersioningFollowPages/Fixture/remove_option_versioning_followPages.php.inc
- tests/Rector/v8/v5/RemoveOptionVersioningFollowPages/RemoveOptionVersioningFollowPagesRectorTest.php
> [TASK] TCA option versioning_followPages removed

- Migrations/TYPO3/8.7/typo3/sysext/core/Migrations/TcaMigration.php
- Migrations/TYPO3/9.5/typo3/sysext/core/Migrations/TcaMigration.php
- config/v8/typo3-86.php
- src/Rector/v8/v6/MoveRequestUpdateOptionFromControlToColumnsRector.php
- tests/Rector/v8/v6/MoveRequestUpdateOptionFromControlToColumns/Fixture/move_request_update_option.php.inc
- tests/Rector/v8/v6/MoveRequestUpdateOptionFromControlToColumns/MoveRequestUpdateOptionFromControlToColumnsRectorTest.php
> [TASK] TCA ctrl field requestUpdate dropped

- Migrations/TYPO3/8.7/typo3/sysext/core/Migrations/TcaMigration.php
- config/v8/typo3-86.php
- src/Helper/TcaHelperTrait.php
- src/Rector/v8/v6/RichtextFromDefaultExtrasToEnableRichtextRector.php
- tests/Rector/v8/v6/RichtextFromDefaultExtrasToEnableRichtext/Fixture/richtext_from_default_extras.php.inc
- tests/Rector/v8/v6/RichtextFromDefaultExtrasToEnableRichtext/RichtextFromDefaultExtrasToEnableRichtextRectorTest.php
> [TASK] TCA richtext configuration in defaultExtras dropped

- src/Rector/v8/v1/TypoScriptFrontendControllerCharsetConverterRector.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v8/v1/TypoScriptFrontendControllerCharsetConverter/Fixture/method_csconv_tsfe.php.inc
> [BUGFIX] Check for concrete method calls

- config/v10/typo3-100.php
- config/v10/typo3-103.php
- config/v7/typo3-70.php
- config/v7/typo3-76.php
- config/v8/typo3-84.php
- config/v8/typo3-86.php
- config/v8/typo3-87.php
- config/v9/typo3-90.php
- config/v9/typo3-92.php
- src/Rector/v7/v6/RemoveIconOptionForRenderTypeSelectRector.php
- tests/Rector/v7/v6/RemoveIconOptionForRenderTypeSelect/Fixture/remove_icon_option_for_select.php.inc
fixes #1723
composer run fix-style to allow committing with enabled hooks
> do not duplicate showIconTable entries in selectSingle TCA

- Migrations/TYPO3/9.5/typo3/sysext/core/Migrations/TcaMigration.php
- config/v8/typo3-87.php
- src/Rector/v8/v1/TypoScriptFrontendControllerCharsetConverterRector.php
- src/Rector/v8/v7/RemoveConfigMaxFromInputDateTimeFieldsRector.php
- tests/Rector/v8/v7/RemoveConfigMaxFromInputDateTimeFields/Fixture/remove_config_max_from_datetime.php.inc
- tests/Rector/v8/v7/RemoveConfigMaxFromInputDateTimeFields/RemoveConfigMaxFromInputDateTimeFieldsRectorTest.php
> [TASK] Remove TCA config 'max' on inputDateTime fields

- config/v8/typo3-87.php
- src/Rector/v8/v7/RemoveLocalizationModeKeepIfNeededRector.php
- tests/Rector/v8/v7/RemoveLocalizationModeKeepIfNeeded/Fixture/remove_localization_mode_keep_if_needed.php.inc
- tests/Rector/v8/v7/RemoveLocalizationModeKeepIfNeeded/RemoveLocalizationModeKeepIfNeededRectorTest.php
> [TASK] Remove localizationMode keep if allowLanguageSynchronization

- config/v7/typo3-70.php
- src/Rector/v7/v0/RemoveDivider2TabsConfigurationRector.php
- tests/Rector/v7/v0/RemoveDivider2TabsConfiguration/Fixture/remove_divider2tabs_configuration.php.inc
- tests/Rector/v7/v0/RemoveDivider2TabsConfiguration/RemoveDivider2TabsConfigurationRectorTest.php
> [TASK] Remove divider2tabs

- config/v8/typo3-87.php
- src/Helper/TcaHelperTrait.php
- src/Rector/v8/v7/MoveForeignTypesToOverrideChildTcaRector.php
- stubs/Core/Utility/ExtensionManagementUtility.php
- tests/Rector/v8/v7/MoveForeignTypesToOverrideChildTca/Fixture/noOverrideChildTca.php.inc
- tests/Rector/v8/v7/MoveForeignTypesToOverrideChildTca/Fixture/noOverrideChildTcaTypes.php.inc
- tests/Rector/v8/v7/MoveForeignTypesToOverrideChildTca/Fixture/withExtensionManagementUtilityGetFileFieldTcaConfig.php.inc
- tests/Rector/v8/v7/MoveForeignTypesToOverrideChildTca/Fixture/withOverrideChildTcaTypes.php.inc
- tests/Rector/v8/v7/MoveForeignTypesToOverrideChildTca/MoveForeignTypesToOverrideChildTcaRectorTest.php
fixes #739 
feel free to drop the last refactoring commit if you don't see its benefit. I'm not certain if the extraction of the generator helps, but it might come in handy for further refactorings
> Move foreign_types to overrideChildTca

- config/v9/typo3-90.php
- src/Helper/TcaHelperTrait.php
- src/Rector/v9/v0/RemoveOptionLocalizeChildrenAtParentLocalizationRector.php
- tests/Rector/v9/v0/RemoveOptionLocalizeChildrenAtParentLocalization/Fixture/remove_option_localizeChildrenAtParentLocalization.php.inc
- tests/Rector/v9/v0/RemoveOptionLocalizeChildrenAtParentLocalization/RemoveOptionLocalizeChildrenAtParentLocalizationRectorTest.php
> [TASK] Remove option localizeChildrenAtParentLocalization

- src/Rector/v9/v0/ReplaceExtKeyWithExtensionKeyRector.php
> [BUGFIX] Check if SmartFileInfo attribute is set

- src/Rector/v9/v0/InjectAnnotationRector.php
- tests/Rector/v9/v0/InjectAnnotation/Fixture/inject.php.inc
> [BUGFIX] Do not add method twice

- config/typo3-11.0.php
- config/v11/typo3-110.php
- src/Rector/v11/v0/ForwardResponseInsteadOfForwardMethodRector.php
- src/Set/Typo3SetList.php
- stubs/Extbase/Http/ForwardResponse.php
- stubs/Extbase/Mvc/Controller/ActionController.php
- stubs/Psr/Http/Message/ResponseInterface.php
- tests/Rector/v11/v0/ForwardResponseInsteadOfForwardMethod/Fixture/foward_response_instead_of_method_forward.php.inc
- tests/Rector/v11/v0/ForwardResponseInsteadOfForwardMethod/ForwardResponseInsteadOfForwardMethodRectorTest.php
> [TASK] Use ForwardResponse instead of forward method

- Migrations/TYPO3/11.0/typo3/sysext/core/Migrations/TcaMigration.php
> [TASK] Add TcaMigration.php for version 11

- config/v11/typo3-110.php
- src/Helper/Typo3NodeResolver.php
- src/Rector/v11/v0/DateTimeAspectInsteadOfGlobalsExecTimeRector.php
- tests/Rector/v11/v0/DateTimeAspectInsteadOfGlobalsExecTime/DateTimeAspectInsteadOfGlobalsExecTimeRectorTest.php
- tests/Rector/v11/v0/DateTimeAspectInsteadOfGlobalsExecTime/Fixture/datetime_aspect_instead_of_globals.php.inc
> [TASK] Return timestamp as integer in DateTimeAspect

- config/v11/typo3-110.php
- src/Rector/v11/v0/UniqueListFromStringUtilityRector.php
- stubs/Core/Utility/GeneralUtility.php
- stubs/Core/Utility/StringUtility.php
- tests/Rector/v11/v0/UniqueListFromStringUtility/Fixture/unique_list_from_string_utility.php.inc
- tests/Rector/v11/v0/UniqueListFromStringUtility/UniqueListFromStringUtilityRectorTest.php
> [TASK] Use StringUtility::uniqueList()

- config/v11/typo3-110.php
- src/Rector/v11/v0/GetClickMenuOnIconTagParametersRector.php
- stubs/Backend/Utility/BackendUtility.php
- tests/Rector/v11/v0/GetClickMenuOnIconTagParameters/Fixture/get_click_menu_on_icon_tag.php.inc
- tests/Rector/v11/v0/GetClickMenuOnIconTagParameters/GetClickMenuOnIconTagParametersRectorTest.php
> [TASK] Use BackendUtility::getClickMenuOnIconTagParameters() if needed

- config/v11/typo3-110.php
- src/Rector/v11/v0/RemoveAddQueryStringMethodRector.php
- stubs/Extbase/Mvc/Web/Routing/UriBuilder.php
- stubs/Frontend/ContentObject/ContentObjectRenderer.php
- tests/Rector/v11/v0/RemoveAddQueryStringMethod/Fixture/remove_add_query_string_method_uri_builder.php.inc
- tests/Rector/v11/v0/RemoveAddQueryStringMethod/Fixture/remove_last_arguments_get_query_params.php.inc
- tests/Rector/v11/v0/RemoveAddQueryStringMethod/RemoveAddQueryStringMethodRectorTest.php
> [TASK] Remove TypoScript option addQueryString.method

- config/v11/typo3-110.php
- src/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php
- stubs/Core/Http/ResponseFactoryInterface.php
- stubs/Core/Utility/HttpUtility.php
- stubs/Extbase/Http/ForwardResponse.php
- stubs/Extbase/Mvc/Controller/ActionController.php
- stubs/Extbase/Mvc/View/ViewInterface.php
- stubs/Psr/Http/Message/ResponseInterface.php
- tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterface/ExtbaseControllerActionsMustReturnResponseInterfaceRectorTest.php
- tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterface/Fixture/extbase_controller_actions_return_response_interface.php.inc
> [TASK] Extbase controller actions must return ResponseInterface

- config/v10/typo3-104.php
- src/Rector/v10/v4/SubstituteConstantsModeAndRequestTypeRector.php
- stubs/Core/Http/ApplicationType.php
- stubs/Psr/Http/Message/ServerRequestInterface.php
- tests/Rector/v10/v4/SubstituteConstantsModeAndRequestType/Fixture/application_type.php.inc
- tests/Rector/v10/v4/SubstituteConstantsModeAndRequestType/Fixture/ext_localconf.php.inc
- tests/Rector/v10/v4/SubstituteConstantsModeAndRequestType/Fixture/ext_tables.php.inc
- tests/Rector/v10/v4/SubstituteConstantsModeAndRequestType/SubstituteConstantsModeAndRequestTypeRectorTest.php
- typo3.constants.php
> [TASK] TYPO3_MODE and TYPO3_REQUESTTYPE constants

- Migrations/TYPO3/8.7/typo3/sysext/core/Migrations/TcaMigration.php
- config/v8/typo3-83.php
- src/Rector/v8/v3/SoftReferencesFunctionalityRemovedRector.php
- tests/Rector/v8/v3/SoftReferencesFunctionalityRemoved/Fixture/soft_references_functionality_removed.php.inc
- tests/Rector/v8/v3/SoftReferencesFunctionalityRemoved/SoftReferencesFunctionalityRemovedRectorTest.php
> [TASK] TSconfig and TStemplate soft references functionality removed

- Migrations/TYPO3/9.5/typo3/sysext/core/Migrations/TcaMigration.php
- config/v8/typo3-86.php
- src/Helper/TcaHelperTrait.php
- src/Rector/v8/v6/MigrateSelectShowIconTableRector.php
- tests/Rector/v8/v6/MigrateSelectShowIconTable/Fixture/migrate_select_show_icon_table.php.inc
- tests/Rector/v8/v6/MigrateSelectShowIconTable/MigrateSelectShowIconTableRectorTest.php
> [TASK] Migrate select showIconTable

- Migrations/TYPO3/7.6/typo3/sysext/core/Migrations/TcaMigration.php
- config/v7/typo3-74.php
- src/Rector/v7/v4/DropAdditionalPaletteRector.php
- tests/Rector/v7/v4/DropAdditionalPalette/DropAdditionalPaletteRectorTest.php
- tests/Rector/v7/v4/DropAdditionalPalette/Fixture/drop_additional_palette.php.inc
> [TASK] TCA: Drop additional palette

- Migrations/TYPO3/8.7/typo3/sysext/core/Migrations/TcaMigration.php
- config/v8/typo3-85.php
- src/Rector/v8/v5/RemoveSupportForTransForeignTableRector.php
- tests/Rector/v8/v5/RemoveSupportForTransForeignTable/Fixture/remove_support_for_transforeigntable.php.inc
- tests/Rector/v8/v5/RemoveSupportForTransForeignTable/RemoveSupportForTransForeignTableRectorTest.php
> [TASK] Remove support for transForeignTable in TCA

- Migrations/TYPO3/8.7/typo3/sysext/core/Migrations/TcaMigration.php
- config/v8/typo3-86.php
- src/Rector/v8/v6/RemoveL10nModeNoCopyRector.php
- tests/Rector/v8/v6/RemoveL10nModeNoCopy/Fixture/remove_l10n_mode_no_copy.php.inc
- tests/Rector/v8/v6/RemoveL10nModeNoCopy/RemoveL10nModeNoCopyRectorTest.php
> [TASK] Remove l10n_mode noCopy

- Migrations/TYPO3/9.5/typo3/sysext/core/Migrations/TcaMigration.php
- config/v8/typo3-86.php
- src/Helper/TcaHelperTrait.php
- src/Rector/v8/v3/RemovedTcaSelectTreeOptionsRector.php
- src/Rector/v8/v6/AddTypeToColumnConfigRector.php
- src/Rector/v8/v6/MigrateOptionsOfTypeGroupRector.php
- src/Rector/v8/v6/RemoveL10nModeNoCopyRector.php
- tests/Rector/v8/v6/MigrateOptionsOfTypeGroup/Fixture/migrate_options_of_type_group.php.inc
- tests/Rector/v8/v6/MigrateOptionsOfTypeGroup/MigrateOptionsOfTypeGroupRectorTest.php
> [TASK] Migrate options if type group in TCA

- config/v10/tca-104.php
- config/v10/typo3-100.php
- config/v10/typo3-103.php
- config/v7/tca-76.php
- config/v7/typo3-70.php
- config/v7/typo3-74.php
- config/v7/typo3-76.php
- config/v8/tca-87.php
- config/v8/typo3-83.php
- config/v8/typo3-84.php
- config/v8/typo3-85.php
- config/v8/typo3-86.php
- config/v8/typo3-87.php
- config/v9/tca-95.php
- config/v9/typo3-90.php
- src/Set/Typo3SetList.php
> [TASK] Add dedicated TCA configuration

- config/v10/typo3-101.php
- config/v10/typo3-103.php
- config/v10/typo3-104.php
- config/v7/typo3-70.php
- config/v7/typo3-76.php
- config/v8/typo3-80.php
- config/v8/typo3-84.php
- config/v8/typo3-85.php
- config/v8/typo3-87.php
- config/v9/typo3-90.php
- config/v9/typo3-93.php
- config/v9/typo3-95.php
> [BUGFIX] Add inlining with new ValueObjectInliner

- .github/workflows/code_coverage.yaml
- .github/workflows/coding_standard.yaml
- .github/workflows/docs.yaml
- .github/workflows/phpstan.yaml
- .github/workflows/rector.yaml
- .github/workflows/tests.yaml
- composer.json
> [BUGFIX] Use composer update instead of composer install

- docs/configuration_and_processing.md
> [TASK] Add an example for the TCA sets

- src/Rector/v9/v4/ConstantToEnvironmentCallRector.php
- tests/Rector/v9/v4/ConstantToEnvironmentCall/Fixture/environment_constants.php.inc
> [BUGFIX] Do not substitute in class property

- composer.json
- src/Rector/v7/v6/RemoveIconOptionForRenderTypeSelectRector.php
- tests/Rector/v7/v6/RemoveIconOptionForRenderTypeSelect/Fixture/remove_icon_option_for_select.php.inc
- tests/Rector/v8/v6/MigrateSelectShowIconTable/Fixture/migrate_select_show_icon_table.php.inc
> [BUGFIX] Do not add showIconTable if not necessary

- src/Rector/v9/v0/InjectAnnotationRector.php
- tests/Rector/v9/v0/InjectAnnotation/Fixture/inject.php.inc
- tests/Rector/v9/v0/InjectAnnotation/Source/ManufacturerRepository.php
> [BUGFIX] Do not break if non docblock is given

- docs/installation.md
- stubs/Core/Core/Bootstrap.php
- stubs/Core/Core/ClassLoadingInformation.php
- stubs/Core/Core/SystemEnvironmentBuilder.php
> [TASK] Add autoloading for version 8 in the docs

- config/v9/typo3-90.php
- ecs.php
> [TASK] Remove StringClassNameToClassConstantRector from config

- src/PostRector/NameImportingPostRector.php
- tests/Rector/Name/RenameClassRector/AutoImportNamesParameterTest.php
- tests/Rector/Name/RenameClassRector/FixtureAutoImportNames/import_names.php.inc
- tests/Rector/Name/RenameClassRector/SkipAutoImportNames/skip_import_names.php.inc
- tests/Rector/Name/RenameClassRector/SkipAutoImportNamesParameterTest.php
- tests/Rector/Name/RenameClassRector/Source/FirstOriginalClass.php
- tests/Rector/Name/RenameClassRector/Source/NewClass.php
- tests/Rector/Name/RenameClassRector/Source/OldClass.php
- tests/Rector/Name/RenameClassRector/Source/SecondOriginalClass.php
> [TASK] Use Skipper library and introduce testcase

- box.json
- src/Compiler/Composer/ComposerJsonManipulator.php
> [BUGFIX] Enable indexing of phar file

- docs/configuration_and_processing.md
- templates/rector.php.dist
> [TASK] Add more files to skip and clarify configuration section in docs

- src/Rector/v10/v1/RegisterPluginWithVendorNameRector.php
> [BUGFIX] Use UpperCamelCase for FQN for extension with underscore

- composer.json
> [TASK] Update to Rector version 0.9.10

- src/Rector/v9/v4/UseLanguageAspectForTsfeLanguagePropertiesRector.php
- tests/Rector/v9/v4/UseLanguageAspectForTsfeLanguageProperties/Fixture/use_language_aspect.php.inc
> [TASK] Use getPropertyFromAspect instead of getAspect

- .dockerignore
- .gitattributes
- .github/workflows/docker.yml
- .gitignore
- Dockerfile
- docker-entrypoint.sh
> [TASK] Build Docker image

- config/general/typo3.php
- config/typo3-10.4.php
- config/typo3-11.0.php
- config/typo3-7.6.php
- config/typo3-8.7.php
- config/typo3-9.5.php
- src/Helper/FileHelperTrait.php
- src/Rector/General/ConvertTypo3ConfVarsRector.php
- src/Rector/v11/v0/SubstituteConstantsModeAndRequestTypeRector.php
- src/Rector/v9/v0/ReplaceExtKeyWithExtensionKeyRector.php
- tests/Rector/General/ConvertTypo3ConfVars/ConvertTypo3ConfVarsRectorTest.php
- tests/Rector/General/ConvertTypo3ConfVars/Fixture/ext_localconf.php.inc
- utils/phpstan/src/Rules/AddSeeDocBlockForRectorClass.php
> [TASK] Convert TYPO3_CONF_VARS to GLOBALS['TYPO3_CONF_VARS']

- composer.json
- src/Console/Output/DecoratedConsoleOutputFormatter.php
- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
- src/PostRector/NameImportingPostRector.php
- src/Rector/v9/v0/IgnoreValidationAnnotationRector.php
- src/Rector/v9/v0/InjectAnnotationRector.php
- src/Rector/v9/v0/MoveRenderArgumentsToInitializeArgumentsMethodRector.php
- src/Rector/v9/v0/ReplaceAnnotationRector.php
- src/Rector/v9/v3/ValidateAnnotationRector.php
- src/Rector/v9/v4/UseContextApiForVersioningWorkspaceIdRector.php
- src/Rector/v9/v4/UseRootlineUtilityInsteadOfGetRootlineMethodRector.php
- src/Rector/v9/v5/RemoveFlushCachesRector.php
- src/Rector/v9/v5/RemoveInternalAnnotationRector.php
> [TASK] Update to Rector version 0.9.16

- Dockerfile
Files and folders in `/tmp` must be readable and writable for all users to run the container as a different user than root
This patch also reorder the installation of the dependencies of PHP extensions before their activation to avoid PHP warnings
> [BUGFIX] Chmod /tmp to be able to run as non root

- composer.json
- config/database-connection-to-dbal.php
- config/services.php
- phpstan-baseline.neon
- src/Helper/DependencyInjection.php
> [TASK] Add wrapper for symfony di service

- composer.json
- config/v10/typo3-104-composer-packages.php
- config/v11/typo3-110-composer-packages.php
- src/Set/Typo3SetList.php
> [TASK] Add basic composer packages update sets

- config/v10/typo3-101.php
- config/v7/typo3-76.php
- phpstan.neon
- stubs/TYPO3Fluid/Core/Rendering/RenderingContext.php
> [BUGFIX] PropertyToMethodRector not found

- config/v10/typo3-104-composer-packages.php
- config/v11/typo3-110-composer-packages.php
> [BUGFIX] Remove outdated composer packages

- config/nimut-testing-framework-to-typo3-testing-framework.php
- phpstan-baseline.neon
- phpstan.neon
- rector.php
- src/Set/Typo3SetList.php
- stubs/Nimut/TestingFramework/Exception/Exception.php
- stubs/Nimut/TestingFramework/MockObject/AccessibleMockObjectInterface.php
- stubs/Nimut/TestingFramework/TestCase/FunctionalTestCase.php
- stubs/Nimut/TestingFramework/TestCase/UnitTestCase.php
- stubs/Nimut/TestingFramework/TestCase/ViewHelperBaseTestcase.php
- stubs/TestingFramework/Core/AccessibleObjectInterface.php
- stubs/TestingFramework/Core/Exception.php
- stubs/TestingFramework/Core/Functional/FunctionalTestCase.php
- stubs/TestingFramework/Core/Unit/UnitTestCase.php
- stubs/TestingFramework/Fluid/Unit/ViewHelpers/ViewHelperBaseTestcase.php
- tests/Rector/Nimut/TestingFramework/Fixture/functional_test_fixture.php.inc
- tests/Rector/Nimut/TestingFramework/Fixture/unit_test_fixture.php.inc
- tests/Rector/Nimut/TestingFramework/Fixture/viewhelper_test_fixture.php.inc
- tests/Rector/Nimut/TestingFramework/NimutTestingFrameworkToTYPO3TestingFrameworkTest.php
> [TASK] Move from nimut testing framework to TYPO3 testing framework

- src/Rector/v8/v6/RefactorTCARector.php
- tests/Rector/v8/v6/RefactorTCA/Fixture/wizard_suggest.php.inc
> [BUGFIX] Keep custom wizards

- config/nimut-testingframework/nimut-testing-framework-to-typo3-testing-framework.php
- config/solr/solr_php_client_to_solarium.php
- config/v8/typo3-81.php
- src/Rector/Extensions/solr/ApacheSolrDocumentToSolariumDocumentRector.php
- src/Rector/v5/v0/ApacheSolrDocumentToSolariumDocumentRector.php
- src/Set/Typo3SetList.php
- stubs/ApacheSolrForTypo3/Solr/System/Solr/Document/Document.php
- stubs/ApacheSolrForTypo3/Solr/System/Solr/ResponseAdapter.php
- stubs/SolrPhpClient/Apache_Solr_Document.php
- stubs/SolrPhpClient/Apache_Solr_Response.php
- tests/Rector/Extensions/solr/ApacheSolrDocumentToSolariumDocument/ApacheSolrDocumentToSolariumDocumentRectorTest.php
- tests/Rector/Extensions/solr/ApacheSolrDocumentToSolariumDocument/Fixture/fixture.php.inc
> [TASK] Migrate from SolrPhpClient to solarium

- config/typo3-104-composer-packages.php
- config/typo3-110-composer-packages.php
- config/typo3-95-composer-packages.php
- src/Set/Typo3SetList.php
> [BUGFIX] Use composer sets explicitly

- src/Rector/v9/v3/ValidateAnnotationRector.php
> [BUGFIX] Leverage of the internal PhpDocInfo cache

- ecs.php
- src/Rector/Experimental/OptionalConstructorToHardRequirementRector.php
- stubs/Core/Database/Connection.php
- stubs/Core/Database/ConnectionPool.php
- stubs/Core/Log/LogManager.php
- stubs/Core/Log/Logger.php
- tests/Rector/Experimental/OptionalConstructorToHardRequirement/Fixture/fixture_logger.php.inc
> [TASK] Enhance OptionalConstructorToHardRequirementRector

- .github/workflows/build.yaml
- .github/workflows/code_coverage.yaml
- .github/workflows/coding_standard.yaml
- .github/workflows/docs.yaml
- .github/workflows/phpstan.yaml
- .github/workflows/rector.yaml
- .github/workflows/tests.yaml
Last follow up to https://github.com/sabbelasichon/typo3-rector/pull/1962
Tip for automated weekly coverage: https://github.com/rectorphp/rector/blob/master/.github/workflows/weekly_code_coverage.yaml
<br>
Btw, what do you use coverage in practise? I'm thinking about it lately and I never work with the coverage number in any way :)
> [CI] Improve workflows

- templates/rector.php.dist
> [TASK] Use core skipping functionality in template

- config/services.php
> [TASK] Add correct phpstan neon file for TYPO3 context

- utils/generator/config/config.php
> [BUGFIX] Load config for utils correctly

- src/Rector/v9/v0/IgnoreValidationAnnotationRector.php
- src/Rector/v9/v0/MoveRenderArgumentsToInitializeArgumentsMethodRector.php
- src/Rector/v9/v0/ReplaceAnnotationRector.php
- src/Rector/v9/v5/RemoveInternalAnnotationRector.php
> [BUGFIX] Leverage the phpdoc cache

- composer.json
> [BUGFIX] Set strict version for rector

- config/nimut-testingframework/nimut-testing-framework-to-typo3-testing-framework.php
- config/solr/solr_php_client_to_solarium.php
- config/typo3-104-composer-packages.php
- config/typo3-110-composer-packages.php
- config/typo3-95-composer-packages.php
- config/underscore-to-namespace.php
- config/v10/typo3-100.php
- config/v10/typo3-101.php
- config/v10/typo3-103.php
- config/v10/typo3-104.php
- config/v7/tca-76.php
- config/v7/typo3-70.php
- config/v7/typo3-76.php
- config/v8/tca-87.php
- config/v8/typo3-80.php
- config/v8/typo3-84.php
- config/v8/typo3-85.php
- config/v8/typo3-86.php
- config/v8/typo3-87.php
- config/v9/typo3-90.php
- config/v9/typo3-92.php
- config/v9/typo3-93.php
- config/v9/typo3-95.php
> [BUGFIX] Use unique ids for configurable rectors

- utils/generator/src/Command/Typo3GenerateCommand.php
- utils/generator/src/Finder/TemplateFinder.php
- utils/generator/templates/tests/Rector/__Major__/__Minor__/__Test_Directory__/__Name__Test.php.inc
- utils/generator/templates/tests/Rector/__Major__/__Minor__/__Test_Directory__/config/configured_rule.php
> [TASK] Adjust generator command

- config/typo3-104-composer-packages.php
- config/typo3-95-composer-packages.php
- config/v8/typo3-86.php
- templates/rector.php.dist
> [BUGFIX] Add class Typo3Option to template

- .github/workflows/typo3-rector-check.yaml
- composer.json
- config/v8/typo3-85.php
- config/v8/typo3-86.php
- templates/rector.php
- templates/rector.php.dist
> [TASK] Add action to check if configs are valid

- config/v11/typo3-110.php
- src/Rector/v11/v0/RemoveLanguageModeMethodsFromTypo3QuerySettingsRector.php
- stubs/Extbase/Persistence/Generic/Typo3QuerySettings.php
- tests/Rector/v11/v0/RemoveLanguageModeMethodsFromTypo3QuerySettings/Fixture/remove_language_mode_methods.php.inc
- tests/Rector/v11/v0/RemoveLanguageModeMethodsFromTypo3QuerySettings/RemoveLanguageModeMethodsFromTypo3QuerySettingsRectorTest.php
- tests/Rector/v11/v0/RemoveLanguageModeMethodsFromTypo3QuerySettings/config/configured_rule.php
> [TASK] Remove language methods from Typo3QuerySettings

- bin/typo3-rector.php
- captainhook.json
- composer.json
- config/nimut-testingframework/nimut-testing-framework-to-typo3-testing-framework.php
- rector.php
- src/Bootstrap/Typo3RectorConfigsResolver.php
- src/Compiler/Composer/ComposerJsonManipulator.php
- src/Console/Application.php
- src/DependencyInjection/Typo3RectorContainerFactory.php
- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
- stubs/Nimut/TestingFramework/TestCase/ViewHelperBaseTestcase.php
- stubs/TestingFramework/Fluid/Unit/ViewHelpers/ViewHelperBaseTestcase.php
- tests/Rector/Extensions/solr/ApacheSolrDocumentToSolariumDocument/Fixture/fixture.php.inc
- tests/Rector/Nimut/TestingFramework/Fixture/functional_test_fixture.php.inc
- tests/Rector/Nimut/TestingFramework/Fixture/unit_test_fixture.php.inc
- tests/Rector/Nimut/TestingFramework/Fixture/viewhelper_test_fixture.php.inc
- tests/Rector/Nimut/TestingFramework/config/configured_rule.php
- tests/Rector/v11/v0/RemoveLanguageModeMethodsFromTypo3QuerySettings/RemoveLanguageModeMethodsFromTypo3QuerySettingsRectorTest.php
- tests/Rector/v8/v0/TimeTrackerInsteadOfNullTimeTracker/Fixture/new_null_time_tracker.php.inc
> [BUGFIX] Use new API of SetResolver

- .dockerignore
- .gitattributes
- README.md
- docs/ci.md
- docs/docker.md
- gitlab-template.yml
> [WIP] [TASK] Add Docker and CI documentation and templates

- src/Rector/v10/v0/ForceTemplateParsingInTsfeAndTemplateServiceRector.php
- stubs/Frontend/Authentication/FrontendUserAuthentication.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v10/v0/ForceTemplateParsingInTsfeAndTemplateServiceRector/Fixture/force_template_parsing_in_tsfe_and_template_service.php.inc
- tests/Rector/v10/v0/ForceTemplateParsingInTsfeAndTemplateServiceRector/ForceTemplateParsingInTsfeAndTemplateServiceRectorTest.php
- tests/Rector/v10/v0/ForceTemplateParsingInTsfeAndTemplateServiceRector/config/configured_rule.php
> [BUGFIX] Use correct parameter for call for isName

- stubs/Core/Tests/FunctionalTestCase.php
- tests/Rector/v8/v6/CoreTestsToTestingFramework/CoreTestsToTestingFramework.php
- tests/Rector/v8/v6/CoreTestsToTestingFramework/Fixture/functional_test_fixture.php.inc
- tests/Rector/v8/v6/CoreTestsToTestingFramework/Fixture/unit_test_fixture.php.inc
- tests/Rector/v8/v6/CoreTestsToTestingFramework/config/configured_rule.php
> [BUGFIX] Core tests to TestingFramework use classes

- src/Rector/v9/v3/ValidateAnnotationRector.php
- tests/Rector/v9/v3/ValidateAnnotation/Fixture/validate.php.inc
> [BUGFIX] Break comma separated validators into multiple annotations

- src/Console/Application.php
> [TASK] Read version dynamically

- src/Rector/v10/v1/RegisterPluginWithVendorNameRector.php
- tests/Rector/v10/v1/RegisterPluginWithVendorName/Fixture/register_plugin_with_vendor_name.php.inc
> [BUGFIX] Keep PascalCase in extensionName

- src/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModulesRector.php
- tests/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModules/Fixture/refactor_configure_plugin.php.inc
> [BUGFIX] No empty extensionKey in configurePlugin method

- composer.json
- src/Console/Command/ComposerCommand.php
- src/Rector/Composer/ExtensionComposerRector.php
- tests/Rector/Composer/ExtensionComposerRector/ExtensionComposerRectorTest.php
- tests/Rector/Composer/ExtensionComposerRector/Fixture/update_package.json
- tests/Rector/Composer/ExtensionComposerRector/config/configured_rule.php
> [TASK] Add command to fix composer.json

- docs/installation.md
This is the autoload.php for TYPO3 10 non composer installations.
> [TASK] add typo3 v10 example for autoload.php

- config/general/typo3.php
- config/v10/typo3-100.php
- src/Rector/Composer/ExtensionComposerRector.php
- src/Rector/General/ExtEmConfRector.php
- tests/Rector/General/ExtEmConf/ExtEmConfRectorTest.php
- tests/Rector/General/ExtEmConf/Fixture/different_configuration.php.inc
- tests/Rector/General/ExtEmConf/Fixture/ext_emconf_boolean.php.inc
- tests/Rector/General/ExtEmConf/Fixture/ext_emconf_messed.php.inc
- tests/Rector/General/ExtEmConf/config/configured_rule.php
> [TASK] Create rector to clean up ext_emconf.php

- src/Rector/v10/v0/ForceTemplateParsingInTsfeAndTemplateServiceRector.php
> [BUGFIX] Small refactoring and safety check

- config/v10/typo3-100.php
- src/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessageRector.php
- stubs/Core/Mail/MailMessage.php
- stubs/SwiftMailer/Swift_Attachment.php
- stubs/Symfony/Mime/AbstractPart.php
- tests/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessage/Fixture/mail_message.php.inc
- tests/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessage/Fixture/mail_message_add_part_text.php.inc
- tests/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessage/Fixture/mail_message_fluent.php.inc
- tests/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessage/Fixture/mail_message_set_body_html.php.inc
- tests/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessage/Fixture/mail_message_text.php.inc
- tests/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessage/SwiftMailerBasedMailMessageToMailerBasedMessageRectorTest.php
- tests/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessage/config/configured_rule.php
- utils/generator/templates/src/Rector/__Major__/__Minor__/__Name__.php
> [TASK] Change MailMessage api calls

- src/Rector/v9/v0/UseNewComponentIdForPageTreeRector.php
- tests/Rector/v9/v0/UseNewComponentIdForPageTree/Fixture/use_new_component_id_for_page_tree_skip_non_page_tree_values.php.inc
> [BUGFIX] Apply new navigation component id only to "typo3-pagetree"

- src/Rector/v8/v6/RefactorTCARector.php
- tests/Rector/v8/v6/RefactorTCA/Fixture/wizard_rte_old.php.inc
> [TASK] Refactor old TCA configuration for rte

- src/Rector/v9/v0/UseRenderingContextGetControllerContextRector.php
- tests/Rector/v9/v0/UseRenderingContextGetControllerContext/Fixture/use_rendering_context_get_controller_context.php.inc
> [BUGFIX] Do not remove controllerContext in custom classes

- config/v9/typo3-90.php
- src/Rector/Composer/RemoveCmsPackageDirFromExtraRector.php
- tests/Rector/Composer/RemoveCmsPackageDirFromExtraRector/Fixture/update_package_extra_defined.json
- tests/Rector/Composer/RemoveCmsPackageDirFromExtraRector/Fixture/update_package_no_extra.json
- tests/Rector/Composer/RemoveCmsPackageDirFromExtraRector/RemoveCmsPackageDirFromExtraRectorTest.php
- tests/Rector/Composer/RemoveCmsPackageDirFromExtraRector/config/configured_rule.php
> [TASK] Remove option cms-package-dir in extra

- config/v10/typo3-100.php
- stubs/Backend/Utility/BackendUtility.php
- stubs/RecordList/RecordList/DatabaseRecordList.php
- tests/Rector/v10/v0/DatabaseRecordList/DatabaseRecordListRector.php
- tests/Rector/v10/v0/DatabaseRecordList/Fixture/database_record_list_renaming.php.inc
- tests/Rector/v10/v0/DatabaseRecordList/config/configured_rule.php
> [TASK] Rename method calls DatabaseRecordList

- config/composer/typo3-104-composer-packages-core.php
- config/composer/typo3-95-composer-packages-core.php
- config/v10/typo3-100.php
- config/v8/typo3-80.php
- config/v8/typo3-86.php
- rector.php
- src/Helper/Typo3NodeResolver.php
- src/Rector/v8/v0/RenderCharsetDefaultsToUtf8Rector.php
- stubs/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v8/v0/RenderCharsetDefaultsToUtf8/Fixture/remove_render_charset_property_fetch.php.inc
- tests/Rector/v8/v0/RenderCharsetDefaultsToUtf8/RenderCharsetDefaultsToUtf8RectorTest.php
- tests/Rector/v8/v0/RenderCharsetDefaultsToUtf8/config/configured_rule.php
> [TASK] Substitute renderCharset with utf-8

- src/Rector/v7/v4/MoveLanguageFilesFromRemovedCmsExtensionRector.php
- tests/Rector/v7/v4/MoveLanguageFilesFromRemovedCmsExtension/Fixture/cms_language_files.php.inc
> [TASK] Replace locallang labels in a string

- config/v8/typo3-84.php
- src/Rector/v8/v4/ExtensionManagementUtilityExtRelPathRector.php
- stubs/Core/Utility/PathUtility.stub
- tests/Rector/v8/v4/ExtensionManagementUtilityExtRelPath/ExtensionManagementUtilityExtRelPathRectorTest.php
- tests/Rector/v8/v4/ExtensionManagementUtilityExtRelPath/Fixture/ext_rel_path.php.inc
- tests/Rector/v8/v4/ExtensionManagementUtilityExtRelPath/config/configured_rule.php
> [TASK] Substitute ExtensionManagementUtility::extRelPath()

- config/v9/typo3-90.php
- src/Rector/v9/v0/SubstituteGeneralUtilityDevLogRector.php
- stubs/Core/Log/LogLevel.stub
- stubs/Core/Utility/GeneralUtility.stub
- tests/Rector/v9/v0/SubstituteGeneralUtilityDevLog/Fixture/devlog_logging_api.php.inc
- tests/Rector/v9/v0/SubstituteGeneralUtilityDevLog/SubstituteGeneralUtilityDevLogRectorTest.php
- tests/Rector/v9/v0/SubstituteGeneralUtilityDevLog/config/configured_rule.php
> [TASK] Use Logging API instead of GeneralUtility::devLog()

- src/Console/Command/ComposerCommand.php
- src/Rector/Composer/ReplacePackageComposerRector.php
> [BUGFIX] Composer command respect command line paths

- composer.json
- src/Rector/Composer/ReplacePackageComposerRector.php
- src/Rector/Migrations/RenameClassMapAliasRector.php
- src/Rector/v11/v0/SubstituteConstantsModeAndRequestTypeRector.php
- src/Rector/v9/v3/ValidateAnnotationRector.php
- src/Renaming/NodeManipulator/ClassRenamer.php
- tests/Rector/Migrations/Fixture/fluid_core_classes_with_full_qualified_namespace.php.inc
- tests/Rector/Migrations/Fixture/fluid_core_classes_with_short_namespace.php.inc
- tests/Rector/Migrations/config/configured_rule.php
> [BUGFIX] Use custom ClassRenamer

- src/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessageRector.php
- stubs/Core/Mail/MailMessage.stub
- stubs/SwiftMailer/Swift_Image.stub
- tests/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessage/Fixture/mail_message.php.inc
> [TASK] Refactor embed method for MailMessage

- config/v9/typo3-90.php
- src/Helper/OldSeverityToLogLevelMapper.php
- src/Rector/v9/v0/ReplacedGeneralUtilitySysLogWithLogginApiRector.php
- stubs/Core/Utility/GeneralUtility.stub
- tests/Rector/v9/v0/ReplacedGeneralUtilitySysLogWithLogginApi/Fixture/sys_log_logging_api.php.inc
- tests/Rector/v9/v0/ReplacedGeneralUtilitySysLogWithLogginApi/ReplacedGeneralUtilitySysLogWithLogginApiRectorTest.php
- tests/Rector/v9/v0/ReplacedGeneralUtilitySysLogWithLogginApi/config/configured_rule.php
> [TASK] Replaced GeneralUtility::sysLog with Logging API

- scoper.php
- src/Helper/Strings.php
- src/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModulesRector.php
- src/Rector/v10/v1/RegisterPluginWithVendorNameRector.php
> [TASK] Add dedicated Strings class

- tests/Rector/v9/v0/IgnoreValidation/IgnoreValidationAnnotationRectorTest.php
- tests/Rector/v9/v0/InjectAnnotation/InjectAnnotationRectorTest.php
- tests/Rector/v9/v0/MoveRenderArgumentsToInitializeArgumentsMethod/MoveRenderArgumentsToInitializeArgumentsMethodRectorTest.php
- tests/Rector/v9/v0/ReplaceAnnotation/ReplaceAnnotationRectorTest.php
- tests/Rector/v9/v3/ValidateAnnotation/ValidateAnnotationRectorTest.php
> [TASK] Do not test PHP 8.0 temporarily

- config/v9/typo3-94.php
- src/Rector/v9/v4/RemoveMethodsFromEidUtilityAndTsfeRector.php
- stubs/Frontend/Controller/TypoScriptFrontendController.stub
- stubs/Frontend/Utility/EidUtility.stub
- tests/Rector/v9/v4/RemoveMethodsFromEidUtilityAndTsfe/Fixture/eid_utility_methods.php.inc
- tests/Rector/v9/v4/RemoveMethodsFromEidUtilityAndTsfe/Fixture/tsfe_methods.php.inc
- tests/Rector/v9/v4/RemoveMethodsFromEidUtilityAndTsfe/RemoveMethodsFromEidUtilityAndTsfeRectorTest.php
- tests/Rector/v9/v4/RemoveMethodsFromEidUtilityAndTsfe/config/configured_rule.php
> [TASK] Remove old EidUtility and various TSFE methods

- src/Rector/v8/v6/RemoveL10nModeNoCopyRector.php
- tests/Rector/v8/v6/RemoveL10nModeNoCopy/Fixture/remove_l10n_mode_no_copy.php.inc
- tests/bootstrap.php
> [BUGFIX] Do not add duplicated config key

- config/v9/typo3-95.php
- src/Helper/TcaHelperTrait.php
- src/Rector/v9/v5/RefactorTypeInternalTypeFileAndFileReferenceToFalRector.php
- tests/Rector/v9/v5/RefactorTypeInternalTypeFileAndFileReferenceToFal/Fixture/internal_type_file.php.inc
- tests/Rector/v9/v5/RefactorTypeInternalTypeFileAndFileReferenceToFal/RefactorTypeInternalTypeFileAndFileReferenceToFalRectorTest.php
- tests/Rector/v9/v5/RefactorTypeInternalTypeFileAndFileReferenceToFal/config/configured_rule.php
> [TASK] Refactor TCA type group internal_type file and file_reference

- config/v8/tca-87.php
- config/v8/typo3-86.php
- config/v9/tca-95.php
- config/v9/typo3-95.php
> [BUGFIX] Move TCA related rectors to correct configuration file

- config/services.php
- src/Console/Command/Typo3ProcessCommand.php
- src/TypoScript/Visitors/OldConditionToExpressionLanguageVisitor.php
> [TASK] Add ProgressBar for typo3-process command

- config/services.php
- config/v8/typo3-83.php
- rector.php
- src/Console/Command/Typo3ProcessCommand.php
- src/Resources/Icons/IconsProcessor.php
> [TASK] Move ext_icon.* to Resources/Public/Icons

- config/v9/typo3-93.php
- src/TypoScript/Conditions/HostnameConditionMatcher.php
- tests/TypoScript/Visitors/OldConditionToExpressionLanguageVisitorTest.php
- tests/TypoScript/config/configured_rule.php
Add [hotsname] to typoscript convertion
> [TASK] Add HostnameConditionMatcher

- src/FlexForms/FlexFormsProcessor.php
- src/FlexForms/Transformer/FlexFormTransformer.php
- src/FlexForms/Transformer/RenderTypeTransformer.php
- tests/FlexForms/Fixture/flexforms.xml
- tests/FlexForms/FlexFormsProcessorTest.php
- tests/FlexForms/config/configured_rule.php
> [TASK] Add FlexFormProcessor

- composer.json
Fixes failing master https://github.com/sabbelasichon/typo3-rector/runs/2305288042
> composer: add package required for docs generator

- config/v9/typo3-90.php
- src/TypoScript/Visitors/FileIncludeToImportStatementVisitor.php
- tests/TypoScript/Fixture/include_dir.typoscript
- tests/TypoScript/Fixture/include_file.typoscript
- tests/TypoScript/Fixture/include_file_with_condition.typoscript
- tests/TypoScript/config/configured_rule.php
> [TASK] Transform old include statement for files to @import

- composer.json
- config/config.php
- src/Composer/ExtensionComposerProcessor.php
- src/Configuration/Typo3Option.php
- src/FlexForms/FlexFormsProcessor.php
- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
- src/Processor/ConfigurableProcessorInterface.php
- src/Rector/v10/v2/InjectEnvironmentServiceIfNeededInResponseRector.php
- src/Rector/v9/v5/RefactorTypeInternalTypeFileAndFileReferenceToFalRector.php
- src/Reporting/HtmlReporter.php
- src/Reporting/NullReporter.php
- src/Reporting/Reporter.php
- src/Reporting/ReporterFactory.php
- src/Reporting/ValueObject/Report.php
- src/Resources/Icons/IconsProcessor.php
- src/Yaml/Form/FormYamlProcessor.php
- templates/report/index.html
- templates/report/main.css
- tests/Rector/Composer/RemoveCmsPackageDirFromExtraRector/RemoveCmsPackageDirFromExtraRectorTest.php
- tests/Rector/Composer/ReplacePackageComposerRector/ReplacePackageComposerRectorTest.php
> [TASK] Add basic Reporter

- src/Helper/FileHelperTrait.php
- src/Rector/v9/v0/ReplaceExtKeyWithExtensionKeyRector.php
- stubs/Core/Utility/ExtensionManagementUtility.php
- tests/Rector/v9/v0/ReplaceExtKeyWithExtensionKey/Fixture/sys_template.php.inc
> [FEATURE] Enable EXTKEY to be replaced in sys_template

- src/Rector/v10/v0/RemovePropertyExtensionNameRector.php
> [TASK] Migrate usage of property extensionName in ActionContr. aswell

- src/Composer/ExtensionComposerProcessor.php
- src/FlexForms/FlexFormsProcessor.php
- src/Resources/Icons/IconsProcessor.php
- src/TypoScript/TypoScriptProcessor.php
- src/Yaml/Form/FormYamlProcessor.php
- tests/Application/ApplicationFileProcessor/AbstractApplicationFileProcessorTest.php
- tests/FlexForms/Fixture/flexforms_no_change.xml
- tests/FlexForms/FlexFormsProcessorTest.php
- tests/Rector/Composer/RemoveCmsPackageDirFromExtraRector/Fixture/update_package_extra_defined.json
- tests/TypoScript/Fixture/conditions.typoscript
- tests/TypoScript/Fixture/include_file.typoscript
- tests/TypoScript/TypoScriptProcessorTest.php
- tests/Yaml/Form/Fixture/my_form.form.yaml
- tests/Yaml/Form/FormYamlProcessorTest.php
> [TASK] Refactor ApplicationFileProcessors api

- src/TypoScript/Conditions/AbstractRootlineConditionMatcher.php
- src/TypoScript/Conditions/ApplicationContextConditionMatcher.php
- src/TypoScript/Conditions/GlobalStringConditionMatcher.php
- src/TypoScript/Conditions/HostnameConditionMatcher.php
- src/TypoScript/Conditions/IPConditionMatcher.php
- src/TypoScript/Conditions/TreeLevelConditionMatcher.php
- src/TypoScript/Visitors/OldConditionToExpressionLanguageVisitor.php
In some cases like hostname etc. it is not reliable to fix conditions with constants
Resolves: #2131
> [TASK] Prevent condition transformation if contains constant

- src/Rector/v9/v0/UseExtensionConfigurationApiRector.php
- tests/Rector/v9/v0/UseExtensionConfigurationApi/Fixture/use_extension_configuration_api.php.inc
- tests/Rector/v9/v0/UseExtensionConfigurationApi/Fixture/use_extension_configuration_api_in_class_context.php.inc
> [BUGFIX] UseExtensionConfigurationApiRector works with variable

- src/Composer/ExtensionComposerProcessor.php
- src/Rector/Composer/ExtensionComposerRector.php
- src/TypoScript/TypoScriptProcessor.php
- src/TypoScript/Visitors/FileIncludeToImportStatementVisitor.php
- src/TypoScript/Visitors/OldConditionToExpressionLanguageVisitor.php
- src/Yaml/Form/FormYamlProcessor.php
- src/Yaml/Form/Transformer/EmailFinisherTransformer.php
- tests/TypoScript/Visitors/OldConditionToExpressionLanguageVisitorTest.php
> [TASK] Add changelogs for non php processors

- config/v10/typo3-100.php
- stubs/TYPO3/CMS/Core/Resource/FileInterface.php
- stubs/TYPO3/CMS/Core/Resource/ProcessedFile.php
- stubs/TYPO3/CMS/Extbase/Configuration/ConfigurationManager.php
- stubs/TYPO3/CMS/Extbase/DomainObject/DomainObjectInterface.php
- stubs/TYPO3/CMS/Extbase/Error/Message.php
- stubs/TYPO3/CMS/Extbase/Property/TypeConverterInterface.php
- stubs/TYPO3/CMS/Extbase/Service/ImageService.php
- tests/TypoScript/TypoScriptProcessorTest.php
> [TASK] Add type declarations for extbase classes

- src/Resources/Icons/IconsProcessor.php
> [TASK] Correct message of ext icon processing

- config/experimental.php
- config/nimut-testingframework/nimut-testing-framework-to-typo3-testing-framework.php
- config/solr/solr_php_client_to_solarium.php
- config/v10/typo3-100.php
- config/v10/typo3-101.php
- config/v10/typo3-103.php
- config/v10/typo3-104.php
- config/v7/typo3-70.php
- config/v7/typo3-76.php
- config/v8/typo3-80.php
- config/v8/typo3-84.php
- config/v8/typo3-85.php
- config/v8/typo3-86.php
- config/v8/typo3-87.php
- config/v9/typo3-90.php
- config/v9/typo3-92.php
- config/v9/typo3-93.php
- src/Rector/v10/v2/UseActionControllerRector.php
> [TASK] Remove ::class for 3rd party classes

- composer.json
- config/v10/typo3-103.php
- config/v10/typoscript-conditions-104.php
- config/v9/typo3-93.php
- config/v9/typoscript-conditions-95.php
- src/Set/Typo3SetList.php
> [TASK] Add dedicated TypoScript conditions set

- phpstan-baseline.neon
- src/EditorConfig/EditorConfigIdiosyncraticParser.php
- src/TypoScript/TypoScriptProcessor.php
- src/ValueObject/EditorConfigConfiguration.php
- tests/TypoScript/TypoScriptProcessorTest.php
> [BUGFIX] Do not add linebreaks multiple times

- bin/rector.php
- build-typo3-rector-scoped.sh
- src/Template/TemplateResolver.php
> [BUGFIX] Include typo3 config in bootstrap file

- composer.json
- phpstan.neon
- src/TypoScript/ConvertToPhpFileInterface.php
- src/TypoScript/TypoScriptProcessor.php
- src/TypoScript/Visitors/ExtbasePersistenceVisitor.php
- src/TypoScript/Visitors/OldConditionToExpressionLanguageVisitor.php
- src/ValueObject/TypoScriptToPhpFile.php
- tests/TypoScript/Fixture/extbase_persistence.typoscript
- tests/TypoScript/Fixture/foo_persistence.typoscript
- tests/TypoScript/TypoScriptProcessorTest.php
- tests/TypoScript/config/configured_rule.php
- utils/composer-packages/src/Command/AddComposerTypo3ExtensionsToConfigCommand.php
> [TASK] Convert extbase persistence

- config/config.php
- src/Rector/v9/v5/RefactorTypeInternalTypeFileAndFileReferenceToFalRector.php
- src/Reporting/ReporterFactory.php
- src/TypoScript/TypoScriptProcessor.php
- templates/rector.php.dist
> [TASK] Document reports option

- src/Rector/v9/v0/UseExtensionConfigurationApiRector.php
- tests/Rector/v9/v0/UseExtensionConfigurationApiRector/Fixture/use_extension_configuration_api.php.inc
> [BUGFIX] Do not change extension configuration

- src/Rector/v8/v6/RefactorTCARector.php
- tests/Rector/v8/v6/RefactorTCARector/Fixture/wizard_select.php.inc
- tests/Rector/v8/v6/RefactorTCARector/Fixture/wizard_suggest.php.inc
> [BUGFIX] Avoid duplicated suggestOptions

- src/TypoScript/TypoScriptProcessor.php
- src/TypoScript/Visitors/AbstractVisitor.php
- src/TypoScript/Visitors/ExtbasePersistenceVisitor.php
- src/TypoScript/Visitors/FileIncludeToImportStatementVisitor.php
- src/TypoScript/Visitors/OldConditionToExpressionLanguageVisitor.php
> [BUGFIX] Do not change TypoScript file if nothing has changed

- config/v10/typo3-101.php
- src/Rector/v10/v0/UseTwoLetterIsoCodeFromSiteLanguageRector.php
- src/Rector/v9/v0/ReplacedGeneralUtilitySysLogWithLogginApiRector.php
- src/TypoScript/Conditions/AbstractGlobalConditionMatcher.php
- tests/TypoScript/Visitors/OldConditionToExpressionLanguageVisitorTest.php
> [BUGFIX] Map IENV:TYPO3_HOST_ONLY to new condition

- phpstan.neon
- src/FlexForms/FlexFormsProcessor.php
- tests/FlexForms/Fixture/sitemap.xml
- tests/FlexForms/FlexFormsProcessorTest.php
> [BUGFIX] Catch loading error for xml

- composer.json
> [BUGFIX] Do not add composer package command

- README.md
- docs/best_practice_guide.md
This is only the first step to lead new DEVs and give some hints about upgrades
> [DOCU] Provide best practice guide for upgrades

- docs/beyond_php_file_processors.md
> [DOCU] Provide docs for special processors

- src/Resources/Icons/IconsProcessor.php
> [TASK] Copy extension icon instead of rename

- rector.php
- src/Composer/InitializeExtensionComposerJsonProcessor.php
- tests/Composer/InitializeExtensionComposerJsonProcessor/Fixture/ext_emconf.php
> [TASK] Add autoload, require etc to composer.json

- config/v10/typo3-100.php
> [BUGFIX] Add correct return type declaration

- scoped/composer.json
- src/Helper/TcaHelperTrait.php
- src/Rector/v8/v6/AddTypeToColumnConfigRector.php
- tests/Rector/v8/v6/AddTypeToColumnConfigRector/Fixture/add_type_to_column_config.php.inc
> [BUGFIX] Do not add config twice

- src/Rector/v8/v6/MigrateSelectShowIconTableRector.php
- tests/Rector/v8/v6/MigrateSelectShowIconTableRector/Fixture/migrate_select_show_icon_table.php.inc
> [BUGFIX] Check if fieldWizard already exists

- src/Rector/v8/v6/RefactorTCARector.php
- src/Yaml/Form/FormYamlProcessor.php
- tests/Rector/v8/v6/RefactorTCARector/Fixture/wizard_colorpicker.php.inc
- tests/Rector/v8/v6/RefactorTCARector/Fixture/wizard_link.php.inc
- tests/Rector/v8/v6/RefactorTCARector/Fixture/wizard_rte_old.php.inc
- tests/Rector/v8/v6/RefactorTCARector/Fixture/wizard_select.php.inc
- tests/Rector/v8/v6/RefactorTCARector/Fixture/wizard_slider.php.inc
- tests/Rector/v8/v6/RefactorTCARector/Fixture/wizard_table.php.inc
> [TASK] Do not duplicate configuration

- composer.json
- config/config.php
- phpstan.neon
- rector.php
It would cause trouble like these 
https://github.com/rectorphp/rector-src/pull/46/checks?check_run_id=2592322406#step:5:15
> [WIP] config: remove local phpstan config reference

- src/Rector/v9/v0/MoveRenderArgumentsToInitializeArgumentsMethodRector.php
> [TASK] Add additional ObjectTypes

- src/Helper/StringUtility.php
> [TASK] Use Stringy

- config/v8/tca-87.php
> [TASK] Remove AddTypeToColumnConfigRector from set

- src/Rector/v9/v3/ValidateAnnotationRector.php
- tests/Rector/v9/v3/ValidateAnnotationRector/Fixture/validate.php.inc
> [BUGFIX] Format validate annotations correctly

- docs/best_practice_guide.md
- docs/beyond_php_file_processors.md
> [DOCU] Add tldr section, extend composer ruleset info

- src/Rector/v9/v5/ExtbaseCommandControllerToSymfonyCommandRector.php
- src/Template/TemplateFinder.php
- src/TypoScript/Visitors/ExtbasePersistenceVisitor.php
> [TASK] Add TemplateFinder class

- src/FileProcessor/TypoScript/Conditions/AdminUserConditionMatcher.php
- tests/FileProcessor/TypoScript/Visitors/OldConditionToExpressionLanguageVisitorTest.php
> [TASK] Add new condition transformation adminUser

- docs/configuration_and_processing.md
- templates/rector.php.dist
> [DOCS] Add non-php fileprocessors to template and docs

- src/FileProcessor/TypoScript/Conditions/AbstractGlobalConditionMatcher.php
- src/FileProcessor/TypoScript/Conditions/GlobalVarConditionMatcher.php
- tests/FileProcessor/TypoScript/Visitors/OldConditionToExpressionLanguageVisitorTest.php
> [BUGFIX] Fix condition for BE_USER

- README.md
- docs/installation.md
> [TASK] Suggest to install rector/rector

- src/FileProcessor/TypoScript/Conditions/ApplicationContextConditionMatcher.php
- tests/FileProcessor/TypoScript/Visitors/OldConditionToExpressionLanguageVisitorTest.php
> [BUGFIX] Add missing quotes to ApplicationContextConditionMatcher

- config/v10/typo3-100.php
- src/FileProcessor/Yaml/Form/FormYamlProcessor.php
- src/FileProcessor/Yaml/Form/Rector/TranslationFileRector.php
- tests/FileProcessor/Yaml/Form/Fixture/form_setup.yaml
- tests/FileProcessor/Yaml/Form/FormYamlProcessorTest.php
- tests/FileProcessor/Yaml/Form/config/configured_rule.php
> [TASK] Rename translationFile to translationFiles

- config/v9/typo3-94.php
- src/Rector/v9/v4/AdditionalFieldProviderRector.php
- stubs/TYPO3/CMS/Scheduler/AbstractAdditionalFieldProvider.php
- stubs/TYPO3/CMS/Scheduler/AdditionalFieldProviderInterface.php
- stubs/TYPO3/CMS/Scheduler/Controller/SchedulerModuleController.php
- tests/Rector/v9/v4/AdditionalFieldProviderRector/AdditionalFieldProviderRectorTest.php
- tests/Rector/v9/v4/AdditionalFieldProviderRector/Fixture/fixture.php.inc
- tests/Rector/v9/v4/AdditionalFieldProviderRector/config/configured_rule.php
> [TASK] Refactor AdditionalFieldProvider

- src/FileProcessor/TypoScript/Visitors/ExtbasePersistenceVisitor.php
- tests/FileProcessor/TypoScript/Expected/Extbase.php.inc
> [BUGFIX] Use correct key for fieldNames

- templates/rector.php.dist
- Sort namespace imports alphabetically
- Sort skip files alphabetically
- Add additional skip files
> [TASK] Optimize rector dist file

- src/FileProcessor/TypoScript/Visitors/ExtbasePersistenceVisitor.php
- tests/FileProcessor/TypoScript/Expected/Extbase.php.inc
> [TASK] Add ::class notation for ExtbasePersistenceVisitor

- .github/workflows/coding_standard.yaml
- .github/workflows/docs.yaml
- .github/workflows/phpstan.yaml
- .github/workflows/rector.yaml
- .github/workflows/tests.yaml
- .github/workflows/typo3-rector-check.yaml
- composer.json
- phpstan.neon
- rector.php
- src/FileProcessor/Resources/Icons/IconsProcessor.php
- src/FileProcessor/Resources/Icons/Rector/IconsRector.php
- src/FileProcessor/TypoScript/Visitors/ExtbasePersistenceVisitor.php
- src/NodeFactory/ImportExtbaseAnnotationIfMissingFactory.php
- src/Rector/v9/v5/ExtbaseCommandControllerToSymfonyCommandRector.php
- tests/FileProcessor/Resources/Icons/IconsProcessor/config/configured_rule.php
- tests/Rector/v8/v5/ContentObjectRendererFileResourceRector/ContentObjectRendererFileResourceRectorTest.php
- tests/Rector/v9/v4/UseGetMenuInsteadOfGetFirstWebPageRector/UseGetMenuInsteadOfGetFirstWebPageRectorTest.php
- tests/Rector/v9/v5/ExtbaseCommandControllerToSymfonyCommandRector/ExtbaseCommandControllerToSymfonyCommandRectorTest.php
- Use ParameterProvider instead of Configuration object
Resolves: #2469
> [BUGFIX] Move away from configuration injection

- src/Rector/v8/v0/TimeTrackerInsteadOfNullTimeTrackerRector.php
- tests/Rector/v8/v0/TimeTrackerInsteadOfNullTimeTrackerRector/Fixture/new_null_time_tracker.php.inc
> [TASK] Add failing test

- src/Rector/Migrations/RenameClassMapAliasRector.php
- templates/rector.php.dist
- tests/Rector/Migrations/Fixture/stringified_classes.php.inc
- tests/Rector/Migrations/config/configured_rule.php
> [TASK] Change old class names even if defined in string

- .gitignore
- config/config.php
- config/v8/typo3-80.php
- src/FileProcessor/TypoScript/TypoScriptProcessor.php
- src/FileProcessor/TypoScript/Visitors/AbstractVisitor.php
- src/FileProcessor/TypoScript/Visitors/AdditionalHeadersToArrayVisitor.php
- tests/FileProcessor/TypoScript/Fixture/TypoScript/config.typoscript
- tests/FileProcessor/TypoScript/config/configured_rule.php
> [TASK] Change statement for additionalHeaders

- src/FileProcessor/TypoScript/Visitors/AdditionalHeadersToArrayVisitor.php
- src/Rector/v9/v4/UseContextApiRector.php
- tests/FileProcessor/TypoScript/config/configured_rule.php
- tests/Rector/v9/v4/UseContextApiRector/Fixture/dont_use_context_api_in_write_context.php.inc
> [BUGFIX] Do not use aspects in write context

- config/v9/typo3-90.php
- src/Rector/v9/v0/QueryLogicalOrAndLogicalAndToArrayParameterRector.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/Query.php
- stubs/TYPO3/CMS/Extbase/Persistence/Query.php
- stubs/TYPO3/CMS/Extbase/Persistence/QueryInterface.php
- stubs/TYPO3/CMS/Extbase/Persistence/QueryResultInterface.php
- stubs/TYPO3/CMS/Extbase/Persistence/Repository.php
- tests/Rector/v9/v0/QueryLogicalOrAndLogicalAndToArrayParameterRector/Fixture/query_logical_and.php.inc
- tests/Rector/v9/v0/QueryLogicalOrAndLogicalAndToArrayParameterRector/Fixture/query_logical_and_with_array.php.inc
- tests/Rector/v9/v0/QueryLogicalOrAndLogicalAndToArrayParameterRector/Fixture/query_logical_and_with_array_but_additional_parameter.php.inc
- tests/Rector/v9/v0/QueryLogicalOrAndLogicalAndToArrayParameterRector/Fixture/query_logical_or.php.inc
- tests/Rector/v9/v0/QueryLogicalOrAndLogicalAndToArrayParameterRector/QueryLogicalOrAndLogicalAndToArrayParameterRectorTest.php
- tests/Rector/v9/v0/QueryLogicalOrAndLogicalAndToArrayParameterRector/config/configured_rule.php
> [TASK] Use array for logicalAnd and logicalOr query calls

- .github/workflows/rector.yaml
> [TASK] Rector fix automatically

- composer.json
- phpstan-baseline.neon
- src/FileProcessor/TypoScript/TypoScriptProcessor.php
> [TASK] Change ts parse error message to warning, add file path

- src/Rector/Migrations/RenameClassMapAliasRector.php
- tests/Rector/Migrations/Fixture/stringified_classes.php.inc
> [BUGFIX] Skip language string class

- config/config.php
- config/v8/typo3-80.php
- config/v9/typoscript-conditions-95.php
- docs/all_rectors_overview.md
- docs/beyond_php_file_processors.md
- phpstan-baseline.neon
- src/Contract/FileProcessor/TypoScript/TypoScriptRectorInterface.php
- src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php
- src/FileProcessor/TypoScript/Rector/AdditionalHeadersToArrayTypoScriptRector.php
- src/FileProcessor/TypoScript/Rector/ExtbasePersistenceTypoScriptRector.php
- src/FileProcessor/TypoScript/Rector/FileIncludeToImportStatementTypoScriptRector.php
- src/FileProcessor/TypoScript/Rector/OldConditionToExpressionLanguageTypoScriptRector.php
- src/FileProcessor/TypoScript/TypoScriptProcessor.php
- tests/FileProcessor/TypoScript/Rector/OldConditionToExpressionLanguageRectorTest.php
- tests/FileProcessor/TypoScript/config/configured_rule.php
> [TASK] Add dedicated TypoScriptRectorInterface

- src/Rector/v10/v2/InjectEnvironmentServiceIfNeededInResponseRector.php
@sabbelasichon I think this can be solution for error https://github.com/rectorphp/rector-src/pull/338/checks?check_run_id=2949192987#step:5:24 
ref https://github.com/rectorphp/rector-src/pull/338#pullrequestreview-695721105
what do you think?
> Fix ClassInsertManipulator::addAsFirstMethod() cannot pass Nop instance

- docs/configuration_and_processing.md
- templates/rector.php.dist
> [DOCS] Synch config docs with template, rename typoscript visitor

- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
Related to Enum upgrade in TypeKind - https://github.com/rectorphp/rector-src/pull/373
Ready to merge :heavy_check_mark:
> use ENUM in TypeKind

- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
- tests/Rector/v9/v0/MoveRenderArgumentsToInitializeArgumentsMethodRector/Fixture/my_viewhelper_with_default_null.php.inc
> [BUGFIX] Do not add null as string

- src/Rector/v8/v0/RenderCharsetDefaultsToUtf8Rector.php
- tests/Rector/v8/v0/RenderCharsetDefaultsToUtf8Rector/Fixture/remove_render_charset_property_fetch.php.inc
> [BUGFIX] Do not change assignment for renderCharset

- src/Rector/v9/v0/ReplaceExtKeyWithExtensionKeyRector.php
- tests/Rector/v9/v0/ReplaceExtKeyWithExtensionKeyRector/Fixture/my_extension/Configuration/TCA/Overrides/sys_template.php.inc
- tests/Rector/v9/v0/ReplaceExtKeyWithExtensionKeyRector/Fixture/my_extension/ext_localconf.php.inc
- tests/Rector/v9/v0/ReplaceExtKeyWithExtensionKeyRector/Fixture/my_extension/ext_tables.php.inc
> [BUGFIX] Do not change  on left side

- composer.json
- src/FileProcessor/TypoScript/Rector/OldConditionToExpressionLanguageTypoScriptRector.php
News https://github.com/nikic/PHP-Parser/releases/tag/v4.11.0
Attempt to fix https://github.com/rectorphp/rector-src/pull/410#issuecomment-877346778
> Bump deps to nikic/php-parser 4.11

- src/FileProcessor/TypoScript/Conditions/AbstractGlobalConditionMatcher.php
- tests/FileProcessor/TypoScript/Rector/OldConditionToExpressionLanguageRectorTest.php
> [TASK] Add IENV:HTTPS to condition matcher

- src/Rector/v9/v3/ValidateAnnotationRector.php
- tests/Rector/v9/v3/ValidateAnnotationRector/Fixture/validate_property.php.inc
> Use correct look behind pattern for validator option

- config/v8/typo3-81.php
Fix missing registration for GeneralUtilityToUpperAndLowerRector and RefactorVariousGeneralUtilityMethodsRector in v8\v1
> Fix missing registrations for v8\v1

- src/FileProcessor/Fluid/Rector/DefaultSwitchFluidRector.php
> Fix multiline content for f:case default

- src/Contract/FileProcessor/TypoScript/TypoScriptRectorInterface.php
- src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php
> Extend Visitor explicitly

- docs/best_practice_guide.md
> Feature: Document class alias map

- src/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php
- src/Rector/v9/v4/RemoveInitTemplateMethodCallRector.php
- src/Rector/v9/v5/RemoveInitMethodFromPageRepositoryRector.php
- tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector/Fixture/extbase_controller_actions_return_response_interface.php.inc
> Fix jsonResponse

- src/FileProcessor/Yaml/Form/Rector/EmailFinisherRector.php
- tests/FileProcessor/Yaml/Form/Fixture/my_form.form.yaml
> [BUGFIX] Refactor finisher variants

- src/FileProcessor/Resources/Icons/IconsFileProcessor.php
> [TASK] Narrow down ext_icon migration to whole file name

- src/FileProcessor/TypoScript/Conditions/GlobalVarConditionMatcher.php
- tests/FileProcessor/TypoScript/Rector/OldConditionToExpressionLanguageRectorTest.php
> [BUGFIX] Add more globalVar transformations

- config/v11/typo3-110.php
- tests/Rector/v11/v0/UsePhpNativeStringFunctionsRector/Fixture/skip_methods.php.inc
- tests/Rector/v11/v0/UsePhpNativeStringFunctionsRector/Fixture/substitute_utility_methods.php.inc
- tests/Rector/v11/v0/UsePhpNativeStringFunctionsRector/Source/MyCustomStringUtility.php
- tests/Rector/v11/v0/UsePhpNativeStringFunctionsRector/UsePhpNativeStringFunctionsRectorTest.php
- tests/Rector/v11/v0/UsePhpNativeStringFunctionsRector/config/configured_rule.php
> [TASK] Use php native string functions

- docs/contribution.md
> [DOCS] Provide more specific docs and help to create own rector

- config/v11/typo3-114.php
- src/Rector/v11/v4/UseNativeFunctionInsteadOfGeneralUtilityShortMd5Rector.php
- stubs/TYPO3/CMS/Core/Utility/GeneralUtility.php
- tests/Rector/v11/v4/UseNativeFunctionInsteadOfGeneralUtilityShortMd5Rector/Fixture/substitute_short_md5.php.inc
- tests/Rector/v11/v4/UseNativeFunctionInsteadOfGeneralUtilityShortMd5Rector/UseNativeFunctionInsteadOfGeneralUtilityShortMd5RectorTest.php
- tests/Rector/v11/v4/UseNativeFunctionInsteadOfGeneralUtilityShortMd5Rector/config/configured_rule.php
> [TASK] Use native php functions

- phpstan.neon
I've noticed the CI is failing here because of php-parser and mine changes, let's make it green again :)
> [phpstan] fix phpstan errors caused by new php-parser and symplify releases

- config/v11/typo3-113.php
- src/Rector/v11/v3/SubstituteMethodRmFromListOfGeneralUtilityRector.php
- tests/Rector/v11/v3/SubstituteMethodRmFromListOfGeneralUtilityRector/Fixture/remove_from_list_to_array_filter.php.inc
- tests/Rector/v11/v3/SubstituteMethodRmFromListOfGeneralUtilityRector/SubstituteMethodRmFromListOfGeneralUtilityRectorTest.php
- tests/Rector/v11/v3/SubstituteMethodRmFromListOfGeneralUtilityRector/config/configured_rule.php
> [TASK] Substitute GeneralUtility::rmFromList

- config/v10/typo3-104.php
- ecs.php
- src/Rector/v10/v4/UseIconsFromSubFolderInIconRegistryRector.php
- src/Rector/v11/v3/SubstituteMethodRmFromListOfGeneralUtilityRector.php
- src/Rector/v11/v4/MigrateFileFolderConfigurationRector.php
- tests/Rector/v10/v4/UseIconsFromSubFolderInIconRegistryRector/Fixture/move_icons_to_subfolder.php.inc
- tests/Rector/v10/v4/UseIconsFromSubFolderInIconRegistryRector/Fixture/skip_register_icon.php.inc
- tests/Rector/v10/v4/UseIconsFromSubFolderInIconRegistryRector/UseIconsFromSubFolderInIconRegistryRectorTest.php
- tests/Rector/v10/v4/UseIconsFromSubFolderInIconRegistryRector/config/configured_rule.php
> [TASK] Use icons from subfolder

- config/v11/typo3-110.php
> Fix Deprecation: GeneralUtility::isAbsPath()

- config/v11/typo3-110.php
- config/v11/typo3-114.php
- config/v11/typo3-115.php
- tests/Rector/v11/v5/GeneralUtilityIsAbsPathRector/Fixture/fixture.php.inc
- tests/Rector/v11/v5/GeneralUtilityIsAbsPathRector/GeneralUtilityIsAbsPathRectorTest.php
- tests/Rector/v11/v5/GeneralUtilityIsAbsPathRector/config/configured_rule.php
> [FEATURE] Rename GeneralUtility::isAbsPath to PathUtility::isAbsolutePath

- config/v10/typo3-101.php
- src/Rector/v10/v1/RemoveEnableMultiSelectFilterTextfieldRector.php
- tests/Rector/v10/v1/RemoveEnableMultiSelectFilterTextfieldRector/Fixture/fixture.php.inc
- tests/Rector/v10/v1/RemoveEnableMultiSelectFilterTextfieldRector/Fixture/fixture_no_change.php.inc
- tests/Rector/v10/v1/RemoveEnableMultiSelectFilterTextfieldRector/RemoveEnableMultiSelectFilterTextfieldRectorTest.php
- tests/Rector/v10/v1/RemoveEnableMultiSelectFilterTextfieldRector/config/configured_rule.php
- utils/phpstan/src/Rules/AddCodeCoverageIgnoreForRectorDefinition.php
> [FEAT] Remove deprecated "enableMultiSelectFilterTextfield"

- src/Rector/v11/v2/MigrateFrameModuleToSvgTreeRector.php
- stubs/TYPO3/CMS/Core/Utility/ExtensionManagementUtility.php
- tests/Rector/v11/v2/MigrateFrameModuleToSvgTreeRector/Fixture/ext_tables.php.inc
- tests/Rector/v11/v2/MigrateFrameModuleToSvgTreeRector/MigrateFrameModuleToSvgTreeRectorTest.php
- tests/Rector/v11/v2/MigrateFrameModuleToSvgTreeRector/config/configured_rule.php
- utils/phpstan/src/Rules/AddCodeCoverageIgnoreForRectorDefinition.php
> [FEAT] Migrate iframe navigationFrameModule

- src/Rector/v11/v3/SwitchBehaviorOfArrayUtilityMethodsRector.php
- stubs/TYPO3/CMS/Core/Utility/ArrayUtility.php
- tests/Rector/v11/v3/SwitchBehaviorOfArrayUtilityMethodsRector/Fixture/fixture.php.inc
- tests/Rector/v11/v3/SwitchBehaviorOfArrayUtilityMethodsRector/Fixture/use_array_diff_assoc_recursive.php.inc
- tests/Rector/v11/v3/SwitchBehaviorOfArrayUtilityMethodsRector/Fixture/use_array_diff_key_recursive.php.inc
- tests/Rector/v11/v3/SwitchBehaviorOfArrayUtilityMethodsRector/SwitchBehaviorOfArrayUtilityMethodsRectorTest.php
- tests/Rector/v11/v3/SwitchBehaviorOfArrayUtilityMethodsRector/config/configured_rule.php
> feat: switch behavior of ArrayUtilit::arrayDiff- methods

- src/Rector/Migrations/RenameClassMapAliasRector.php
- tests/Rector/Migrations/Fixture/stringified_classes.php.inc
> fix: prevent replacement of 'template' via RenameClassAliasRector

- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
> [BUGFIX] Catch invalid docblock parameter

- composer.json
- src/Helper/StringUtility.php
- src/Rector/v10/v0/RemovePropertyExtensionNameRector.php
> Remove usage of Stringy

- phpstan.neon
- utils/composer-packages/src/Rector/AddPackageVersionRector.php
- utils/composer-packages/src/Rector/AddReplacePackageRector.php
- utils/composer-packages/src/Rector/RemovePackageVersionsRector.php
Cherry pick of https://github.com/sabbelasichon/typo3-rector/pull/2747
> [phpstan] Improve type resolving without property_exists

- .github/workflows/coding_standard.yaml
- composer.json
- phpstan-baseline.neon
- phpstan.neon
- src/FileProcessor/TypoScript/TypoScriptFileProcessor.php
- utils/composer-packages/src/Collection/ExtensionCollection.php
- utils/composer-packages/src/Command/AddComposerTypo3ExtensionsToConfigCommand.php
- utils/composer-packages/src/Rector/AddReplacePackageRector.php
- utils/composer-packages/src/ValueObject/ExtensionVersion.php
- utils/composer-packages/tests/ComposerPackageParserTest.php
- utils/composer-packages/tests/Rector/AddReplacePackageRector/config/configured_rule.php
Split of https://github.com/sabbelasichon/typo3-rector/pull/2747
> Correct RenamePackage name, validate configure() input

- utils/composer-packages/tests/Rector/AddReplacePackageRector/config/configured_rule.php
Related to https://github.com/rectorphp/rector-src/pull/1443
> fix nested array on configure

- docs/all_rectors_overview.md
- docs/best_practice_guide.md
- docs/beyond_php_file_processors.md
- docs/configuration_and_processing.md
- docs/contribution.md
- docs/examples_in_action.md
- docs/installation.md
- docs/limitations.md
> docs: provide table of contents for each doc segment

- composer.json
- src/FileProcessor/FlexForms/FlexFormsProcessor.php
- src/FileProcessor/FlexForms/Rector/RenderTypeFlexFormRector.php
- src/FileProcessor/Fluid/FluidFileProcessor.php
- src/FileProcessor/Resources/Icons/IconsFileProcessor.php
- src/FileProcessor/TypoScript/TypoScriptFileProcessor.php
- src/FileProcessor/Yaml/Form/FormYamlFileProcessor.php
- src/FileProcessor/Yaml/YamlIndentResolver.php
- tests/FileProcessor/FlexForms/Fixture/flexforms.xml
I'm working on parallel run in Rector - https://github.com/rectorphp/rector/issues/2971  :hugs: 
After this PR, https://github.com/rectorphp/rector-src/pull/1583 it is required to return jsonable value objects, so paralell process can merge them around :) 
This PR updates architecture here, so the diff is always returned :+1:
> [Paralell] Prepare file processors for parallel run

- docs/configuration_and_processing.md
- templates/rector.php.dist
> [TASK] Add vendor and (.)Build as directories to skip

- docs/best_practice_guide.md
- docs/beyond_php_file_processors.md
- docs/configuration_and_processing.md
- docs/contribution.md
- docs/examples_in_action.md
- docs/installation.md
- docs/limitations.md
- docs/special_rules.md
> [DOCS] Provide doc segment with rules that need manual handling

- composer.json
- phpstan.neon
Avoid error on rector-src rectorphp/rector-src#1653 (comment)
> Using php-cs-fixer ^3.4

- config/v9/typo3-90.php
- src/Rector/v9/v3/BackendUserAuthenticationSimplelogRector.php
- tests/Rector/v9/v3/BackendUserAuthenticationSimplelogRector/Fixture/backend_user_authentication_simplelog.php.inc
> Check for potential empty argument

- src/Rector/v9/v4/RemoveMethodsFromEidUtilityAndTsfeRector.php
- tests/Rector/v9/v4/RemoveMethodsFromEidUtilityAndTsfeRector/Fixture/tsfe_methods.php.inc
> Fix storeSessionData method call on TSFE

- src/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php
- tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector/Fixture/extbase_controller_actions_return_response_interface.php.inc
- tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector/config/configured_rule.php
> Fix double return statement for forward method call

- src/FileProcessor/TypoScript/Rector/ExtbasePersistenceTypoScriptRector.php
- tests/FileProcessor/TypoScript/Expected/Extbase.php.inc
- tests/FileProcessor/TypoScript/Fixture/Extbase/002_extbase_persistence.txt
> Fix subclassing keys

- config/config.php
- config/v8/typo3-87.php
- src/Contract/FileProcessor/TypoScript/TypoScriptPostRectorInterface.php
- src/FileProcessor/TypoScript/PostRector/LibFluidContentToContentElementTypoScriptPostRector.php
- src/FileProcessor/TypoScript/Rector/LibFluidContentToLibContentElementRector.php
- src/FileProcessor/TypoScript/TypoScriptFileProcessor.php
- tests/FileProcessor/TypoScript/Fixture/TypoScript/lib_fluid_content.typoscript
- tests/FileProcessor/TypoScript/config/configured_rule.php
> Transform lib.fluidContent to lib.contentElement

- src/Rector/General/ExtEmConfRector.php
- tests/Rector/General/ExtEmConfRector/Fixture/different_configuration.php.inc
> Remove guard clause

- config/v11/typo3-113.php
- src/Rector/v11/v3/SubstituteExtbaseRequestGetBaseUriRector.php
- tests/Rector/v11/v3/SubstituteExtbaseRequestGetBaseUriRector/Fixture/new_request.php.inc
- tests/Rector/v11/v3/SubstituteExtbaseRequestGetBaseUriRector/SubstituteExtbaseRequestGetBaseUriRectorTest.php
- tests/Rector/v11/v3/SubstituteExtbaseRequestGetBaseUriRector/config/configured_rule.php
- utils/generator/templates/src/Rector/__Major__/__Minor__/__Name__.php
> Use PSR-7 request for getBaseUri

- config/v11/typo3-115.php
- src/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector.php
- stubs/TYPO3/CMS/Backend/Template/ModuleTemplateFactory.php
- tests/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector/Fixture/backend_template_view.php.inc
- tests/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector/Fixture/backend_template_view_action_with_one_action.php.inc
- tests/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector/Fixture/backend_template_view_action_without_statements.php.inc
- tests/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector/SubstituteBackendTemplateViewWithModuleTemplateRectorTest.php
- tests/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector/config/configured_rule.php
> Substitute BackendTemplateView

- phpstan.neon
- src/Rector/v11/v4/AddSetConfigurationMethodToExceptionHandlerRector.php
- stubs/TYPO3/CMS/Frontend/ContentObject/Exception/ExceptionHandlerInterface.php
- stubs/TYPO3/CMS/Frontend/ContentObject/Exception/ProductionExceptionHandler.php
- tests/Rector/v11/v4/AddSetConfigurationMethodToExceptionHandlerRector/AddSetConfigurationMethodToExceptionHandlerRectorTest.php
- tests/Rector/v11/v4/AddSetConfigurationMethodToExceptionHandlerRector/Fixture/custom_exception_handler_with_constructor.php.inc
- tests/Rector/v11/v4/AddSetConfigurationMethodToExceptionHandlerRector/Fixture/custom_exception_handler_without_constructor.php.inc
- tests/Rector/v11/v4/AddSetConfigurationMethodToExceptionHandlerRector/Fixture/skip_custom_exception_handler.php.inc
- tests/Rector/v11/v4/AddSetConfigurationMethodToExceptionHandlerRector/Fixture/skip_custom_exception_handler_extending_production_handler.php.inc
- tests/Rector/v11/v4/AddSetConfigurationMethodToExceptionHandlerRector/config/configured_rule.php
> Add setConfiguration method for custom ExceptionHandler

- config/v11/typo3-115.php
- src/Rector/v11/v5/SubstituteGetIconFactoryAndGetPageRendererFromModuleTemplateRector.php
- tests/Rector/v11/v5/SubstituteGetIconFactoryAndGetPageRendererFromModuleTemplateRector/Fixture/my_action_controller.php.inc
- tests/Rector/v11/v5/SubstituteGetIconFactoryAndGetPageRendererFromModuleTemplateRector/SubstituteGetIconFactoryAndGetPageRendererFromModuleTemplateRectorTest.php
- tests/Rector/v11/v5/SubstituteGetIconFactoryAndGetPageRendererFromModuleTemplateRector/config/configured_rule.php
> Use PageRenderer and IconFactory directly

- src/Rector/v10/v0/SwiftMailerBasedMailMessageToMailerBasedMessageRector.php
> Fix if parameter exists

- phpstan.neon
- src/Rector/v9/v2/PageNotFoundAndErrorHandlingRector.php
- tests/Rector/v9/v2/PageNotFoundAndErrorHandlingRector/Fixture/page_not_found_action.php.inc
> Fix missing message for method call

- src/Rector/General/InjectMethodToConstructorInjectionRector.php
- tests/Rector/General/InjectMethodToConstructorInjectionRector/Fixture/inject_if_possible.php.inc
- tests/Rector/General/InjectMethodToConstructorInjectionRector/InjectMethodToConstructorInjectionRectorTest.php
- tests/Rector/General/InjectMethodToConstructorInjectionRector/config/configured_rule.php
> feat: provide general inject replacement rector

- src/Rector/v9/v3/ValidateAnnotationRector.php
- tests/Rector/v9/v3/ValidateAnnotationRector/Fixture/validate_property.php.inc
> Fix validate annotation with whitespaces

- src/FileProcessor/TypoScript/Conditions/GlobalStringConditionMatcher.php
- tests/FileProcessor/TypoScript/Rector/OldConditionToExpressionLanguageRectorTest.php
> Fix _COOKIE conditions

- src/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php
- tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector/Fixture/skip_extbase_controller_actions.php.inc
> Do not convert abstract action methods

- config/v9/typo3-94.php
- src/Rector/v9/v4/GeneralUtilityGetHostNameToGetIndpEnvRector.php
- tests/Rector/v9/v4/GeneralUtilityGetHostNameToGetIndpEnvRector/Fixture/get_host_name_to_get_indp_env.php.inc
- tests/Rector/v9/v4/GeneralUtilityGetHostNameToGetIndpEnvRector/GeneralUtilityGetHostNameToGetIndpEnvRectorTest.php
- tests/Rector/v9/v4/GeneralUtilityGetHostNameToGetIndpEnvRector/config/configured_rule.php
> Use getIndpEnv('HTTP_HOST')

- src/Rector/Experimental/ObjectManagerGetToConstructorInjectionRector.php
- src/Rector/v9/v4/GeneralUtilityGetHostNameToGetIndpEnvRector.php
- stubs/TYPO3/CMS/Extbase/DomainObject/AbstractDomainObject.php
- stubs/TYPO3/CMS/Extbase/DomainObject/AbstractEntity.php
- stubs/TYPO3/CMS/Extbase/DomainObject/AbstractValueObject.php
- tests/Rector/Experimental/ObjectManagerGetToConstructorInjectionRector/Fixture/entities_and_value_objects.php.inc
- tests/Rector/Experimental/ObjectManagerGetToConstructorInjectionRector/Fixture/first_class.php.inc
- tests/Rector/Experimental/ObjectManagerGetToConstructorInjectionRector/ObjectManagerGetToConstructorInjectionRectorTest.php
- tests/Rector/Experimental/ObjectManagerGetToConstructorInjectionRector/Source/MyEntity.php
- tests/Rector/Experimental/ObjectManagerGetToConstructorInjectionRector/Source/MyOtherService.php
- tests/Rector/Experimental/ObjectManagerGetToConstructorInjectionRector/Source/MyService.php
- tests/Rector/Experimental/ObjectManagerGetToConstructorInjectionRector/Source/MyValueObject.php
- tests/Rector/Experimental/ObjectManagerGetToConstructorInjectionRector/config/configured_rule.php
- tests/Rector/v9/v4/GeneralUtilityGetHostNameToGetIndpEnvRector/config/configured_rule.php
- utils/phpstan/tests/Rules/AddChangelogDocBlockForRectorClass/AddChangelogDocBlockForRectorClassTest.php
- utils/phpstan/tests/Rules/AddCodeCoverageIgnoreForRectorDefinition/AddCodeCoverageIgnoreForRectorDefinitionTest.php
> Add experimental rector from ObjectManager::get to DI

- config/register-icon-to-icons-file/register-icon-to-icons-file.php
- src/Rector/v11/v5/RegisterIconToIconFileRector.php
- src/Rector/v11/v5/RegisterIconToIconFileRector/AddIconsToReturnRector.php
- src/Set/Typo3SetList.php
- tests/Rector/v11/v5/RegisterIconToIconFileRector/Fixture/Expected/Configuration/Icons.php.inc
- tests/Rector/v11/v5/RegisterIconToIconFileRector/Fixture/my_extension/ext_localconf.php.inc
- tests/Rector/v11/v5/RegisterIconToIconFileRector/RegisterIconToIconFileRectorTest.php
- tests/Rector/v11/v5/RegisterIconToIconFileRector/config/configured_rule.php
> TASK: Add Icons.php rector

- composer.json
- src/FileProcessor/FlexForms/Rector/RenderTypeFlexFormRector.php
- src/Rector/v10/v0/UseControllerClassesInExtbasePluginsAndModulesRector.php
- src/Rector/v11/v5/RegisterIconToIconFileRector.php
- src/Rector/v11/v5/RegisterIconToIconFileRector/AddIconsToReturnRector.php
- src/Rector/v9/v5/ExtbaseCommandControllerToSymfonyCommandRector.php
See https://github.com/rectorphp/rector-src/pull/2036
> Use custom NodePrinterInterface

- composer.json
- src/Rector/v11/v5/RegisterIconToIconFileRector.php
Follow up to similar https://github.com/sabbelasichon/typo3-rector/pull/2832
Ref https://github.com/rectorphp/rector-src/pull/2038
> Add RemovedAndAddedFilesCollector as explicit service

- composer.json
- src/NodeFactory/ImportExtbaseAnnotationIfMissingFactory.php
- src/Rector/Migrations/RenameClassMapAliasRector.php
- src/Rector/v8/v6/MigrateLastPiecesOfDefaultExtrasRector.php
- src/Rector/v8/v6/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRector.php
- src/Rector/v8/v7/MoveForeignTypesToOverrideChildTcaRector.php
Related to https://github.com/rectorphp/rector-src/pull/2136
> Narrowing current statement

- composer.json
- tests/Rector/v10/v2/InjectEnvironmentServiceIfNeededInResponseRector/Fixture/inject_environment_service_if_needed.php.inc
Ref https://github.com/rectorphp/rector-src/pull/2164
> Update fixture with fixed import

- src/Rector/v12/v0/MigrateInternalTypeRector.php
- tests/Rector/v12/v0/MigrateInternalTypeRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/MigrateInternalTypeRector/MigrateInternalTypeRectorTest.php
- tests/Rector/v12/v0/MigrateInternalTypeRector/config/configured_rule.php
> feat: provide migration for internal_type

- config/v11/typo3-110.php
- src/FileProcessor/TypoScript/Rector/TemplateToFluidTemplateTypoScriptRector.php
- tests/FileProcessor/TypoScript/Fixture/TypoScript/template_to_fluidtemplate.typoscript
- tests/FileProcessor/TypoScript/config/configured_rule.php
> TASK: Add rule TemplateToFluidTemplateTypoScriptRector

- Migrations/TYPO3/12.0/typo3/sysext/backend/Migrations/Code/ClassAliasMap.php
- Migrations/TYPO3/12.0/typo3/sysext/frontend/Migrations/Code/ClassAliasMap.php
- config/v12/typo3-120.php
- docs/best_practice_guide.md
> TASK: Add ClassAliasMaps for version 12.0

- config/v12/typo3-120.php
- src/Rector/v12/v0/ReplacePreviewUrlMethodRector.php
- stubs/Psr/Http/Message/UriInterface.php
- stubs/TYPO3/CMS/Backend/Routing/PreviewUriBuilder.php
- stubs/TYPO3/CMS/Backend/Utility/BackendUtility.php
- stubs/TYPO3/CMS/Core/Http/Uri.php
- tests/Rector/v12/v0/ReplacePreviewUrlMethodRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/ReplacePreviewUrlMethodRector/ReplacePreviewUrlMethodRectorTest.php
- tests/Rector/v12/v0/ReplacePreviewUrlMethodRector/config/configured_rule.php
> feat: provide replacement for BackendUtility::getPreviewUrl()

- src/FileProcessor/Resources/Icons/IconsFileProcessor.php
- src/FileProcessor/Resources/Icons/Rector/IconsRector.php
- src/Rector/v9/v5/ExtbaseCommandControllerToSymfonyCommandRector.php
> TASK: Get rid of SmartFileSystem

- config/v12/tca-120.php
- src/Helper/StringUtility.php
- src/Rector/v12/v0/MigrateNullFlagRector.php
- tests/Rector/v12/v0/MigrateNullFlagRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/MigrateNullFlagRector/MigrateNullFlagRectorTest.php
- tests/Rector/v12/v0/MigrateNullFlagRector/config/configured_rule.php
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/74319/5/typo3/sysext/core/Classes/Migrations/TcaMigration.php
Resolves: #2954
> [FEATURE] Add TCA option nullable instead of eval=null

- src/Rector/v12/v0/MigrateRequiredFlagRector.php
- tests/Rector/v12/v0/MigrateRequiredFlagRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/MigrateRequiredFlagRector/MigrateRequiredFlagRectorTest.php
- tests/Rector/v12/v0/MigrateRequiredFlagRector/config/configured_rule.php
See https://review.typo3.org/c/Packages/TYPO3.CMS/+/73709/18/typo3/sysext/core/Classes/Migrations/TcaMigration.php
Resolves: #2944
> [FEATURE] Add required flag in TCA instead of `eval` option

- config/config.php
- config/v12/typo3-120.php
- src/Contract/FileProcessor/Resources/FileRectorInterface.php
- src/FileProcessor/Resources/Files/ExtTypoScriptFileProcessor.php
- src/FileProcessor/Resources/Files/Rector/RenameExtTypoScriptFilesFileRector.php
- tests/FileProcessor/Resources/Files/ExtTypoScriptFileProcessor/ExtTypoScriptFileProcessorTest.php
- tests/FileProcessor/Resources/Files/ExtTypoScriptFileProcessor/config/configured_rule.php
> TASK: Rename ext_typoscript_*.txt

- src/FileProcessor/TypoScript/Collector/RemoveTypoScriptStatementCollector.php
- src/FileProcessor/TypoScript/Rector/AbstractTypoScriptRector.php
- src/FileProcessor/TypoScript/Rector/v12/v0/RemoveDisableCharsetHeaderConfigTypoScriptRector.php
- src/FileProcessor/TypoScript/TypoScriptFileProcessor.php
- tests/FileProcessor/TypoScript/v12/v0/RemoveDisableCharsetHeaderConfigTypoScriptRector/Fixture/disable_charset_header.typoscript
- tests/FileProcessor/TypoScript/v12/v0/RemoveDisableCharsetHeaderConfigTypoScriptRector/RemoveDisableCharsetHeaderConfigTypoScriptRectorTest.php
- tests/FileProcessor/TypoScript/v12/v0/RemoveDisableCharsetHeaderConfigTypoScriptRector/config/configured_rule.php
> TASK: Remove disableCharsetHeader

- composer.json
- utils/composer-packages/src/Command/AddComposerTypo3ExtensionsToConfigCommand.php
- utils/generator/src/Command/Typo3GenerateCommand.php
- utils/phpstan/src/Rules/AddChangelogDocBlockForRectorClassRule.php
- [DX] simplify command naming
- replace deprecated Broker to ReflectionProvider in PHPStanp
> [DX] Make command naming more explicit

- config/v12/typo3-120.php
- src/Rector/v12/v0/typo3/RemoveUpdateRootlineDataRector.php
- tests/Rector/v12/v0/typo3/RemoveUpdateRootlineDataRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/RemoveUpdateRootlineDataRector/RemoveUpdateRootlineDataRectorTest.php
- tests/Rector/v12/v0/typo3/RemoveUpdateRootlineDataRector/config/configured_rule.php
> [FEATURE] Remove TemplateService->updateRootlineData()

- config/v12/typo3-120.php
- docs/all_rectors_overview.md
- src/Rector/v12/v0/typo3/ReplaceTSFEWithContextMethodsRector.php
- stubs/TYPO3/CMS/Core/Context/Context.php
- stubs/TYPO3/CMS/Core/Context/DateTimeAspect.php
- stubs/TYPO3/CMS/Core/Context/UserAspect.php
- stubs/TYPO3/CMS/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v12/v0/typo3/ReplaceTSFEWithContextMethodsRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/ReplaceTSFEWithContextMethodsRector/ReplaceTSFEWithContextMethodsRectorTest.php
- tests/Rector/v12/v0/typo3/ReplaceTSFEWithContextMethodsRector/config/configured_rule.php
> [FEATURE] Replace TSFE methods with according Context methods

- config/v12/typo3-120.php
- docs/all_rectors_overview.md
- rector.php
- src/Rector/v12/v0/typo3/HintNecessaryUploadedFileChangesRector.php
- stubs/TYPO3/CMS/Core/Http/UploadedFile.php
- stubs/TYPO3/CMS/Core/Resource/ResourceStorage.php
- tests/Rector/v12/v0/typo3/HintNecessaryUploadedFileChangesRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/HintNecessaryUploadedFileChangesRector/Fixture/fixture_no_apply_needed.php.inc
- tests/Rector/v12/v0/typo3/HintNecessaryUploadedFileChangesRector/Fixture/fixture_not_fitting_override.php.inc
- tests/Rector/v12/v0/typo3/HintNecessaryUploadedFileChangesRector/Fixture/fixture_with_existing_comments.php.inc
- tests/Rector/v12/v0/typo3/HintNecessaryUploadedFileChangesRector/Fixture/fixture_with_existing_doc_comment.php.inc
- tests/Rector/v12/v0/typo3/HintNecessaryUploadedFileChangesRector/HintNecessaryUploadedFileChangesRectorTest.php
- tests/Rector/v12/v0/typo3/HintNecessaryUploadedFileChangesRector/config/configured_rule.php
> [FEATURE] Add hint to adapt addUploadedFile override

- composer.json
- config/v12/typoscript-120.php
- docs/all_rectors_overview.md
- phpstan-baseline.neon
- phpstan.neon
- src/Rector/v12/v0/typoscript/RemoveSpamProtectEmailAddressesAsciiOptionRector.php
- tests/Rector/v12/v0/typoscript/RemoveSpamProtectEmailAddressesAsciiOptionRector/Fixture/fixture-keep.typoscript
- tests/Rector/v12/v0/typoscript/RemoveSpamProtectEmailAddressesAsciiOptionRector/Fixture/fixture.typoscript
- tests/Rector/v12/v0/typoscript/RemoveSpamProtectEmailAddressesAsciiOptionRector/RemoveSpamProtectEmailAddressesAsciiOptionRectorTest.php
- tests/Rector/v12/v0/typoscript/RemoveSpamProtectEmailAddressesAsciiOptionRector/config/configured_rule.php
> [TASK] Remove config.spamProtectEmailAddresses with option "ascii"

- config/v12/typo3-120.php
- docs/all_rectors_overview.md
- src/Rector/v12/v0/typo3/UseCompositeExpressionStaticMethodsRector.php
- stubs/TYPO3/CMS/Core/Database/Query/Expression/CompositeExpression.php
- tests/Rector/v12/v0/typo3/HintNecessaryUploadedFileChangesRector/config/configured_rule.php
- tests/Rector/v12/v0/typo3/ReplaceContentObjectRendererGetMailToWithEmailLinkBuilderRector/config/configured_rule.php
- tests/Rector/v12/v0/typo3/UseCompositeExpressionStaticMethodsRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/UseCompositeExpressionStaticMethodsRector/UseCompositeExpressionStaticMethodsRectorTest.php
- tests/Rector/v12/v0/typo3/UseCompositeExpressionStaticMethodsRector/config/configured_rule.php
> [FEATURE] Use static methods instead of constructor for CompositeExpression

- config/v12/typo3-120.php
- docs/all_rectors_overview.md
- src/Rector/v12/v0/typo3/SubstituteCompositeExpressionAddMethodsRector.php
- stubs/TYPO3/CMS/Core/Database/Query/Expression/CompositeExpression.php
- tests/Rector/v12/v0/typo3/SubstituteCompositeExpressionAddMethodsRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/SubstituteCompositeExpressionAddMethodsRector/SubstituteCompositeExpressionAddMethodsRectorTest.php
- tests/Rector/v12/v0/typo3/SubstituteCompositeExpressionAddMethodsRector/config/configured_rule.php
> [FEATURE] Replace add() and addMultiple() of CompositeExpression with with()

- src/Rector/v11/v0/ForwardResponseInsteadOfForwardMethodRector.php
- tests/Rector/v11/v0/ForwardResponseInsteadOfForwardMethodRector/Fixture/foward_response_instead_of_method_forward.php.inc
> [BUGFIX] Resolve ReturnType 'void' along with DocComment

- config/v12/tca-120.php
- docs/all_rectors_overview.md
- src/Rector/v12/v0/tca/RemoveTCAInterfaceAlwaysDescriptionRector.php
- tests/Rector/v12/v0/tca/RemoveTCAInterfaceAlwaysDescriptionRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/tca/RemoveTCAInterfaceAlwaysDescriptionRector/RemoveTCAInterfaceAlwaysDescriptionRectorTest.php
- tests/Rector/v12/v0/tca/RemoveTCAInterfaceAlwaysDescriptionRector/config/configured_rule.php
> [FEATURE] Remove redundant ['interface']['always_description']

- config/v12/typo3-120.php
- docs/all_rectors_overview.md
- src/Rector/v12/v0/typo3/ReplaceExpressionBuilderMethodsRector.php
- stubs/Doctrine/DBAL/Result.php
- stubs/TYPO3/CMS/Core/Database/Connection.php
- stubs/TYPO3/CMS/Core/Database/Query/Expression/ExpressionBuilder.php
- stubs/TYPO3/CMS/Core/Database/Query/QueryBuilder.php
- tests/Rector/v12/v0/typo3/ReplaceExpressionBuilderMethodsRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/ReplaceExpressionBuilderMethodsRector/ReplaceExpressionBuilderMethodsRectorTest.php
- tests/Rector/v12/v0/typo3/ReplaceExpressionBuilderMethodsRector/config/configured_rule.php
> [FEATURE] Substitute ExpressionBuilder methods andX() & orX()

- config/v12/typo3-120.php
- config/v12/typoscript-120.php
- docs/all_rectors_overview.md
- phpstan-baseline.neon
- src/Rector/v12/v0/typo3/RemoveRedundantFeLoginModeMethodsRector.php
- src/Rector/v12/v0/typoscript/RemoveSendCacheHeadersConfigOptionRector.php
- stubs/TYPO3/CMS/Frontend/Authentication/FrontendUserAuthentication.php
- tests/Rector/v12/v0/typo3/RemoveRedundantFeLoginModeMethodsRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/RemoveRedundantFeLoginModeMethodsRector/RemoveRedundantFeLoginModeMethodsRectorTest.php
- tests/Rector/v12/v0/typo3/RemoveRedundantFeLoginModeMethodsRector/config/configured_rule.php
- tests/Rector/v12/v0/typoscript/RemoveSendCacheHeadersConfigOptionRector/Fixture/fixture.typoscript
- tests/Rector/v12/v0/typoscript/RemoveSendCacheHeadersConfigOptionRector/RemoveSendCacheHeadersConfigOptionRectorTest.php
- tests/Rector/v12/v0/typoscript/RemoveSendCacheHeadersConfigOptionRector/config/configured_rule.php
> [FEATURE] Provide components handling the fe_login_mode

- docs/all_rectors_overview.md
- src/FileProcessor/Fluid/Rector/v10/v0/RemoveNoCacheHashAndUseCacheHashAttributeFluidRector.php
- tests/FileProcessor/Fluid/Rector/v10/v0/RemoveNoCacheHashAndUseCacheHashAttributeFluidRector/Fixture/fixture.html
- tests/FileProcessor/Fluid/Rector/v10/v0/RemoveNoCacheHashAndUseCacheHashAttributeFluidRector/RemoveNoCacheHashAndUseCacheHashAttributeFluidRectorTest.php
- tests/FileProcessor/Fluid/Rector/v10/v0/RemoveNoCacheHashAndUseCacheHashAttributeFluidRector/config/configured_rule.php
> [TASK] Add RemoveNoCacheHashAndUseCacheHashAttributeFluidRector

- utils/generator/src/Command/Typo3GenerateCommand.php
- utils/generator/src/FileSystem/ConfigFilesystem.php
- utils/generator/templates/config/config.php
> TASK: Create base file for new config set

- docs/beyond_php_file_processors.md
- docs/configuration_and_processing.md
- docs/special_rules.md
> [TASK] Update docs to use rectorConfig everyhwere

- config/v12/typo3-120.php
- src/Rector/v12/v0/typo3/AddMethodToWidgetInterfaceClassesRector.php
- stubs/TYPO3/CMS/Dashboard/Widgets/WidgetInterface.php
- tests/Rector/v12/v0/typo3/AddMethodToWidgetInterfaceClassesRector/AddMethodToWidgetInterfaceClassesRectorTest.php
- tests/Rector/v12/v0/typo3/AddMethodToWidgetInterfaceClassesRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/AddMethodToWidgetInterfaceClassesRector/Fixture/fixture_with_existing_method.php.inc
- tests/Rector/v12/v0/typo3/AddMethodToWidgetInterfaceClassesRector/config/configured_rule.php
> [FEATURE] Add method according to WidgetInterface integration

- config/v12/resources-120.php
- src/FileProcessor/Resources/Files/Rector/v12/v0/RenameConstantsAndSetupFileEndingRector.php
- src/Rector/v12/v0/typo3/AddMethodToWidgetInterfaceClassesRector.php
- tests/FileProcessor/Resources/Files/Rector/v12/v0/RenameConstantsAndSetupFileEndingRector/RenameConstantsAndSetupFileEndingRectorTest.php
- tests/FileProcessor/Resources/Files/Rector/v12/v0/RenameConstantsAndSetupFileEndingRector/config/configured_rule.php
> [TASK] Rename constants|setup.txt to typoscript

- config/v12/typo3-120.php
- src/Rector/v12/v0/typo3/MigrateQueryBuilderExecuteRector.php
- stubs/TYPO3/CMS/Core/Database/Query/QueryBuilder.php
- tests/Rector/v12/v0/typo3/MigrateQueryBuilderExecuteRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/MigrateQueryBuilderExecuteRector/MigrateQueryBuilderExecuteRectorTest.php
- tests/Rector/v12/v0/typo3/MigrateQueryBuilderExecuteRector/config/configured_rule.php
> [FEATURE] Migrate Querybuilder->execute()

- config/v10/typo3-100.php
- config/v7/typo3-70.php
- config/v7/typo3-76.php
- src/NodeFactory/ImportExtbaseAnnotationIfMissingFactory.php
- src/Rector/Migrations/RenameClassMapAliasRector.php
> TASK: Use constant from AbstractMessage

- src/FileProcessor/TypoScript/TypoScriptFileProcessor.php
- src/NodeAnalyzer/CommandArrayDecorator.php
- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
- src/Rector/General/InjectMethodToConstructorInjectionRector.php
- src/Rector/v11/v4/RegisterIconToIconFileRector.php
- src/Rector/v8/v6/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRector.php
- tests/Rector/v8/v6/MigrateSpecialConfigurationAndRemoveShowItemStylePointerConfigRector/Fixture/skip_formatting.php.inc
- utils/composer-packages/src/ComposerPackageParser.php
- utils/generator/src/Command/Typo3GenerateCommand.php
> TASK: Do not reformat if nothing has changed 

- config/v12/typo3-120.php
- src/Rector/v12/v0/typo3/RemoveRelativeToCurrentScriptArgumentsRector.php
- stubs/TYPO3/CMS/Backend/Backend/Avatar/Image.php
- stubs/TYPO3/CMS/Core/Resource/File.php
- stubs/TYPO3/CMS/Core/Resource/Rendering/AudioTagRenderer.php
- stubs/TYPO3/CMS/Core/Resource/Rendering/FileRendererInterface.php
- stubs/TYPO3/CMS/Core/Resource/Rendering/VideoTagRenderer.php
- stubs/TYPO3/CMS/Core/Resource/Rendering/VimeoRenderer.php
- stubs/TYPO3/CMS/Core/Resource/Rendering/YoutubeRenderer.php
- tests/Rector/v12/v0/typo3/RemoveRelativeToCurrentScriptArgumentsRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/RemoveRelativeToCurrentScriptArgumentsRector/Fixture/fixture_class.php.inc
- tests/Rector/v12/v0/typo3/RemoveRelativeToCurrentScriptArgumentsRector/Fixture/keep_render_method_parameters.php.inc
- tests/Rector/v12/v0/typo3/RemoveRelativeToCurrentScriptArgumentsRector/RemoveRelativeToCurrentScriptArgumentsRectorTest.php
- tests/Rector/v12/v0/typo3/RemoveRelativeToCurrentScriptArgumentsRector/Source/TestFileRendering.php
- tests/Rector/v12/v0/typo3/RemoveRelativeToCurrentScriptArgumentsRector/config/configured_rule.php
> [FEATURE] Remove redundant param from FileRenderer render methods

- config/v12/tca-120.php
- src/Helper/StringUtility.php
- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
- src/Rector/v12/v0/tca/RemoveCruserIdRector.php
- tests/Rector/General/ConvertImplicitVariablesToExplicitGlobalsRector/Fixture/ext_localconf.php.inc
- tests/Rector/v12/v0/tca/RemoveCruserIdRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/tca/RemoveCruserIdRector/RemoveCruserIdRectorTest.php
- tests/Rector/v12/v0/tca/RemoveCruserIdRector/config/configured_rule.php
> [FEATURE] Provide rule to remove redundant cruser_id from TCA ctrl

- config/v12/typoscript-120.php
- src/Rector/v12/v0/typoscript/RemoveConfigDoctypeSwitchRector.php
- tests/Rector/v12/v0/typoscript/RemoveConfigDoctypeSwitchRector/Fixture/fixture.typoscript
- tests/Rector/v12/v0/typoscript/RemoveConfigDoctypeSwitchRector/RemoveConfigDoctypeSwitchRectorTest.php
- tests/Rector/v12/v0/typoscript/RemoveConfigDoctypeSwitchRector/config/configured_rule.php
> [FEATURE] Provide rule to remove config.doctypeSwitch

- config/v12/typo3-120.php
- config/v12/typoscript-120.php
- src/Rector/v12/v0/typo3/UseConfigArrayForTSFEPropertiesRector.php
- src/Rector/v12/v0/typoscript/UseConfigArrayForTSFEPropertiesRector.php
- stubs/TYPO3/CMS/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v12/v0/typo3/UseConfigArrayForTSFEPropertiesRector/Fixture/use_config_array.php.inc
- tests/Rector/v12/v0/typo3/UseConfigArrayForTSFEPropertiesRector/UseConfigArrayForTSFEPropertiesRectorTest.php
- tests/Rector/v12/v0/typo3/UseConfigArrayForTSFEPropertiesRector/config/configured_rule.php
- tests/Rector/v12/v0/typoscript/UseConfigArrayForTSFEPropertiesRector/Fixture/use_config_array.typoscript
- tests/Rector/v12/v0/typoscript/UseConfigArrayForTSFEPropertiesRector/UseConfigArrayForTSFEPropertiesRectorTest.php
- tests/Rector/v12/v0/typoscript/UseConfigArrayForTSFEPropertiesRector/config/configured_rule.php
> TASK: Add rector for PHP and TypoScript

- config/v12/typo3-120.php
- docs/all_rectors_overview.md
- src/Rector/v12/v0/typo3/RemoveMailerAdapterInterfaceRector.php
- stubs/TYPO3/CMS/Mail/MailerAdapterInterface.php
- tests/Rector/v12/v0/typo3/RemoveMailerAdapterInterfaceRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/RemoveMailerAdapterInterfaceRector/RemoveMailerAdapterInterfaceRectorTest.php
- tests/Rector/v12/v0/typo3/RemoveMailerAdapterInterfaceRector/config/configured_rule.php
> [TASK] Add rule to remove MailerAdapterInterface

- composer.json
- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
- src/NodeFactory/InjectMethodFactory.php
- src/Rector/v10/v0/ConfigurationManagerAddControllerConfigurationMethodRector.php
- src/Rector/v10/v2/InjectEnvironmentServiceIfNeededInResponseRector.php
- src/Rector/v11/v4/ProvideCObjViaMethodRector.php
> TASK: Remove symplify/astral

- src/FileProcessor/Resources/Icons/IconsFileProcessor.php
- src/Helper/FilesFinder.php
- src/NodeFactory/InitializeArgumentsClassMethodFactory.php
- src/Rector/General/ConvertImplicitVariablesToExplicitGlobalsRector.php
- src/Rector/v11/v0/SubstituteConstantsModeAndRequestTypeRector.php
- src/Rector/v11/v2/MigrateFrameModuleToSvgTreeRector.php
- tests/Rector/v9/v0/MoveRenderArgumentsToInitializeArgumentsMethodRector/Fixture/my_viewhelper_with_already_existing_arguments.php.inc
> TASK: Keep already existing arguments 

- config/v12/typoscript-120.php
- src/Rector/v12/v0/typoscript/RemoveTSConfigModesRector.php
- tests/Rector/v12/v0/typoscript/RemoveTSConfigModesRector/Fixture/fixture.typoscript
- tests/Rector/v12/v0/typoscript/RemoveTSConfigModesRector/RemoveTSConfigModesRectorTest.php
- tests/Rector/v12/v0/typoscript/RemoveTSConfigModesRector/config/configured_rule.php
> [TASK] Remove unused wordspace TSConfig modes

- config/v12/typoscript-120.php
- src/Rector/v12/v0/typoscript/RemoveNewContentElementWizardOptionsRector.php
- tests/Rector/v12/v0/typoscript/RemoveNewContentElementWizardOptionsRector/Fixture/fixture.typoscript
- tests/Rector/v12/v0/typoscript/RemoveNewContentElementWizardOptionsRector/RemoveNewContentElementWizardOptionsRectorTest.php
- tests/Rector/v12/v0/typoscript/RemoveNewContentElementWizardOptionsRector/config/configured_rule.php
> [TASK] Remove TSConfig mod options for new element wizard

- docs/configuration_and_processing.md
- templates/rector.php.dist
> TASK: Add skip configuration for NameImportingPostRector

- src/FileProcessor/Yaml/YamlIndentResolver.php
- tests/FileProcessor/Yaml/Form/Rector/v10/v0/EmailFinisherRector/Fixture/my_form.form.yaml
> TASK: Trim the yaml file contents

- config/v12/typoscript-120.php
- src/Rector/v12/v0/typoscript/RenameMailLinkHandlerKeyRector.php
- tests/Rector/v12/v0/typoscript/RenameMailLinkHandlerKeyRector/Fixture/fixture.typoscript
- tests/Rector/v12/v0/typoscript/RenameMailLinkHandlerKeyRector/RenameMailLinkHandlerKeyRectorTest.php
- tests/Rector/v12/v0/typoscript/RenameMailLinkHandlerKeyRector/config/configured_rule.php
> TASK: Rename key from mail to email

- config/v11/typo3-112.php
- src/NodeFactory/Typo3GlobalsFactory.php
- src/Rector/v11/v2/typo3/SubstituteEnvironmentServiceWithApplicationTypeRector.php
- stubs/TYPO3/CMS/Extbase/Service/EnvironmentService.php
- tests/Rector/v11/v2/typo3/SubstituteEnvironmentServiceWithApplicationTypeRector/Fixture/enviornment_application_type.php.inc
- tests/Rector/v11/v2/typo3/SubstituteEnvironmentServiceWithApplicationTypeRector/Source/MyCustomEnvironment.php
- tests/Rector/v11/v2/typo3/SubstituteEnvironmentServiceWithApplicationTypeRector/SubstituteEnvironmentServiceWithApplicationTypeRectorTest.php
- tests/Rector/v11/v2/typo3/SubstituteEnvironmentServiceWithApplicationTypeRector/config/configured_rule.php
> TASK: Add SubstituteEnvironmentServiceWithApplicationTypeRector

- config/v12/typo3-120.php
- ecs.php
- src/NodeVisitor/RemoveExtbaseTypeConverterNodeVisitor.php
- src/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector.php
- stubs/TYPO3/CMS/Extbase/Property/TypeConverterInterface.php
- stubs/TYPO3/CMS/Extbase/Utility/ExtensionUtility.php
- tests/FileProcessor/Resources/Icons/Rector/v8/v3/IconsRector/IconsRectorTest.php
- tests/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector/Fixture/ExpectedMySecondSpecialTypeConverter.php
- tests/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector/Fixture/ExpectedMySpecialTypeConverter.php
- tests/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector/Fixture/ExpectedServices.yaml
- tests/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector/Fixture/Services.yaml
- tests/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector/Fixture/ext_localconf.php.inc
- tests/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector/RegisterExtbaseTypeConvertersAsServicesRectorTest.php
- tests/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector/Source/MySecondSpecialTypeConverter.php
- tests/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector/Source/MySpecialEntity.php
- tests/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector/Source/MySpecialTypeConverter.php
- tests/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector/config/configured_rule.php
> TASK: Extract type converters to services.yaml

- src/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php
- tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector/Fixture/skip_extbase_controller_actions.php.inc
> TASK: Do not touch return inside a closure

- .github/workflows/rector.yaml
- src/FileProcessor/Resources/Icons/IconsFileProcessor.php
- src/FileProcessor/TypoScript/Conditions/GlobalStringConditionMatcher.php
- src/FileProcessor/TypoScript/Conditions/GlobalVarConditionMatcher.php
- src/FileProcessor/TypoScript/Conditions/PageConditionMatcher.php
- src/FileProcessor/TypoScript/Conditions/TimeConditionMatcher.php
- src/FileProcessor/TypoScript/Rector/v9/v4/OldConditionToExpressionLanguageTypoScriptRector.php
- src/FileProcessor/TypoScript/TypoScriptFileProcessor.php
- src/NodeAnalyzer/ExtbaseControllerRedirectAnalyzer.php
- src/Rector/General/ConvertImplicitVariablesToExplicitGlobalsRector.php
- src/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php
- src/Rector/v11/v3/typo3/UseNormalizedParamsToGetRequestUrlRector.php
- src/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector.php
- src/Rector/v12/v0/typo3/ImplementSiteLanguageAwareInterfaceRector.php
- src/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector.php
- src/Rector/v12/v0/typo3/UseConfigArrayForTSFEPropertiesRector.php
- tests/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector/Fixture/backend_template_view.php.inc
- utils/phpstan/src/Rules/AddChangelogDocBlockForRectorClassRule.php
- utils/phpstan/src/Rules/AddCodeCoverageIgnoreForRectorDefinitionRule.php
> TASK: Fix bug for method with redirect

- config/v12/typo3-120.php
- src/Rector/v12/v0/typo3/ChangeExtbaseValidatorsRector.php
- stubs/TYPO3/CMS/Extbase/Error/Result.php
- stubs/TYPO3/CMS/Extbase/Validation/Validator/AbstractValidator.php
- stubs/TYPO3/CMS/Extbase/Validation/Validator/ValidatorInterface.php
- tests/Rector/v12/v0/typo3/ChangeExtbaseValidatorsRector/ChangeExtbaseValidatorsRectorTest.php
- tests/Rector/v12/v0/typo3/ChangeExtbaseValidatorsRector/Fixture/custom_validator_extending_abstract_validator.php.inc
- tests/Rector/v12/v0/typo3/ChangeExtbaseValidatorsRector/Fixture/custom_validator_implementing_validator_interface.php.inc
- tests/Rector/v12/v0/typo3/ChangeExtbaseValidatorsRector/Fixture/custom_validator_without_options.php.inc
- tests/Rector/v12/v0/typo3/ChangeExtbaseValidatorsRector/config/configured_rule.php
> TASK: Change extbase validators signatures

- composer.json
- config/solr/solr-11.x.php
- config/solr/v11/solr-11.0.php
- phpstan.neon
- src/Set/Extension/SolrSetList.php
- stubs/ApacheSolrForTypo3/Solr/System/Url/UrlHelper.php
- tests/Rector/Extensions/solr/v11/Fixture/fixture.php.inc
- tests/Rector/Extensions/solr/v11/RenameMethodsTest.php
- tests/Rector/Extensions/solr/v11/config/configured_rule.php
> TASK: Add rules for Solr version 11

- config/config.php
- config/v12/annotations_to_attributes.php
- src/AttributeDecorator/ExtbaseCascadeAttributeDecorator.php
- src/AttributeDecorator/ExtbaseIgnoreValidationAttributeDecorator.php
- src/AttributeDecorator/ExtbaseValidateAttributeDecorator.php
- src/Rector/v11/v0/ForwardResponseInsteadOfForwardMethodRector.php
- src/Rector/v8/v6/AddTypeToColumnConfigRector.php
- src/Rector/v8/v6/RichtextFromDefaultExtrasToEnableRichtextRector.php
- stubs/TYPO3/CMS/Extbase/Annotation/IgnoreValidation.php
- stubs/TYPO3/CMS/Extbase/Annotation/ORM/Cascade.php
- stubs/TYPO3/CMS/Extbase/Annotation/ORM/Lazy.php
- stubs/TYPO3/CMS/Extbase/Annotation/ORM/Transient.php
- stubs/TYPO3/CMS/Extbase/Annotation/Validate.php
- stubs/TYPO3/CMS/Extbase/Validation/Validator/NotEmptyValidator.php
- tests/Rector/v12/v0/typo3/AnnotationsToAttributes/AnnotationsToAttributesRectorTest.php
- tests/Rector/v12/v0/typo3/AnnotationsToAttributes/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/AnnotationsToAttributes/config/configured_rule.php
- tests/Rector/v9/v0/ReplaceExtKeyWithExtensionKeyRector/ReplaceExtKeyWithExtensionKeyFromComposerJsonNameRectorTest.php
- tests/Rector/v9/v0/SubstituteGeneralUtilityDevLogRector/Fixture/devlog_logging_api.php
> TASK: Annotations to Attributes

- config/v12/typo3-120.php
- src/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector.php
- tests/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector/ContentObjectRegistrationViaServiceConfigurationRectorTest.php
- tests/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector/Fixture/ExpectedServices.yaml
- tests/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector/Fixture/ext_localconf.php.inc
- tests/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector/Source/MultiValue.php
- tests/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector/Source/SingleValue.php
- tests/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector/config/configured_rule.php
> TASK: ContentObject Registration via service configuration

- src/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector.php
- tests/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector/Fixture/ExpectedServices.yaml
Resolves: #3415
Related: ##3344
> BUGFIX: Correctly nest tags for ContentObject registration

- src/FileProcessor/Resources/Files/Rector/v12/v0/RenameExtTypoScriptFilesFileRector.php
- tests/FileProcessor/Resources/Files/Rector/v12/v0/RenameExtTypoScriptFiles/RenameExtTypoScriptFilesFileRectorTest.php
- tests/Rector/v10/v0/DatabaseRecordListRector/Fixture/database_record_list_renaming.php
> TASK: Fix missing slash

- src/Rector/v11/v3/RemoveBackendUtilityViewOnClickUsageRector.php
- tests/Rector/v11/v3/RemoveBackendUtilityViewOnClickUsageRector/Fixture/fixture.php.inc
> TASK: Remove withRootline if null

- src/FileProcessor/Yaml/Form/FormYamlFileProcessor.php
- src/Helper/SymfonyYamlParser.php
- src/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector.php
- src/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector.php
> TASK: Add SymfonyYamlParser as service

- src/Rector/v9/v0/ReplacedGeneralUtilitySysLogWithLogginApiRector.php
- tests/Rector/v9/v0/ReplacedGeneralUtilitySysLogWithLogginApiRector/Fixture/sys_log_logging_api.php.inc
> TASK: Casting severity to int

- src/AttributeDecorator/ExtbaseCascadeAttributeDecorator.php
- src/Rector/v11/v0/ReplaceInjectAnnotationWithMethodRector.php
- src/Rector/v12/v0/typo3/AddMethodToWidgetInterfaceClassesRector.php
- src/Rector/v12/v3/tca/MigrateItemsIndexedKeysToAssociativeRector.php
- src/Rector/v9/v0/InjectAnnotationRector.php
- src/Rector/v9/v0/RefactorBackendUtilityGetPagesTSconfigRector.php
- tests/Rector/v12/v0/typo3/AnnotationsToAttributes/Fixture/fixture.php.inc
- tests/Rector/v12/v3/tca/MigrateItemsIndexedKeysToAssociativeRector/Fixture/fixture.php.inc
> TASK: Fix wrong cascade remove annotation

- config/v12/tca-120.php
- src/Rector/v12/v0/tca/MigrateToEmailTypeRector.php
- tests/Rector/v12/v0/tca/MigrateToEmailTypeRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/tca/MigrateToEmailTypeRector/MigrateToEmailTypeRectorTest.php
- tests/Rector/v12/v0/tca/MigrateToEmailTypeRector/config/configured_rule.php
> feat: provide MigrateToEmailTypeRector rule

- src/Rector/v12/v0/typo3/AbstractMessageGetSeverityRector.php
- tests/Rector/v12/v0/typo3/AbstractMessageGetSeverityRector/Fixture/FlashMessage.php.inc
> TASK: Fix non idempotent rector

- config/v11/typo3-113.php
> fix: add missed out rector rules to v11 config

- config/v12/tca-120.php
- src/Rector/v12/v0/tca/MigrateInputDateTimeRector.php
- tests/Rector/v12/v0/tca/MigrateInputDateTimeRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/tca/MigrateInputDateTimeRector/MigrateInputDateTimeRectorTest.php
- tests/Rector/v12/v0/tca/MigrateInputDateTimeRector/config/configured_rule.php
https://github.com/sabbelasichon/typo3-rector/issues/3556
> [FEATURE] New TCA type "datetime" (#3556)

- config/v12/tca-120.php
- phpstan-baseline.neon
- phpstan.neon
- src/FileProcessor/FlexForms/FlexFormsProcessor.php
- src/Helper/FlexFormHelperTrait.php
- src/Rector/v12/v0/flexform/MigrateEvalIntAndDouble2ToTypeNumberFlexFormRector.php
- src/Rector/v12/v0/tca/MigrateEvalIntAndDouble2ToTypeNumberRector.php
- tests/Rector/v12/v0/flexform/MigrateEvalIntAndDouble2ToTypeNumberFlexFormRector/Fixture/fixture.xml.inc
- tests/Rector/v12/v0/flexform/MigrateEvalIntAndDouble2ToTypeNumberFlexFormRector/MigrateEvalIntAndDouble2ToTypeNumberFlexFormRectorTest.php
- tests/Rector/v12/v0/flexform/MigrateEvalIntAndDouble2ToTypeNumberFlexFormRector/config/configured_rule.php
- tests/Rector/v12/v0/tca/MigrateEvalIntAndDouble2ToTypeNumberRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/tca/MigrateEvalIntAndDouble2ToTypeNumberRector/MigrateEvalIntAndDouble2ToTypeNumberRectorTest.php
- tests/Rector/v12/v0/tca/MigrateEvalIntAndDouble2ToTypeNumberRector/config/configured_rule.php
> [TASK] Add MigrateEvalIntAndDouble2ToTypeNumberRector

- src/Helper/TcaHelperTrait.php
- src/Rector/v12/v0/tca/MigrateToEmailTypeRector.php
- src/Rector/v12/v3/flexform/MigrateItemsToIndexedArrayKeysForFlexFormItemsRector.php
- tests/Rector/v12/v0/tca/MigrateToEmailTypeRector/Fixture/fixture.php.inc
Keep properties instead of throwing everything away
> [BUGFIX] Fix MigrateToEmailTypeRector

- composer.json
- config/v12/typo3-120.php
- src/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/Qom/AndInterface.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/Qom/OrInterface.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/Query.php
- stubs/TYPO3/CMS/Extbase/Persistence/QueryInterface.php
- tests/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector/Fixture/log_entry_repository.php.inc
- tests/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector/Fixture/query_logical_and_with_individual_arguments.php.inc
- tests/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector/Fixture/query_logical_and_with_one_individual_argument.php.inc
- tests/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector/Fixture/query_logical_and_with_variables_as_arguments.php.inc
- tests/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector/Fixture/query_logical_or.php.inc
- tests/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector/HardenMethodSignatureOfLogicalAndAndLogicalOrRectorTest.php
- tests/Rector/v12/v0/typo3/HardenMethodSignatureOfLogicalAndAndLogicalOrRector/config/configured_rule.php
> [TASK] Harden method signature of logicalAnd() and logicalOr()

- src/Rector/v12/v0/flexform/MigrateEvalIntAndDouble2ToTypeNumberFlexFormRector.php
- src/Rector/v12/v0/tca/MigrateEvalIntAndDouble2ToTypeNumberRector.php
- src/Rector/v12/v0/tca/MigrateToEmailTypeRector.php
- tests/Rector/v12/v0/tca/MigrateToEmailTypeRector/Fixture/fixture_keep_max_for_other_types.php.inc
> [BUGFIX] Keep max property for other input types

- config/v12/yaml-120.php
- src/Rector/v12/v0/yaml/RemoveElementTceFormsYamlRector.php
- tests/Rector/v12/v0/yaml/RemoveElementTceFormsYamlRector/Fixture/fixture.yaml.inc
- tests/Rector/v12/v0/yaml/RemoveElementTceFormsYamlRector/RemoveElementTceFormsYamlRectorTest.php
- tests/Rector/v12/v0/yaml/RemoveElementTceFormsYamlRector/config/configured_rule.php
> [FEATURE] Add RemoveElementTceFormsYamlRector

- config/v12/typoscript-124.php
- src/FileProcessor/TypoScript/Conditions/GlobalVarConditionMatcher.php
- src/Rector/v12/v4/typoscript/MigrateXhtmlDoctypeRector.php
- tests/Rector/v12/v4/typoscript/MigrateXhtmlDoctypeRector/Fixture/fixture.typoscript.inc
- tests/Rector/v12/v4/typoscript/MigrateXhtmlDoctypeRector/MigrateXhtmlDoctypeRectorTest.php
- tests/Rector/v12/v4/typoscript/MigrateXhtmlDoctypeRector/config/configured_rule.php
> [FEATURE] Provide migration for typoscript xhtmlDoctype config

- src/Rector/v11/v3/SubstituteMethodRmFromListOfGeneralUtilityRector.php
- tests/Rector/v11/v3/SubstituteMethodRmFromListOfGeneralUtilityRector/Fixture/remove_from_list_to_array_filter.php.inc
> [BUGFIX] Use arg as var name instead of fixed one

- config/v12/flexform-120.php
- config/v12/tca-120.php
- src/Rector/v12/v0/flexform/MigrateInternalTypeFolderToTypeFolderFlexFormRector.php
- src/Rector/v12/v0/tca/MigrateInternalTypeFolderToTypeFolderRector.php
- src/Rector/v12/v0/tca/MigrateToEmailTypeRector.php
- tests/Rector/v12/v0/flexform/MigrateInternalTypeFolderToTypeFolderFlexFormRector/Fixture/fixture.xml.inc
- tests/Rector/v12/v0/flexform/MigrateInternalTypeFolderToTypeFolderFlexFormRector/MigrateInternalTypeFolderToTypeFolderFlexFormRectorTest.php
- tests/Rector/v12/v0/flexform/MigrateInternalTypeFolderToTypeFolderFlexFormRector/config/configured_rule.php
> [FEATURE] MigrateInternalTypeFolderToTypeFolderFlexFormRector

- config/v12/flexform-120.php
- src/Rector/v12/v0/flexform/MigrateNullFlagFlexFormRector.php
- src/Rector/v12/v0/tca/MigrateNullFlagRector.php
- tests/Rector/v12/v0/flexform/MigrateNullFlagFlexFormRector/Fixture/fixture.xml.inc
- tests/Rector/v12/v0/flexform/MigrateNullFlagFlexFormRector/MigrateNullFlagFlexFormRectorTest.php
- tests/Rector/v12/v0/flexform/MigrateNullFlagFlexFormRector/config/configured_rule.php
> [FEATURE] MigrateNullFlagFlexFormRector

- config/v12/tca-120.php
- src/Rector/v12/v0/tca/MigratePasswordAndSaltedPasswordToPasswordTypeRector.php
- tests/Rector/v12/v0/tca/MigratePasswordAndSaltedPasswordToPasswordTypeRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/tca/MigratePasswordAndSaltedPasswordToPasswordTypeRector/MigratePasswordAndSaltedPasswordToPasswordTypeRectorTest.php
- tests/Rector/v12/v0/tca/MigratePasswordAndSaltedPasswordToPasswordTypeRector/config/configured_rule.php
> [FEATURE] MigratePasswordAndSaltedPasswordToPasswordTypeRector

- config/typo3-testingframework/typo3-testingframework-7.php
- docs/configuration_and_processing.md
- src/Helper/Database/Refactorings/ConnectionCallFactory.php
- src/Helper/OldSeverityToLogLevelMapper.php
- src/Set/Extension/TYPO3TestingFrameworkSetList.php
- templates/rector.php
- templates/rector.php.dist
> [FEATURE] Add TYPO3 TestingFramework 7 Migrations and sync template

- config/v12/flexform-120.php
- src/Helper/FlexFormHelperTrait.php
- src/Rector/v12/v0/flexform/MigrateRenderTypeColorpickerToTypeColorFlexFormRector.php
- src/Rector/v12/v0/tca/MigrateRenderTypeColorpickerToTypeColorRector.php
- tests/Rector/v12/v0/flexform/MigrateRenderTypeColorpickerToTypeColorFlexFormRector/Fixture/fixture.xml.inc
- tests/Rector/v12/v0/flexform/MigrateRenderTypeColorpickerToTypeColorFlexFormRector/MigrateRenderTypeColorpickerToTypeColorFlexFormRectorTest.php
- tests/Rector/v12/v0/flexform/MigrateRenderTypeColorpickerToTypeColorFlexFormRector/config/configured_rule.php
> [FEATURE] Add MigrateRenderTypeColorpickerToTypeColorFlexFormRector

- src/Rector/v11/v0/ForwardResponseInsteadOfForwardMethodRector.php
- src/Rector/v11/v5/SubstituteBackendTemplateViewWithModuleTemplateRector.php
- src/Rector/v12/v0/typo3/ContentObjectRegistrationViaServiceConfigurationRector.php
- src/Rector/v12/v0/typo3/RegisterExtbaseTypeConvertersAsServicesRector.php
- src/Rector/v12/v0/typo3/RemoveUpdateRootlineDataRector.php
> TASK: Do not use NodesToAddCollector

- config/v10/typo3-100.php
- config/v10/typo3-101.php
- config/v10/typo3-104.php
- config/v11/typo3-110.php
- config/v11/typo3-114.php
- config/v11/typo3-115.php
- config/v8/typo3-84.php
- src/Rector/v12/v3/flexform/MigrateItemsToIndexedArrayKeysForFlexFormItemsRector.php
- src/Rector/v8/v7/BackendUtilityGetRecordsByFieldToQueryBuilderRector.php
- tests/FileProcessor/TypoScript/config/configured_rule.php
- tests/Rector/v10/v4/SubstituteObjectManagerGetWithGeneralUtilityMakeInstanceRector/config/configured_rule.php
- tests/Rector/v12/v0/typo3/ReplaceExpressionBuilderMethodsRector/config/configured_rule.php
- tests/Rector/v12/v0/typo3/ReplaceTSFEWithContextMethodsRector/config/configured_rule.php
- tests/Rector/v9/v4/AdditionalFieldProviderRector/config/configured_rule.php
> [FEATURE] Associative array keys for TCA items

- config/v11/tca-110.php
- src/Rector/v11/v0/tca/RemoveWorkspacePlaceholderShadowColumnsConfigurationRector.php
- tests/Rector/v11/v0/tca/RemoveWorkspacePlaceholderShadowColumnsConfigurationRector/Fixture/fixture.php.inc
- tests/Rector/v11/v0/tca/RemoveWorkspacePlaceholderShadowColumnsConfigurationRector/RemoveWorkspacePlaceholderShadowColumnsConfigurationRectorTest.php
- tests/Rector/v11/v0/tca/RemoveWorkspacePlaceholderShadowColumnsConfigurationRector/config/configured_rule.php
Resolves: #1827
Resolves: #1829
Resolves: #3837
Resolves: #3852
> [FEATURE] Add RemoveWorkspacePlaceholderShadowColumnsConfigurationRector

- config/v10/typo3-100.php
- config/v10/typo3-101.php
- config/v10/typo3-104.php
- config/v11/typo3-110.php
- config/v11/typo3-114.php
- config/v11/typo3-115.php
- config/v8/typo3-84.php
- src/Rector/v10/v0/BackendUtilityGetViewDomainToPageRouterRector.php
- src/Rector/v8/v1/TypoScriptFrontendControllerCharsetConverterRector.php
- src/Rector/v8/v7/BackendUtilityGetRecordsByFieldToQueryBuilderRector.php
- tests/FileProcessor/TypoScript/config/configured_rule.php
- tests/Rector/v10/v0/BackendUtilityGetViewDomainToPageRouterRector/Fixture/backend_utility_get_view_domain.php.inc
- tests/Rector/v10/v4/SubstituteObjectManagerGetWithGeneralUtilityMakeInstanceRector/config/configured_rule.php
- tests/Rector/v12/v0/typo3/ReplaceExpressionBuilderMethodsRector/config/configured_rule.php
- tests/Rector/v12/v0/typo3/ReplaceTSFEWithContextMethodsRector/config/configured_rule.php
- tests/Rector/v9/v4/AdditionalFieldProviderRector/config/configured_rule.php
> TASK: Return nodes instead of using NodesToAddCollector

- src/Rector/v8/v5/ContentObjectRendererFileResourceRector.php
> TASK: Return nodes directly

- src/FileProcessor/TypoScript/Conditions/GlobalVarConditionMatcher.php
- src/Rector/v10/v0/ForceTemplateParsingInTsfeAndTemplateServiceRector.php
- src/Rector/v9/v4/RefactorDeprecatedConcatenateMethodsPageRendererRector.php
- tests/Rector/v9/v4/RefactorDeprecatedConcatenateMethodsPageRendererRector/Fixture/refactor_deprecated_concatenate_methods.php.inc
> TASK: Return nodes for RefactorDeprecatedConcatenateMethodsPageRendererRector

- src/Rector/v9/v4/TemplateGetFileNameToFilePathSanitizerRector.php
- tests/Rector/v9/v4/TemplateGetFileNameToFilePathSanitizerRector/Fixture/template_get_file_name_to_file_path_sanitizer.php.inc
> TASK: Return nodes TemplateGetFileNameToFilePathSanitizerRector

- src/Rector/v9/v4/UseGetMenuInsteadOfGetFirstWebPageRector.php
- tests/Rector/v9/v4/UseGetMenuInsteadOfGetFirstWebPageRector/Fixture/use_get_menu_instead_of_get_first_web_page.php.inc
- tests/Rector/v9/v4/UseGetMenuInsteadOfGetFirstWebPageRector/Fixture/use_get_menu_instead_of_get_first_web_page_tsfe.php.inc
> TASK: Return nodes UseGetMenuInsteadOfGetFirstWebPageRector

- src/Rector/v9/v3/CopyMethodGetPidForModTSconfigRector.php
- tests/Rector/v9/v3/CopyMethodGetPidForModTSconfigRector/Fixture/copy_method_get_pid_for_mod_tsconfig.php.inc
> TASK: Return nodes CopyMethodGetPidForModTSconfigRector

- src/Rector/v9/v2/PageNotFoundAndErrorHandlingRector.php
> TASK: Return node for PageNotFoundAndErrorHandlingRector

- src/Rector/v9/v4/UseClassSchemaInsteadReflectionServiceMethodsRector.php
- tests/Rector/v9/v4/UseClassSchemaInsteadReflectionServiceMethodsRector/Fixture/class.php.inc
- tests/Rector/v9/v4/UseClassSchemaInsteadReflectionServiceMethodsRector/Fixture/properties.php.inc
> TASK: Remove somecases from UseClassSchemaInsteadReflectionServiceMethodsRector

- src/Rector/v10/v1/SendNotifyEmailToMailApiRector.php
> TASK: Return nodes for SendNotifyEmailToMailApiRector

- src/Rector/v11/v5/FlexFormToolsArrayValueByPathRector.php
> TASK: Return nodes for FlexFormToolsArrayValueByPathRector

- composer.json
Also align the Symfony dependency versions with those of the TYPO3 Core.
> [FEATURE] Add support for Symfony 7

- src/Rector/v12/v0/tca/MigrateInputDateTimeRector.php
- tests/Rector/v12/v0/tca/MigrateInputDateTimeRector/Fixture/fixture.php.inc
> [FEATURE] Removed eval=int from TCA type "datetime"

- src/Rector/v10/v0/UseTwoLetterIsoCodeFromSiteLanguageRector.php
- tests/Rector/v10/v0/UseTwoLetterIsoCodeFromSiteLanguageRector/Fixture/use_two_letter_iso_code_from_site_language.php.inc
> [BUGFIX] Fix wrong conversion UseTwoLetterIsoCodeFromSiteLanguageRector

- config/v12/typo3-120.php
- rector.php
- rules/TYPO312/AnnotationToAttribute/ValidateAttributeDecorator.php
- rules/TYPO312/v0/ExtbaseAnnotationToAttributeRector.php
- rules/TYPO312/v0/MigrateContentObjectRendererLastTypoLinkPropertiesRector.php
- stubs/TYPO3/CMS/Frontend/ContentObject/ContentObjectRenderer.php
- stubs/TYPO3/CMS/Frontend/Typolink/LinkResultInterface.php
- tests/Rector/v12/v0/MigrateContentObjectRendererLastTypoLinkPropertiesRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/MigrateContentObjectRendererLastTypoLinkPropertiesRector/MigrateContentObjectRendererLastTypoLinkPropertiesRectorTest.php
- tests/Rector/v12/v0/MigrateContentObjectRendererLastTypoLinkPropertiesRector/config/configured_rule.php
- utils/generator/src/ValueObject/Typo3RectorRecipe.php
> [FEATURE] Add MigrateContentObjectRendererLastTypoLinkPropertiesRector

- config/v12/typo3-120.php
- rules/TYPO312/v0/MigrateContentObjectRendererLastTypoLinkPropertiesRector.php
- rules/TYPO312/v0/UsePageDoktypeRegistryRector.php
- stubs/TYPO3/CMS/Core/DataHandling/PageDoktypeRegistry.php
- tests/Rector/v12/v0/UsePageDoktypeRegistryRector/Fixture/ext_tables.php.inc
- tests/Rector/v12/v0/UsePageDoktypeRegistryRector/Fixture/ext_tables_array.php.inc
- tests/Rector/v12/v0/UsePageDoktypeRegistryRector/Source/PageTypeConstant.php
- tests/Rector/v12/v0/UsePageDoktypeRegistryRector/UsePageDoktypeRegistryRectorTest.php
- tests/Rector/v12/v0/UsePageDoktypeRegistryRector/config/configured_rule.php
> [FEATURE] Add UsePageDoktypeRegistryRector

- config/v12/typo3-124.php
- rules/TYPO312/v4/MigrateRecordTooltipMethodToRecordIconAltTextMethodRector.php
- stubs/TYPO3/CMS/Backend/Utility/BackendUtility.php
- tests/Rector/v12/v4/MigrateRecordTooltipMethodToRecordIconAltTextMethodRector/Fixture/fixture.php.inc
- tests/Rector/v12/v4/MigrateRecordTooltipMethodToRecordIconAltTextMethodRector/MigrateRecordTooltipMethodToRecordIconAltTextMethodRectorTest.php
- tests/Rector/v12/v4/MigrateRecordTooltipMethodToRecordIconAltTextMethodRector/Source/CustomBackendUtility.php
- tests/Rector/v12/v4/MigrateRecordTooltipMethodToRecordIconAltTextMethodRector/config/configured_rule.php
> [FEATURE] Add MigrateRecordTooltipMethodToRecordIconAltTextMethodRector

- config/v12/typo3-124.php
- rules/TYPO312/v4/MigrateRequestArgumentFromMethodStartRector.php
- stubs/TYPO3/CMS/Frontend/ContentObject/ContentObjectRenderer.php
- tests/Rector/v12/v4/MigrateRequestArgumentFromMethodStartRector/Fixture/fixture.php.inc
- tests/Rector/v12/v4/MigrateRequestArgumentFromMethodStartRector/MigrateRequestArgumentFromMethodStartRectorTest.php
- tests/Rector/v12/v4/MigrateRequestArgumentFromMethodStartRector/Source/MyServerRequest.php
- tests/Rector/v12/v4/MigrateRequestArgumentFromMethodStartRector/config/configured_rule.php
> [FEATURE] Add MigrateRequestArgumentFromMethodStartRector

- .github/workflows/code_analysis.yaml
- config/level/up-to-typo3-13.php
- config/typo3-13.php
- config/v13/typo3-130.php
- rules/TYPO312/v4/MigrateRequestArgumentFromMethodStartRector.php
- rules/TYPO313/v0/MigrateFileTypeConstantsToFileTypeEnumRector.php
- src/Set/Typo3SetList.php
- stubs/TYPO3/CMS/Core/Resource/AbstractFile.php
- stubs/TYPO3/CMS/Core/Resource/FileType.php
- tests/Rector/v12/v0/MigrateContentObjectRendererLastTypoLinkPropertiesRector/MigrateContentObjectRendererLastTypoLinkPropertiesRectorTest.php
- tests/Rector/v12/v0/UsePageDoktypeRegistryRector/UsePageDoktypeRegistryRectorTest.php
- tests/Rector/v12/v4/MigrateRequestArgumentFromMethodStartRector/MigrateRequestArgumentFromMethodStartRectorTest.php
- tests/Rector/v13/v0/MigrateFileTypeConstantsToFileTypeEnumRector/Fixture/abstract_file_types.php.inc
- tests/Rector/v13/v0/MigrateFileTypeConstantsToFileTypeEnumRector/MigrateFileTypeConstantsToFileTypeEnumRectorTest.php
- tests/Rector/v13/v0/MigrateFileTypeConstantsToFileTypeEnumRector/Source/MyOtherFileType.php
- tests/Rector/v13/v0/MigrateFileTypeConstantsToFileTypeEnumRector/config/configured_rule.php
- utils/generator/src/Command/Typo3GenerateCommand.php
- utils/generator/templates/tests/Rector/__MajorPrefixed__/__MinorPrefixed__/__Test_Directory__/__Name__Test.php.inc
> [FEATURE] Add MigrateFileTypeConstantsToFileTypeEnumRector

- config/v13/typo3-130.php
> [FEATURE] Move constants to enum

- config/v12/tca-120.php
- rules/TYPO312/v0/MigrateFileFieldTCAConfigToTCATypeFileRector.php
- tests/Rector/v12/v0/MigrateFileFieldTCAConfigToTCATypeFileRector/Fixture/tca.php.inc
- tests/Rector/v12/v0/MigrateFileFieldTCAConfigToTCATypeFileRector/MigrateFileFieldTCAConfigToTCATypeFileRectorTest.php
- tests/Rector/v12/v0/MigrateFileFieldTCAConfigToTCATypeFileRector/config/configured_rule.php
> [FEATURE] Add MigrateFileFieldTCAConfigToTCATypeFileRector

- config/v12/typo3-124.php
- rules/TYPO312/v4/CommandConfigurationToAnnotationRector.php
- src/Helper/SymfonyCommandHelper.php
- tests/Rector/v12/v4/CommandConfigurationToAnnotationRector/CommandConfigurationToAnnotationRectorTest.php
- tests/Rector/v12/v4/CommandConfigurationToAnnotationRector/Fixture/command.php.inc
- tests/Rector/v12/v4/CommandConfigurationToAnnotationRector/Fixture/command_with_default_name_and_description.php.inc
- tests/Rector/v12/v4/CommandConfigurationToAnnotationRector/Fixture/non_scheduable_command.php.inc
- tests/Rector/v12/v4/CommandConfigurationToAnnotationRector/config/configured_rule.php
- tests/Rector/v12/v4/CommandConfigurationToAnnotationRector/xml/services.xml
> [FEATURE] Add CommandConfigurationToAnnotationRector

- config/v13/typo3-130.php
- rules/General/Renaming/RenameAttributeRector.php
- rules/General/Renaming/ValueObject/RenameAttribute.php
- stubs/TYPO3/CMS/Backend/Attribute/AsController.php
- stubs/TYPO3/CMS/Backend/Attribute/Controller.php
- tests/Rector/General/Renaming/RenameAttributeRector/Fixture/attribute.php.inc
- tests/Rector/General/Renaming/RenameAttributeRector/RenameAttributeRectorTest.php
- tests/Rector/General/Renaming/RenameAttributeRector/config/configured_rule.php
- utils/generator/src/Command/Typo3GenerateCommand.php
> [FEATURE] Add RenameAttributeRector

- rules/TYPO312/v0/ExtbaseAnnotationToAttributeRector.php
- tests/Rector/v12/v0/typo3/ExtbaseAnnotationToAttributeRector/Fixture/fixture.php.inc
> [BUGFIX] Fix missing leading slash for attributes

- bin/typo3-rector.php
- config/v12/typo3-124.php
- config/v13/typo3-130.php
- rules/TYPO312/v4/CommandConfigurationToAttributeRector.php
- rules/TYPO313/v0/EventListenerConfigurationToAttributeRector.php
- src/Helper/ServiceDefinitionHelper.php
- stubs/TYPO3/CMS/Core/Attribute/AsEventListener.php
- tests/Rector/v12/v4/CommandConfigurationToAttributeRector/CommandConfigurationToAttributeRectorTest.php
- tests/Rector/v12/v4/CommandConfigurationToAttributeRector/Fixture/command.php.inc
- tests/Rector/v12/v4/CommandConfigurationToAttributeRector/Fixture/command_with_default_name_and_description.php.inc
- tests/Rector/v12/v4/CommandConfigurationToAttributeRector/Fixture/non_scheduable_command.php.inc
- tests/Rector/v12/v4/CommandConfigurationToAttributeRector/config/configured_rule.php
- tests/Rector/v12/v4/CommandConfigurationToAttributeRector/xml/services.xml
- tests/Rector/v13/v0/EventListenerConfigurationToAttributeRector/EventListenerConfigurationToAttributeRectorTest.php
- tests/Rector/v13/v0/EventListenerConfigurationToAttributeRector/Fixture/event_listener.php.inc
- tests/Rector/v13/v0/EventListenerConfigurationToAttributeRector/Fixture/event_listener_with_all_options.php.inc
- tests/Rector/v13/v0/EventListenerConfigurationToAttributeRector/Source/MySpecialEvent.php
- tests/Rector/v13/v0/EventListenerConfigurationToAttributeRector/config/configured_rule.php
- tests/Rector/v13/v0/EventListenerConfigurationToAttributeRector/xml/services.xml
> [FEATURE] Add AsEventListener attribute

- .github/workflows/code_analysis.yaml
- bin/typo3-rector.php
- config/config.php
- config/replace-vhs.php
- src/FileProcessor/Fluid/Rector/vhs/ReplaceExtensionPathRelativeFluidRector.php
- src/FileProcessor/Fluid/Rector/vhs/ReplaceOrFluidRector.php
- src/FileProcessor/Fluid/Rector/vhs/ReplaceVariableSetFluidRector.php
- tests/FileProcessor/Fluid/Rector/vhs/ReplaceFormatJsonEncodeFluidRector/config/configured_rule.php
- tests/FileProcessor/Fluid/Rector/vhs/ReplaceLFluidRector/config/configured_rule.php
- tests/FileProcessor/Fluid/Rector/vhs/ReplaceMediaImageFluidRector/config/configured_rule.php
- tests/FileProcessor/Fluid/Rector/vhs/ReplaceOrFluidRector/config/configured_rule.php
- tests/FileProcessor/Fluid/Rector/vhs/ReplaceUriImageFluidRector/config/configured_rule.php
- tests/FileProcessor/Fluid/Rector/vhs/ReplaceVariableSetFluidRector/config/configured_rule.php
- utils/generator/src/Command/Typo3GenerateCommand.php
Resolves: https://github.com/martin-helmich/typo3-typoscript-parser/issues/100
> TASK: Remove Traverser from DI container

- config/v13/typo3-130.php
- rules/TYPO313/v0/ChangeSignatureForLastInsertIdRector.php
- stubs/TYPO3/CMS/Core/Database/Connection.php
- tests/Rector/v13/v0/ChangeSignatureForLastInsertIdRector/ChangeSignatureForLastInsertIdRectorTest.php
- tests/Rector/v13/v0/ChangeSignatureForLastInsertIdRector/Fixture/lastInsertIdOnNonConnection.php.inc
- tests/Rector/v13/v0/ChangeSignatureForLastInsertIdRector/Fixture/lastInsertIdWithParameter.php.inc
- tests/Rector/v13/v0/ChangeSignatureForLastInsertIdRector/Fixture/lastInsertIdWithoutParameter.php.inc
- tests/Rector/v13/v0/ChangeSignatureForLastInsertIdRector/config/configured_rule.php
> [FEATURE] Add rule ChangeSignatureForLastInsertIdRector

- config/v10/tca-100.php
- rules/TYPO310/v0/RemoveShowRemovedLocalizationRecordsRector.php
- tests/Rector/v10/v0/RemoveShowRemovedLocalizationRecordsRector/Fixture/fixture.php.inc
- tests/Rector/v10/v0/RemoveShowRemovedLocalizationRecordsRector/RemoveShowRemovedLocalizationRecordsRectorTest.php
- tests/Rector/v10/v0/RemoveShowRemovedLocalizationRecordsRector/config/configured_rule.php
See also https://review.typo3.org/c/Packages/TYPO3.CMS/+/69665
resolves https://github.com/sabbelasichon/typo3-rector/issues/3939
> [FEATURE] Add TCA Rule: remove showRemovedLocalizationRecords from appearance config

- config/v13/typo3-130-extbase-hash-service-core-hash-service.php
- config/v13/typo3-130.php
- rules/TYPO313/v0/MigrateExtbaseHashServiceToUseCoreHashServiceRector.php
- stubs/TYPO3/CMS/Core/Crypto/HashService.php
- stubs/TYPO3/CMS/Core/Exception/Crypto/InvalidHashStringException.php
- stubs/TYPO3/CMS/Extbase/Security/Cryptography/HashService.php
- stubs/TYPO3/CMS/Extbase/Security/Exception/InvalidArgumentForHashGenerationException.php
- stubs/TYPO3/CMS/Extbase/Security/Exception/InvalidHashException.php
- tests/Rector/v13/v0/MigrateExtbaseHashServiceToUseCoreHashServiceRector/Fixture/change.php.inc
- tests/Rector/v13/v0/MigrateExtbaseHashServiceToUseCoreHashServiceRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/MigrateExtbaseHashServiceToUseCoreHashServiceRector/Fixture/in_class_context.php.inc
- tests/Rector/v13/v0/MigrateExtbaseHashServiceToUseCoreHashServiceRector/Fixture/no_change_required.php.inc
- tests/Rector/v13/v0/MigrateExtbaseHashServiceToUseCoreHashServiceRector/MigrateExtbaseHashServiceToUseCoreHashServiceRectorTest.php
- tests/Rector/v13/v0/MigrateExtbaseHashServiceToUseCoreHashServiceRector/config/configured_rule.php
> [FEATURE] Add MigrateExtbaseHashServiceToUseCoreHashServiceRector

- config/v11/tca-114.php
- rules/TYPO311/v4/MigrateRootUidToStartingPointsRector.php
- tests/Rector/v11/v4/MigrateRootUidToStartingPointsRector/Fixture/fixture.php.inc
- tests/Rector/v11/v4/MigrateRootUidToStartingPointsRector/MigrateRootUidToStartingPointsRectorTest.php
- tests/Rector/v11/v4/MigrateRootUidToStartingPointsRector/config/configured_rule.php
> [FEATURE] Add TCA Rule for rootUid related setting of trees

- config/v13/tca-130.php
- rules/TYPO313/v0/RemoveMmHasUidFieldRector.php
- tests/Rector/v13/v0/RemoveMmHasUidFieldRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/RemoveMmHasUidFieldRector/Fixture/fixture_overrides.php.inc
- tests/Rector/v13/v0/RemoveMmHasUidFieldRector/RemoveMmHasUidFieldRectorTest.php
- tests/Rector/v13/v0/RemoveMmHasUidFieldRector/config/configured_rule.php
> [FEATURE] Add TCA Rule: remove mm_hasUidField config

- config/v13/extbase-strict-types-persistence-manager.php
- config/v13/typo3-130.php
- rules/TYPO313/v0/StrictTypesPersistenceManagerRector.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/BackendInterface.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/ObjectStorage.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/PersistenceManager.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/QueryFactoryInterface.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/Session.php
- tests/Rector/v13/v0/StrictTypesPersistenceManagerRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/StrictTypesPersistenceManagerRector/StrictTypesPersistenceManagerRectorTest.php
- tests/Rector/v13/v0/StrictTypesPersistenceManagerRector/config/configured_rule.php
> Issue 4074 use strict type in extbase

- config/v11/typo3-113.php
- rules/TYPO311/v3/MigrateHttpUtilityRedirectRector.php
- rules/TYPO311/v4/MigrateRootUidToStartingPointsRector.php
- stubs/TYPO3/CMS/Core/Http/PropagateResponseException.php
- stubs/TYPO3/CMS/Core/Utility/HttpUtility.php
- tests/Rector/v11/v3/MigrateHttpUtilityRedirectRector/Fixture/RedirectCallWithOneParameters.php.inc
- tests/Rector/v11/v3/MigrateHttpUtilityRedirectRector/Fixture/RedirectCallWithTwoParameters.php.inc
- tests/Rector/v11/v3/MigrateHttpUtilityRedirectRector/Fixture/RedirectCallWithTwoParametersNotInHttpUtility.php.inc
- tests/Rector/v11/v3/MigrateHttpUtilityRedirectRector/MigrateHttpUtilityRedirectRectorTest.php
- tests/Rector/v11/v3/MigrateHttpUtilityRedirectRector/Source/Foo.php
- tests/Rector/v11/v3/MigrateHttpUtilityRedirectRector/config/configured_rule.php
> [FEATURE] Add MigrateHttpUtilityRedirectRector

- config/v13/extbase-strict-types.php
- rules/TYPO313/v0/UseStrictTypesInExtbaseAbstractDomainObjectRector.php
- tests/Rector/v13/v0/ResourceInterfaceStrictTypesRector/config/configured_rule.php
- tests/Rector/v13/v0/UseStrictTypesInExtbaseAbstractDomainObjectRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/UseStrictTypesInExtbaseAbstractDomainObjectRector/UseStrictTypesInExtbaseAbstractDomainObjectRectorTest.php
- tests/Rector/v13/v0/UseStrictTypesInExtbaseAbstractDomainObjectRector/config/configured_rule.php
> [FEATURE] Use strict type in extbase AbstractDomainObject

- config/v13/introduce-capabilities-bit-set.php
- config/v13/typo3-130.php
- rules/TYPO313/v0/IntroduceCapabilitiesBitSetRector.php
- stubs/TYPO3/CMS/Core/Resource/Capabilities.php
- stubs/TYPO3/CMS/Core/Resource/ResourceStorageInterface.php
- tests/Rector/v13/v0/IntroduceCapabilitiesBitSetRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/IntroduceCapabilitiesBitSetRector/IntroduceCapabilitiesBitSetRectorTest.php
- tests/Rector/v13/v0/IntroduceCapabilitiesBitSetRector/config/configured_rule.php
> [FEATURE] Introduce capabilities bit set

- config/v12/typo3-120.php
- config/v13/strict-types.php
- tests/Rector/v13/v0/FileInterfaceStrictTypesRector/config/configured_rule.php
- tests/Rector/v13/v0/ResourceInterfaceStrictTypesRector/config/configured_rule.php
> [FEATURE] Add PARAM_* from Connection class

- config/v12/typo3-124.php
- rules/TYPO312/v4/MigrateTypoScriptFrontendControllerTypeRector.php
- stubs/TYPO3/CMS/Core/Routing/PageArguments.php
- stubs/TYPO3/CMS/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v12/v4/MigrateTypoScriptFrontendControllerTypeRector/Fixture/fixture.php.inc
- tests/Rector/v12/v4/MigrateTypoScriptFrontendControllerTypeRector/MigrateTypoScriptFrontendControllerTypeRectorTest.php
- tests/Rector/v12/v4/MigrateTypoScriptFrontendControllerTypeRector/config/configured_rule.php
> [FEATURE] Add MigrateTypoScriptFrontendControllerTypeRector

- config/v13/strict-types.php
- rules/TYPO311/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector.php
- tests/Rector/v11/v0/ExtbaseControllerActionsMustReturnResponseInterfaceRector/Fixture/skip_extbase_controller_actions.php.inc
- tests/Rector/v13/v0/FileInterfaceStrictTypesRector/config/configured_rule.php
- tests/Rector/v13/v0/ResourceInterfaceStrictTypesRector/config/configured_rule.php
> [BUGFIX] Do not try to add ResponseInterface again

- config/v13/strict-types.php
- stubs/TYPO3/CMS/Core/Resource/Capabilities.php
- stubs/TYPO3/CMS/Core/Resource/Driver/DriverInterface.php
- tests/Rector/v13/v0/StrictTypesDriverInterfaceRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/StrictTypesDriverInterfaceRector/StrictTypesDriverInterfaceRector.php
- tests/Rector/v13/v0/StrictTypesDriverInterfaceRector/config/configured_rule.php
> [FEATURE] Add strict types for DriverInterface

- config/v13/strict-types.php
- stubs/TYPO3/CMS/Core/Resource/FolderInterface.php
- tests/Rector/v13/v0/StrictTypesFolderInterfaceRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/StrictTypesFolderInterfaceRector/StrictTypesFolderInterfaceRector.php
- tests/Rector/v13/v0/StrictTypesFolderInterfaceRector/config/configured_rule.php
> [FEATURE] Add strict types for FolderInterface

- config/v12/typo3-124.php
- rules/TYPO312/v4/UseServerRequestInsteadOfGeneralUtilityGetRector.php
- stubs/TYPO3/CMS/Core/Utility/GeneralUtility.php
- stubs/TYPO3/CMS/Extbase/Mvc/Request.php
- tests/Rector/v12/v4/UseServerRequestInsteadOfGeneralUtilityGetRector/Fixture/action_controller_context.php.inc
- tests/Rector/v12/v4/UseServerRequestInsteadOfGeneralUtilityGetRector/Fixture/standalone_class.php.inc
- tests/Rector/v12/v4/UseServerRequestInsteadOfGeneralUtilityGetRector/UseServerRequestInsteadOfGeneralUtilityGetRectorTest.php
- tests/Rector/v12/v4/UseServerRequestInsteadOfGeneralUtilityGetRector/config/configured_rule.php
> [FEATURE] Use PSR-7 instead of GeneralUtility::_GET  

- config/v12/typo3-120.php
- rules/TYPO312/v0/UseServerRequestInsteadOfGeneralUtilityPostRector.php
- src/NodeFactory/GeneralUtilitySuperGlobalsToPsr7ServerRequestFactory.php
- stubs/TYPO3/CMS/Core/Utility/GeneralUtility.php
- stubs/TYPO3/CMS/Extbase/Mvc/Request.php
- tests/Rector/v12/v0/UseServerRequestInsteadOfGeneralUtilityPostRector/Fixture/action_controller_context.php.inc
- tests/Rector/v12/v0/UseServerRequestInsteadOfGeneralUtilityPostRector/Fixture/standalone_class.php.inc
- tests/Rector/v12/v0/UseServerRequestInsteadOfGeneralUtilityPostRector/UseServerRequestInsteadOfGeneralUtilityPostRectorTest.php
- tests/Rector/v12/v0/UseServerRequestInsteadOfGeneralUtilityPostRector/config/configured_rule.php
> [FEATURE] Use PSR-7 instead of GeneralUtility::_POST

- config/v12/typo3-121.php
- rules/TYPO312/v1/TemplateServiceToServerRequestFrontendTypoScriptAttributeRector.php
- stubs/TYPO3/CMS/Core/TypoScript/TemplateService.php
- tests/Rector/v12/v1/TemplateServiceToServerRequestFrontendTypoScriptAttributeRector/Fixture/fixture.php.inc
- tests/Rector/v12/v1/TemplateServiceToServerRequestFrontendTypoScriptAttributeRector/Fixture/in_class_context.php.inc
- tests/Rector/v12/v1/TemplateServiceToServerRequestFrontendTypoScriptAttributeRector/Fixture/in_extbase_action_controller_class_context.php.inc
- tests/Rector/v12/v1/TemplateServiceToServerRequestFrontendTypoScriptAttributeRector/TemplateServiceToServerRequestFrontendTypoScriptAttributeRectorTest.php
- tests/Rector/v12/v1/TemplateServiceToServerRequestFrontendTypoScriptAttributeRector/config/configured_rule.php
> [FEATURE] Use PSR-7 frontend.typoscript attribute

- config/v10/use-constants-from-typo3-database-connection.php
- config/v12/typo3-120.php
- rules/TYPO310/v0/UseConstantsFromTYPO3DatabaseConnection.php
- stubs/TYPO3/CMS/Core/Database/Connection.php
- tests/Rector/v10/v0/UseConstantsFromTYPO3DatabaseConnection/Fixture/fixture.php.inc
- tests/Rector/v10/v0/UseConstantsFromTYPO3DatabaseConnection/UseConstantsFromTYPO3DatabaseConnectionTest.php
- tests/Rector/v10/v0/UseConstantsFromTYPO3DatabaseConnection/config/configured_rule.php
> [FEATURE] Use Constants from TYPO3 Database Connection

- composer.json
> [BUGFIX] Remove typo3-rector from composer binaries

- README.md
- docs/README.md
- docs/best_practice_guide.md
- docs/configuration_and_processing.md
- docs/contribution.md
- docs/examples_in_action.md
- docs/installation.md
- docs/limitations.md
> [TASK] Improve documentation

- rules/TYPO312/v3/MigrateGeneralUtilityGPRector.php
- stubs/TYPO3/CMS/Core/Utility/GeneralUtility.php
- tests/Rector/v12/v3/MigrateGeneralUtilityGPRector/Fixture/action_controller_context.php.inc
- tests/Rector/v12/v3/MigrateGeneralUtilityGPRector/Fixture/standalone_class.php.inc
- tests/Rector/v12/v3/MigrateGeneralUtilityGPRector/MigrateGeneralUtilityGPRectorTest.php
- tests/Rector/v12/v3/MigrateGeneralUtilityGPRector/config/configured_rule.php
> [FEATURE] Add MigrateGeneralUtilityGPRector

- config/v13/typo3-130.php
- templates/rector.php
> [BUGFIX] Fix correct imports

- config/v12/typo3-124.php
- rules/TYPO312/v4/MigrateConfigurationManagerGetContentObjectRector.php
- stubs/TYPO3/CMS/Extbase/Configuration/ConfigurationManagerInterface.php
- stubs/TYPO3/CMS/Extbase/Mvc/Controller/ActionController.php
- tests/Rector/v12/v4/MigrateConfigurationManagerGetContentObjectRector/Fixture/fixture.php.inc
- tests/Rector/v12/v4/MigrateConfigurationManagerGetContentObjectRector/MigrateConfigurationManagerGetContentObjectRectorTest.php
- tests/Rector/v12/v4/MigrateConfigurationManagerGetContentObjectRector/config/configured_rule.php
> [FEATURE] Add MigrateConfigurationManagerGetContentObjectRector

- config/v13/typo3-130.php
- rules/TYPO313/v0/SubstituteItemFormElIDRector.php
- stubs/TYPO3/CMS/Backend/Form/NodeInterface.php
- stubs/TYPO3/CMS/Core/Utility/StringUtility.php
- tests/Rector/v13/v0/SubstituteItemFormElIDRector/Fixture/my_custom_form_element.php.inc
- tests/Rector/v13/v0/SubstituteItemFormElIDRector/Fixture/my_other_form_element.php.inc
- tests/Rector/v13/v0/SubstituteItemFormElIDRector/SubstituteItemFormElIDRectorTest.php
- tests/Rector/v13/v0/SubstituteItemFormElIDRector/config/configured_rule.php
> [FEATURE] Add SubstituteItemFormElIDRector

- config/v12/typo3-122.php
- rules/TYPO312/v2/MigrateGeneralUtilityGPMergedRector.php
- stubs/TYPO3/CMS/Core/Utility/GeneralUtility.php
- tests/Rector/v12/v2/MigrateGeneralUtilityGPMergedRector/Fixture/action_controller_context.php.inc
- tests/Rector/v12/v2/MigrateGeneralUtilityGPMergedRector/Fixture/standalone_class.php.inc
- tests/Rector/v12/v2/MigrateGeneralUtilityGPMergedRector/MigrateGeneralUtilityGPMergedRectorTest.php
- tests/Rector/v12/v2/MigrateGeneralUtilityGPMergedRector/config/configured_rule.php
> [FEATURE] Add MigrateGeneralUtilityGPMergedRector

- bin/generate-rule
- utils/generator/src/Command/Typo3GenerateCommand.php
- utils/generator/src/Contract/Typo3RectorTypeInterface.php
- utils/generator/src/FileSystem/ConfigFilesystem.php
- utils/generator/src/ValueObject/TcaRectorType.php
- utils/generator/src/ValueObject/Typo3RectorRecipe.php
- utils/generator/src/ValueObject/Typo3RectorType.php
- utils/generator/templates/rules/TYPO3__Major__/__MinorPrefixed__/__Name__.php
- Add alias bin script
- add option to skip changelog
- generate basic body template for rector rules which has been removed before for the 2.0 release
> [TASK] Improve rector rule generator

- composer.json
- config/v12/typo3-120.php
- rules/TYPO311/v2/SubstituteEnvironmentServiceWithApplicationTypeRector.php
- rules/TYPO312/v0/MigrateFetchColumnToFetchOneRector.php
- stubs/Doctrine/DBAL/Abstraction/Result.php
- stubs/Doctrine/DBAL/Driver/PDOStatement.php
- stubs/Doctrine/DBAL/Driver/Result.php
- stubs/Doctrine/DBAL/Result.php
- stubs/TYPO3/CMS/Core/Database/Driver/PDOStatement.php
- stubs/TYPO3/CMS/Core/Database/Driver/Statement.php
- stubs/TYPO3/CMS/Core/Database/Query/QueryBuilder.php
- tests/Rector/v12/v0/MigrateFetchColumnToFetchOneRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/MigrateFetchColumnToFetchOneRector/MigrateFetchColumnToFetchOneRectorTest.php
- tests/Rector/v12/v0/MigrateFetchColumnToFetchOneRector/config/configured_rule.php
> [FEATURE] Add MigrateFetchColumnToFetchOneRector

- rules/TYPO312/v0/UseServerRequestInsteadOfGeneralUtilityPostRector.php
- rules/TYPO312/v4/UseServerRequestInsteadOfGeneralUtilityGetRector.php
- src/NodeFactory/GeneralUtilitySuperGlobalsToPsr7ServerRequestFactory.php
- stubs/TYPO3/CMS/Core/Utility/GeneralUtility.php
- tests/Rector/v12/v0/UseServerRequestInsteadOfGeneralUtilityPostRector/Fixture/action_controller_context.php.inc
- tests/Rector/v12/v0/UseServerRequestInsteadOfGeneralUtilityPostRector/Fixture/consider_existing_coalesce_cases.php.inc
- tests/Rector/v12/v4/UseServerRequestInsteadOfGeneralUtilityGetRector/Fixture/action_controller_context.php.inc
- tests/Rector/v12/v4/UseServerRequestInsteadOfGeneralUtilityGetRector/Fixture/consider_existing_coalesce_cases.php.inc
> [BUGFIX] Consider existing coalesce for _GET and _POST

- config/v13/typo3-130.php
- rules/TYPO313/v0/MigrateAddUserTSConfigToUserTsConfigFileRector.php
- src/ComposerExtensionKeyResolver.php
- src/Contract/FilesystemInterface.php
- src/Filesystem/FlysystemFilesystem.php
- src/Helper/ExtensionKeyResolverTrait.php
- stubs/TYPO3/CMS/Core/Utility/ExtensionManagementUtility.php
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/extension1/Configuration/page.tsconfig
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/extension1/page.tsconfig
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/extension2/Configuration/page.tsconfig
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/extension2/page.tsconfig
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/extension3/Configuration/page.tsconfig
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/extension3/page.tsconfig
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Fixture/extension1/ext_localconf.php.inc
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Fixture/extension2/ext_localconf.php.inc
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Fixture/extension3/ext_localconf.php.inc
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/MigrateAddPageTSConfigToPageTsConfigFileRectorTest.php
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/Assertions/extension1/Configuration/user.tsconfig
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/Assertions/extension2/Configuration/user.tsconfig
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/Assertions/extension3/Configuration/user.tsconfig
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/Fixture/extension1/ext_localconf.php.inc
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/Fixture/extension2/ext_localconf.php.inc
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/Fixture/extension3/ext_localconf.php.inc
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/MigrateAddUserTSConfigToUserTsConfigFileRectorTest.php
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/config/configured_rule.php
> [TASK] Add MigrateAddUserTSConfigToUserTsConfigFileRector

- config/code-quality.php
- rules/CodeQuality/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector.php
- rules/TYPO313/v0/MigrateAddPageTSConfigToPageTsConfigFileRector.php
- src/Helper/ExtensionKeyResolverTrait.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/Assertions/extension1/Configuration/TCA/Overrides/sys_template.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/Assertions/extension2/Configuration/TCA/Overrides/sys_template.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/Assertions/extension3/Configuration/TCA/Overrides/sys_template.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/Fixture/extension1/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/Fixture/extension2/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/Fixture/extension3/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRectorTest.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/config/configured_rule.php
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/extension2/Configuration/page.tsconfig
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/MigrateAddPageTSConfigToPageTsConfigFileRectorTest.php
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/Assertions/extension2/Configuration/user.tsconfig
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/MigrateAddUserTSConfigToUserTsConfigFileRectorTest.php
> [TASK] Add MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector

- config/code-quality.php
- rules/CodeQuality/General/MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRector.php
- rules/TYPO312/v0/MoveAllowTableOnStandardPagesToTCAConfigurationRector.php
- stubs/TYPO3/CMS/Core/Utility/ExtensionManagementUtility.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/Fixture/extension1/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/Fixture/extension2/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddStaticFileIntoTCAOverridesRector/Fixture/extension3/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRector/Assertions/extension1/Configuration/TCA/Overrides/tt_content.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRector/Assertions/extension2/Configuration/TCA/Overrides/tt_content.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRector/Assertions/extension3/Configuration/TCA/Overrides/tt_content.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRector/Fixture/extension1/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRector/Fixture/extension2/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRector/Fixture/extension3/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRector/MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRectorTest.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRector/config/configured_rule.php
> [FEATURE] Add MoveExtensionManagementUtilityAddToAllTCAtypesIntoTCAOverridesRector

- config/code-quality.php
- rules/CodeQuality/General/MoveExtensionUtilityRegisterPluginIntoTCAOverridesRector.php
- stubs/TYPO3/CMS/Extbase/Utility/ExtensionUtility.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionUtilityRegisterPluginIntoTCAOverridesRector/Assertions/extension1/Configuration/TCA/Overrides/tt_content.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionUtilityRegisterPluginIntoTCAOverridesRector/Assertions/extension2/Configuration/TCA/Overrides/tt_content.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionUtilityRegisterPluginIntoTCAOverridesRector/Assertions/extension3/Configuration/TCA/Overrides/tt_content.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionUtilityRegisterPluginIntoTCAOverridesRector/Fixture/extension1/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionUtilityRegisterPluginIntoTCAOverridesRector/Fixture/extension2/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionUtilityRegisterPluginIntoTCAOverridesRector/Fixture/extension3/ext_tables.php.inc
- tests/Rector/CodeQuality/Rector/General/MoveExtensionUtilityRegisterPluginIntoTCAOverridesRector/MoveExtensionUtilityRegisterPluginIntoTCAOverridesRectorTest.php
- tests/Rector/CodeQuality/Rector/General/MoveExtensionUtilityRegisterPluginIntoTCAOverridesRector/config/configured_rule.php
> [FEATURE] Add MoveExtensionUtilityRegisterPluginIntoTCAOverridesRector

- config/v12/tca-120.php
- rules/TYPO312/v0/RemoveObsoleteAppearanceConfigRector.php
- tests/Rector/v12/v0/RemoveObsoleteAppearanceConfigRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/RemoveObsoleteAppearanceConfigRector/RemoveObsoleteAppearanceConfigRectorTest.php
- tests/Rector/v12/v0/RemoveObsoleteAppearanceConfigRector/config/configured_rule.php
> [FEATURE] Remove obsolete appearance config in group/inline TCA

- config/v12/typo3-120.php
- rules/TYPO312/v0/MigrateFetchAllToFetchAllAssociativeRector.php
- stubs/Doctrine/DBAL/Driver/Result.php
- tests/Rector/v12/v0/MigrateFetchAllToFetchAllAssociativeRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/MigrateFetchAllToFetchAllAssociativeRector/MigrateFetchAllToFetchAllAssociativeRectorTest.php
- tests/Rector/v12/v0/MigrateFetchAllToFetchAllAssociativeRector/config/configured_rule.php
> [FEATURE] Add MigrateFetchAllToFetchAllAssociativeRector

- .github/workflows/code_analysis.yaml
- config/v12/typo3-120.php
- rector.php
- rules/TYPO312/v0/MigrateFetchToFetchAssociativeRector.php
- stubs/Doctrine/DBAL/Driver/Result.php
- stubs/Doctrine/DBAL/FetchMode.php
- tests/Rector/v12/v0/MigrateFetchToFetchAssociativeRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/MigrateFetchToFetchAssociativeRector/MigrateFetchToFetchAssociativeRectorTest.php
- tests/Rector/v12/v0/MigrateFetchToFetchAssociativeRector/config/configured_rule.php
> [FEATURE] Add MigrateFetchToFetchAssociativeRector

- composer.json
> [BUGFIX] Rector is currently not fully compatible with phpstan >= 1.11.0

- config/typo3-13.php
- config/v13/typo3-131.php
- rules/TYPO313/v1/MigrateGeneralUtilityHmacToHashServiceHmacRector.php
- stubs/TYPO3/CMS/Core/Crypto/HashService.php
- stubs/TYPO3/CMS/Core/Utility/GeneralUtility.php
- tests/Rector/v13/v1/MigrateGeneralUtilityHmacToHashServiceHmacRector/Fixture/fixture.php.inc
- tests/Rector/v13/v1/MigrateGeneralUtilityHmacToHashServiceHmacRector/MigrateGeneralUtilityHmacToHashServiceHmacRectorTest.php
- tests/Rector/v13/v1/MigrateGeneralUtilityHmacToHashServiceHmacRector/config/configured_rule.php
> [FEATURE] Add MigrateGeneralUtilityHmacToHashServiceHmacRector

- config/v10/typo3-100.php
- config/v13/strict-types.php
- rules/TYPO312/v4/MigrateRecordTooltipMethodToRecordIconAltTextMethodRector.php
@simonschaufi here to fix PHPStan 1.11 Internal error
> PHPStan 1.11 TypeCombinator invalid usage on Rector config fix

- config/v13/typo3-130.php
- phpunit.xml.dist
- rules/TYPO312/v0/MoveAllowTableOnStandardPagesToTCAConfigurationRector.php
- rules/TYPO313/v0/MigrateExpressionBuilderTrimMethodSecondParameterRector.php
- stubs/Doctrine/DBAL/Platforms/TrimMode.php
- stubs/TYPO3/CMS/Core/Database/Connection.php
- stubs/TYPO3/CMS/Core/Database/Query/Expression/ExpressionBuilder.php
- tests/Rector/General/Renaming/RenameAttributeRector/config/configured_rule.php
- tests/Rector/v13/v0/MigrateExpressionBuilderTrimMethodSecondParameterRector/Fixture/fixture.php
- tests/Rector/v13/v0/MigrateExpressionBuilderTrimMethodSecondParameterRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/MigrateExpressionBuilderTrimMethodSecondParameterRector/MigrateExpressionBuilderTrimMethodSecondParameterRectorTest.php
- tests/Rector/v13/v0/MigrateExpressionBuilderTrimMethodSecondParameterRector/config/configured_rule.php
> [FEATURE] Add MigrateExpressionBuilderTrimMethodSecondParameterRector

- rules/TYPO311/v0/SubstituteConstantsModeAndRequestTypeRector.php
- tests/Rector/v11/v0/SubstituteConstantsModeAndRequestTypeRector/Fixture/application_type.php.inc
> [BUGFIX] Add missing negate operator

- composer.json
- config/config.php
- rules/TYPO312/v0/RemoveUpdateRootlineDataRector.php
- rules/TYPO312/v0/ReplaceContentObjectRendererGetMailToWithEmailLinkBuilderRector.php
- rules/TYPO312/v0/ReplacePageRepoOverlayFunctionRector.php
- rules/TYPO312/v0/UseCompositeExpressionStaticMethodsRector.php
- rules/TYPO312/v3/MigrateMagicRepositoryMethodsRector.php
- rules/TYPO313/v0/MigrateExtbaseHashServiceToUseCoreHashServiceRector.php
> [TASK] Support Flysystem version 3

- rules/TYPO312/AnnotationToAttribute/IgnoreValidationAttributeDecorator.php
- tests/Rector/v12/v0/typo3/ExtbaseAnnotationToAttributeRector/Fixture/fixture.php.inc
> [BUGFIX] Set correct IgnoreValidation attribute key

- rules/TYPO311/v5/SimplifyCheckboxItemsTCARector.php
- tests/Rector/v11/v5/SimplifyCheckboxItemsTCARector/Fixture/bug_4298.php.inc
> [BUGFIX] Add numbered key if missing for SimplifyCheckboxItemsTCARector

- phpstan-baseline.neon
Upgrading to PHPStan 2.x is a different thing
> TASK: Ignore current PHPStan errors.

- config/v12/typo3-120.php
- rules/TYPO312/v0/ExtbaseActionsWithRedirectMustReturnResponseInterfaceRector.php
- tests/Rector/v12/v0/ExtbaseActionsWithRedirectMustReturnResponseInterfaceRector/ExtbaseActionsWithRedirectMustReturnResponseInterfaceRectorTest.php
- tests/Rector/v12/v0/ExtbaseActionsWithRedirectMustReturnResponseInterfaceRector/Fixture/extbase_controller_actions_return_response_interface.php.inc
- tests/Rector/v12/v0/ExtbaseActionsWithRedirectMustReturnResponseInterfaceRector/config/configured_rule.php
Resolves: #2863 
Resolves: #4393
> [FEATURE] Add ExtbaseActionsWithRedirectMustReturnResponseInterfaceRector

- rules/TYPO312/v0/UseServerRequestInsteadOfGeneralUtilityPostRector.php
- rules/TYPO312/v4/UseServerRequestInsteadOfGeneralUtilityGetRector.php
- tests/Rector/v12/v0/UseServerRequestInsteadOfGeneralUtilityPostRector/Fixture/action_controller_context.php.inc
- tests/Rector/v12/v0/UseServerRequestInsteadOfGeneralUtilityPostRector/Fixture/standalone_class.php.inc
- tests/Rector/v12/v4/UseServerRequestInsteadOfGeneralUtilityGetRector/Fixture/action_controller_context.php.inc
- tests/Rector/v12/v4/UseServerRequestInsteadOfGeneralUtilityGetRector/Fixture/standalone_class.php.inc
> [BUGFIX] Avoid notices and use null coalesce

- config/typo3-13.php
- config/v13/typo3-134.php
- rector.php
- rules/TYPO313/v4/MigratePluginContentElementAndPluginSubtypesRector.php
- src/ComposerPsr4Resolver.php
- src/Filesystem/FilesFinder.php
- stubs/TYPO3/CMS/Core/Utility/ExtensionManagementUtility.php
- stubs/TYPO3/CMS/Install/Classes/Attribute/UpgradeWizard.php
- stubs/TYPO3/CMS/Install/Updates/AbstractListTypeToCTypeUpdate.php
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesRector/Assertions/extension1/Classes/Updates/TYPO3RectorCTypeMigration.php
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesRector/Fixture/extension1/Configuration/TCA/Overrides/tt_content.php.inc
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesRector/Fixture/extension1/ext_localconf.php.inc
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesRector/MigratePluginContentElementAndPluginSubtypesRectorTest.php
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesRector/config/configured_rule.php
> [FEATURE] Add MigratePluginContentElementAndPluginSubtypesRector

- config/v13/typo3-134.php
- docs/all_rectors_overview.md
- rules/TYPO313/v4/MigratePluginContentElementAndPluginSubtypesTCARector.php
- rules/TYPO313/v4/RemoveTcaSubTypesExcludeListTCARector.php
- src/Rector/AbstractArrayDimFetchTcaRector.php
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesTCARector/Fixture/fixture.php.inc
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesTCARector/MigratePluginContentElementAndPluginSubtypesTCARectorTest.php
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesTCARector/config/configured_rule.php
- tests/Rector/v13/v4/RemoveTcaSubTypesExcludeListTCARector/Fixture/fixture.php.inc
- tests/Rector/v13/v4/RemoveTcaSubTypesExcludeListTCARector/RemoveTcaSubTypesExcludeListTCARectorTest.php
- tests/Rector/v13/v4/RemoveTcaSubTypesExcludeListTCARector/config/configured_rule.php
- utils/phpstan/src/Rules/AddChangelogDocBlockForRectorClassRule.php
> [FEATURE] Add MigratePluginContentElementAndPluginSubtypesTCARector

- config/v13/typo3-134.php
- rules/TYPO313/v4/MigratePluginContentElementAndPluginSubtypesSwapArgsRector.php
- stubs/TYPO3/CMS/Core/Utility/ExtensionManagementUtility.php
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesSwapArgsRector/Fixture/fixture.php.inc
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesSwapArgsRector/MigratePluginContentElementAndPluginSubtypesSwapArgsRectorTest.php
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesSwapArgsRector/config/configured_rule.php
> [FEATURE] Add MigratePluginContentElementAndPluginSubtypesSwapArgsRector

- rules/General/Renaming/ConstantsToBackedEnumValueRector.php
- stubs/TYPO3/CMS/Core/Imaging/Icon.php
- stubs/TYPO3/CMS/Core/Imaging/IconSize.php
- tests/Rector/General/Renaming/ConstantsToBackedEnumValueRector/Fixture/abstract_file_types.php.inc
- tests/Rector/General/Renaming/ConstantsToBackedEnumValueRector/config/configured_rule.php
> [BUGFIX] Fix ConstantsToBackedEnumValueRector

- rules/CodeQuality/General/InjectMethodToConstructorInjectionRector.php
- tests/Rector/CodeQuality/General/InjectMethodToConstructorInjectionRector/Fixture/inject_if_possible_different_variable_name.php.inc
> [BUGFIX] Check if property and param names match and rename if not

- rules/TYPO312/v0/MigrateBackendModuleRegistrationRector.php
- tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Assertions/extension_empty_access/Configuration/Backend/Modules.php
- tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/Fixture/extension_empty_access/ext_tables.php.inc
- tests/Rector/v12/v0/MigrateBackendModuleRegistrationRector/MigrateBackendModuleRegistrationRectorTest.php
Resolves: #4462
Releases: 3, 2
> [BUGFIX] Fix empty access

- rules/TYPO312/v0/UseServerRequestInsteadOfGeneralUtilityPostRector.php
- rules/TYPO312/v4/UseServerRequestInsteadOfGeneralUtilityGetRector.php
- tests/Rector/v12/v0/UseServerRequestInsteadOfGeneralUtilityPostRector/Fixture/action_controller_context.php.inc
- tests/Rector/v12/v4/UseServerRequestInsteadOfGeneralUtilityGetRector/Fixture/action_controller_context.php.inc
Resolves: #4461
Releases: 3, 2
> [BUGFIX] Add check if rule must be skipped

- rules/TYPO312/v0/MigrateRequiredFlagSiteConfigRector.php
- src/Helper/TcaHelperTrait.php
- src/Rector/AbstractArrayDimFetchTcaRector.php
- src/Rector/AbstractTcaRector.php
- tests/Rector/v12/v0/MigrateRequiredFlagSiteConfigRector/Fixture/site.php.inc
- tests/Rector/v12/v0/MigrateRequiredFlagSiteConfigRector/MigrateRequiredFlagSiteConfigRectorTest.php
- tests/Rector/v12/v0/MigrateRequiredFlagSiteConfigRector/config/configured_rule.php
Resolves: #2944
Releases: 3, 2
> [FEATURE] Add MigrateRequiredFlagSiteConfigRector

- rules/TYPO312/v0/MoveAllowTableOnStandardPagesToTCAConfigurationRector.php
> [BUGFIX] Trim table name in MoveAllowTableOnStandardPagesToTCAConfigurationRector

- config/typo3-10.php
- config/typo3-12.php
> [BUGFIX] Import missing config files

- config/v13/typo3-130.php
- rules/General/Renaming/ConstantsToBackedEnumRector.php
- stubs/TYPO3/CMS/Core/Authentication/LoginType.php
- stubs/TYPO3/CMS/Core/Resource/AbstractFile.php
- stubs/TYPO3/CMS/Core/Type/Enumeration.php
- tests/Rector/General/Renaming/ConstantsToBackedEnumRector/ConstantsToBackedEnumRectorTest.php
- tests/Rector/General/Renaming/ConstantsToBackedEnumRector/Fixture/icon_types.php.inc
- tests/Rector/General/Renaming/ConstantsToBackedEnumRector/Source/MyOtherFileType.php
- tests/Rector/General/Renaming/ConstantsToBackedEnumRector/config/configured_rule.php
- tests/Rector/General/Renaming/ConstantsToBackedEnumValueRector/Fixture/abstract_file_types.php.inc
- tests/Rector/General/Renaming/ConstantsToBackedEnumValueRector/Fixture/login_types.php.broken
- tests/Rector/General/Renaming/ConstantsToBackedEnumValueRector/config/configured_rule.php
> [BUGFIX] Split migration to enums and enum values

- config/v12/typo3-120.php
- rules/TYPO312/v0/MigrateGetControllerContextGetUriBuilderRector.php
- tests/Rector/v12/v0/MigrateGetControllerContextGetUriBuilderRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/MigrateGetControllerContextGetUriBuilderRector/MigrateGetControllerContextGetUriBuilderRectorTest.php
- tests/Rector/v12/v0/MigrateGetControllerContextGetUriBuilderRector/config/configured_rule.php
> [FEATURE] Add MigrateGetControllerContextGetUriBuilderRector

- README.md
.. so that people don't have to dig out https://github.com/sabbelasichon/typo3-rector/issues/3179#issuecomment-2661377905
> [DOCS] Mention fractor in README

- rules/TYPO312/v0/ChangeExtbaseValidatorsRector.php
- rules/TYPO312/v1/TemplateServiceToServerRequestFrontendTypoScriptAttributeRector.php
- rules/TYPO313/v0/SubstituteItemFormElIDRector.php
- rules/TypeDeclaration/Property/AddPropertyTypeDeclarationWithDefaultNullRector.php
- src/NodeFactory/GeneralUtilitySuperGlobalsToPsr7ServerRequestFactory.php
- utils/phpstan/src/Rules/AddChangelogDocBlockForRectorClassRule.php
See https://github.com/phpstan/phpstan/discussions/12706
> [BUGFIX] Use `is` instead of `isSubclassOf` of class reflection

- rules/TYPO313/v1/RenamePageTreeNavigationComponentIdRector.php
- tests/Rector/v13/v1/RenamePageTreeNavigationComponentIdRector/Fixture/extension1/Configuration/Backend/Modules.php.inc
- tests/Rector/v13/v1/RenamePageTreeNavigationComponentIdRector/RenamePageTreeNavigationComponentIdRectorTest.php
- tests/Rector/v13/v1/RenamePageTreeNavigationComponentIdRector/config/configured_rule.php
> [FEATURE] Add RenamePageTreeNavigationComponentIdRector

- config/typo3-13.php
- config/v13/typo3-132.php
- rules/TYPO313/v2/MigrateRegularExpressionValidatorValidatorOptionErrorMessageRector.php
- stubs/TYPO3/CMS/Extbase/Annotation/Validate.php
- tests/Rector/v13/v2/MigrateRegularExpressionValidatorValidatorOptionErrorMessageRector/Fixture/fixture.php.inc
- tests/Rector/v13/v2/MigrateRegularExpressionValidatorValidatorOptionErrorMessageRector/Fixture/fixture_with_alias.php.inc
- tests/Rector/v13/v2/MigrateRegularExpressionValidatorValidatorOptionErrorMessageRector/MigrateRegularExpressionValidatorValidatorOptionErrorMessageRectorTest.php
- tests/Rector/v13/v2/MigrateRegularExpressionValidatorValidatorOptionErrorMessageRector/config/configured_rule.php
> [FEATURE] Add MigrateRegularExpressionValidatorValidatorOptionErrorMessageRector

- rules/TYPO313/v2/RemoveAddRootLineFieldsRector.php
- tests/Rector/v13/v2/RemoveAddRootLineFieldsRector/Fixture/fixture.php.inc
- tests/Rector/v13/v2/RemoveAddRootLineFieldsRector/RemoveAddRootLineFieldsRectorTest.php
- tests/Rector/v13/v2/RemoveAddRootLineFieldsRector/config/configured_rule.php
> [FEATURE] Add RemoveAddRootLineFieldsRector

- config/v13/typo3-132.php
- rules/TYPO313/v2/MigrateNamespacedShortHandValidatorRector.php
- tests/Rector/v13/v2/MigrateNamespacedShortHandValidatorRector/Fixture/fixture.php.inc
- tests/Rector/v13/v2/MigrateNamespacedShortHandValidatorRector/MigrateNamespacedShortHandValidatorRectorTest.php
- tests/Rector/v13/v2/MigrateNamespacedShortHandValidatorRector/config/configured_rule.php
> [FEATURE] Add MigrateNamespacedShortHandValidatorRector

- config/typo3-14.php
- config/v14/typo3-140.php
- rules/TYPO314/v0/DropFifthParameterForExtensionUtilityConfigurePluginRector.php
- tests/Rector/v14/v0/DropFifthParameterForExtensionUtilityConfigurePluginRector/DropFifthParameterForExtensionUtilityConfigurePluginRectorTest.php
- tests/Rector/v14/v0/DropFifthParameterForExtensionUtilityConfigurePluginRector/Fixture/fixture.php.inc
- tests/Rector/v14/v0/DropFifthParameterForExtensionUtilityConfigurePluginRector/config/configured_rule.php
> [FEATURE] Add DropFifthParameterForExtensionUtilityConfigurePluginRector

- config/v14/tca-140.php
- rules/TYPO314/v0/RemoveMaxDBListItemsRector.php
- tests/Rector/v14/v0/RemoveMaxDBListItemsRector/Fixture/fixture.php.inc
- tests/Rector/v14/v0/RemoveMaxDBListItemsRector/Fixture/fixture2.php.inc
- tests/Rector/v14/v0/RemoveMaxDBListItemsRector/RemoveMaxDBListItemsRectorTest.php
- tests/Rector/v14/v0/RemoveMaxDBListItemsRector/config/configured_rule.php
> [FEATURE] Add RemoveMaxDBListItemsRector

- config/v11/typo3-110.php
- rules/TYPO311/v0/MigrateAbstractUserAuthenticationCreateSessionIdRector.php
- stubs/TYPO3/CMS/Core/Authentication/AbstractUserAuthentication.php
- stubs/TYPO3/CMS/Core/Authentication/BackendUserAuthentication.php
- tests/Rector/v11/v0/MigrateAbstractUserAuthenticationCreateSessionIdRector/Fixture/fixture.php.inc
- tests/Rector/v11/v0/MigrateAbstractUserAuthenticationCreateSessionIdRector/Fixture/fixture_backend.php.inc
- tests/Rector/v11/v0/MigrateAbstractUserAuthenticationCreateSessionIdRector/MigrateAbstractUserAuthenticationCreateSessionIdRectorTest.php
- tests/Rector/v11/v0/MigrateAbstractUserAuthenticationCreateSessionIdRector/config/configured_rule.php
> [FEATURE] Add MigrateAbstractUserAuthenticationCreateSessionIdRector

- config/v11/typo3-110.php
- rules/TYPO311/v0/MigrateAbstractUserAuthenticationGetSessionIdRector.php
- stubs/TYPO3/CMS/Core/Authentication/AbstractUserAuthentication.php
- tests/Rector/v11/v0/MigrateAbstractUserAuthenticationGetSessionIdRector/Fixture/fixture.php.inc
- tests/Rector/v11/v0/MigrateAbstractUserAuthenticationGetSessionIdRector/Fixture/fixture_backend.php.inc
- tests/Rector/v11/v0/MigrateAbstractUserAuthenticationGetSessionIdRector/MigrateAbstractUserAuthenticationGetSessionIdRectorTest.php
- tests/Rector/v11/v0/MigrateAbstractUserAuthenticationGetSessionIdRector/config/configured_rule.php
> [FEATURE] Add MigrateAbstractUserAuthenticationGetSessionIdRector

- rules/TYPO314/v0/ExtendExtbaseValidatorsFromAbstractValidatorRector.php
- tests/Rector/v14/v0/ExtendExtbaseValidatorsFromAbstractValidatorRector/ExtendValidatorFromAbstractValidatorRectorTest.php
- tests/Rector/v14/v0/ExtendExtbaseValidatorsFromAbstractValidatorRector/Fixture/already_migrated.php.inc
- tests/Rector/v14/v0/ExtendExtbaseValidatorsFromAbstractValidatorRector/Fixture/fixture.php.inc
- tests/Rector/v14/v0/ExtendExtbaseValidatorsFromAbstractValidatorRector/Fixture/fixture_with_additional_interface.php.inc
- tests/Rector/v14/v0/ExtendExtbaseValidatorsFromAbstractValidatorRector/Source/MyCustomInterface.php
- tests/Rector/v14/v0/ExtendExtbaseValidatorsFromAbstractValidatorRector/config/configured_rule.php
> [FEATURE] Add ExtendExtbaseValidatorsFromAbstractValidatorRector

- config/v13/typo3-132.php
- rules/TYPO313/v2/MigrateMathUtilityConvertToPositiveIntegerToMaxRector.php
- stubs/TYPO3/CMS/Core/Utility/MathUtility.php
- tests/Rector/v13/v2/MigrateMathUtilityConvertToPositiveIntegerToMaxRector/Fixture/fixture.php.inc
- tests/Rector/v13/v2/MigrateMathUtilityConvertToPositiveIntegerToMaxRector/MigrateMathUtilityConvertToPositiveIntegerToMaxRectorTest.php
- tests/Rector/v13/v2/MigrateMathUtilityConvertToPositiveIntegerToMaxRector/config/configured_rule.php
> [FEATURE] Add MigrateMathUtilityConvertToPositiveIntegerToMaxRector

- rules/TYPO313/v0/MigrateAddPageTSConfigToPageTsConfigFileRector.php
- rules/TYPO313/v0/MigrateAddUserTSConfigToUserTsConfigFileRector.php
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Assertions/no_recursion/Configuration/page.tsconfig
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/Fixture/no_recursion/ext_localconf.php.inc
- tests/Rector/v13/v0/MigrateAddPageTSConfigToPageTsConfigFileRector/MigrateAddPageTSConfigToPageTsConfigFileRectorTest.php
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/Assertions/no_recursion/Configuration/user.tsconfig
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/Fixture/no_recursion/ext_localconf.php.inc
- tests/Rector/v13/v0/MigrateAddUserTSConfigToUserTsConfigFileRector/MigrateAddUserTSConfigToUserTsConfigFileRectorTest.php
> [BUGFIX] Make sure importing page/user.tsconfig doesn't get imported recursively

- config/v13/typo3-134.php
- rules/TYPO313/v4/RenameTableOptionsAndCollateConnectionConfigurationRector.php
- tests/Rector/v13/v4/RenameTableOptionsAndCollateConnectionConfigurationRector/Fixture/additional.php.inc
- tests/Rector/v13/v4/RenameTableOptionsAndCollateConnectionConfigurationRector/Fixture/fixture.php.inc
- tests/Rector/v13/v4/RenameTableOptionsAndCollateConnectionConfigurationRector/Fixture/fixture_full.php.inc
- tests/Rector/v13/v4/RenameTableOptionsAndCollateConnectionConfigurationRector/Fixture/migrated.php.inc
- tests/Rector/v13/v4/RenameTableOptionsAndCollateConnectionConfigurationRector/RenameTableOptionsAndCollateConnectionConfigurationRectorTest.php
- tests/Rector/v13/v4/RenameTableOptionsAndCollateConnectionConfigurationRector/config/configured_rule.php
> [FEATURE] Add RenameTableOptionsAndCollateConnectionConfigurationRector

- config/v13/typo3-134.php
- rules/TYPO313/v4/ReplaceTYPO3EnumTypeWithDoctrineDBALEnumTypeRector.php
- stubs/Doctrine/DBAL/Types/Types.php
- stubs/TYPO3/CMS/Core/Database/Types/EnumType.php
- tests/Rector/v13/v4/ReplaceTYPO3EnumTypeWithDoctrineDBALEnumTypeRector/Fixture/fixture.php.inc
- tests/Rector/v13/v4/ReplaceTYPO3EnumTypeWithDoctrineDBALEnumTypeRector/ReplaceTYPO3EnumTypeWithDoctrineDBALEnumTypeRectorTest.php
- tests/Rector/v13/v4/ReplaceTYPO3EnumTypeWithDoctrineDBALEnumTypeRector/config/configured_rule.php
> [FEATURE] Replace TYPO3 EnumType with Doctrine DBAL EnumType

- rules/TYPO312/v0/MigrateGetControllerContextGetUriBuilderRector.php
- tests/Rector/v12/v0/MigrateGetControllerContextGetUriBuilderRector/Fixture/bug-4497.php.inc
> [BUGFIX] First check for subclass of ActionController before method call

- rules/TYPO311/v5/SimplifyCheckboxItemsTCARector.php
- src/Helper/TcaHelperTrait.php
- tests/Rector/v11/v5/SimplifyCheckboxItemsTCARector/Fixture/bug_4541.php.inc
- tests/Rector/v11/v5/SimplifyCheckboxItemsTCARector/Fixture/fixture.php.inc
> [BUGFIX] Check for all available checkboxToggle keys

- rules/TYPO313/v3/UseTYPO3CoreViewInterfaceInExtbaseRector.php
- stubs/TYPO3/CMS/Core/View/FluidViewAdapter.php
- stubs/TYPO3/CMS/Core/View/ViewInterface.php
- stubs/TYPO3/CMS/Extbase/Mvc/Controller/ActionController.php
- stubs/TYPO3Fluid/Fluid/Core/Cache/FluidCacheInterface.php
- stubs/TYPO3Fluid/Fluid/Core/Cache/SimpleFileCache.php
- stubs/TYPO3Fluid/Fluid/Core/Exception.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/Configuration.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/ErrorHandlerInterface.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/Exception.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/RenderingContext.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/RenderingContextInterface.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/StopCompilingException.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/SyntaxTree/Expression/ExpressionException.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/TemplateCompiler.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/TemplateParser.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/TemplateProcessorInterface.php
- stubs/TYPO3Fluid/Fluid/Core/Rendering/VariableProviderInterface.php
- stubs/TYPO3Fluid/Fluid/Core/ViewHelper/Exception.php
- stubs/TYPO3Fluid/Fluid/Core/ViewHelper/ViewHelperInvoker.php
- stubs/TYPO3Fluid/Fluid/Core/ViewHelper/ViewHelperResolver.php
- stubs/TYPO3Fluid/Fluid/Core/ViewHelper/ViewHelperVariableContainer.php
- stubs/TYPO3Fluid/Fluid/Exception.php
- stubs/TYPO3Fluid/Fluid/View/Exception.php
- stubs/TYPO3Fluid/Fluid/View/TemplatePaths.php
- stubs/TYPO3Fluid/Fluid/View/ViewInterface.php
- tests/Rector/v13/v3/UseTYPO3CoreViewInterfaceInExtbaseRector/Fixture/fixture.php.inc
- tests/Rector/v13/v3/UseTYPO3CoreViewInterfaceInExtbaseRector/UseTYPO3CoreViewInterfaceInExtbaseRectorTest.php
- tests/Rector/v13/v3/UseTYPO3CoreViewInterfaceInExtbaseRector/config/configured_rule.php
> [FEATURE] Add UseTYPO3CoreViewInterfaceInExtbaseRector

- rules/TYPO313/v1/RenamePageTreeNavigationComponentIdRector.php
- tests/Rector/v13/v1/RenamePageTreeNavigationComponentIdRector/Fixture/extension2/Configuration/Backend/Modules.php.inc
- tests/Rector/v13/v1/RenamePageTreeNavigationComponentIdRector/RenamePageTreeNavigationComponentIdRectorTest.php
> [BUGFIX] Add check if the array key is an Expression

- rules/TYPO311/v0/SubstituteConstantsModeAndRequestTypeRector.php
- tests/Rector/v11/v0/SubstituteConstantsModeAndRequestTypeRector/Fixture/bug_4216.php.inc
> [BUGFIX] Fix case with TYPO3_REQUESTTYPE

- rules/TYPO311/v5/SimplifyCheckboxItemsTCARector.php
- tests/Rector/v11/v5/SimplifyCheckboxItemsTCARector/Fixture/bug_4555.php.inc
> [BUGFIX] Check for already migrated label/value keys

- rules/TYPO311/v5/SimplifyCheckboxItemsTCARector.php
- tests/Rector/v11/v5/SimplifyCheckboxItemsTCARector/Fixture/bug_4561.php.inc
> [BUGFIX] Keep items if index 1 is not defined

- config/v13/typo3-130.php
- rules/TYPO313/v0/ConvertVersionStateToEnumRector.php
- stubs/TYPO3/CMS/Core/Database/Query/Expression/ExpressionBuilder.php
- stubs/TYPO3/CMS/Core/Type/Enumeration.php
- stubs/TYPO3/CMS/Core/Versioning/VersionState.php
- tests/Rector/v13/v0/ConvertVersionStateToEnumRector/ConvertVersionStateToEnumRectorTest.php
- tests/Rector/v13/v0/ConvertVersionStateToEnumRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/ConvertVersionStateToEnumRector/config/configured_rule.php
Resolves: https://github.com/sabbelasichon/typo3-rector/issues/3656
> [FEATURE] Convert VersionState to native backed enum

- config/v13/typo3-130.php
- rules/TYPO313/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector.php
- stubs/TYPO3/CMS/Domain/Repository/PageRepository.php
- tests/Rector/v13/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector/Fixture/constant_assignment.php.inc
- tests/Rector/v13/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector/Fixture/keep_unrelated_constants.php.inc
- tests/Rector/v13/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector/Fixture/nested_array_key.php.inc
- tests/Rector/v13/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector/Fixture/remove_from_boolean_and.php.inc
- tests/Rector/v13/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector/Fixture/use_in_if_condition.php.inc
- tests/Rector/v13/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector/Fixture/used_in_if_condition_and.php.inc
- tests/Rector/v13/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector/Fixture/used_in_if_condition_or.php.inc
- tests/Rector/v13/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector/RemoveConstantPageRepositoryDoktypeRecyclerRectorTest.php
- tests/Rector/v13/v0/RemoveConstantPageRepositoryDoktypeRecyclerRector/config/configured_rule.php
> [FEATURE] Add RemoveConstantPageRepositoryDoktypeRecyclerRector

- config/v13/typo3-133.php
- rules/TYPO313/v3/MigrateFluidStandaloneMethodsRector.php
- stubs/TYPO3/CMS/Fluid/Core/ViewHelper/TagBuilder.php
- stubs/TYPO3Fluid/Fluid/Core/ViewHelper/AbstractTagBasedViewHelper.php
- stubs/TYPO3Fluid/Fluid/Core/ViewHelper/AbstractViewHelper.php
- tests/Rector/v13/v3/MigrateFluidStandaloneMethodsRector/Fixture/fixture.php.inc
- tests/Rector/v13/v3/MigrateFluidStandaloneMethodsRector/MigrateFluidStandaloneMethodsRectorTest.php
- tests/Rector/v13/v3/MigrateFluidStandaloneMethodsRector/config/configured_rule.php
> [FEATURE] Add MigrateFluidStandaloneMethodsRector

- config/v13/typo3-132.php
- rules/TYPO313/v2/MigrateTableDependentDefinitionOfColumnsOnlyRector.php
- tests/Rector/v13/v2/MigrateTableDependentDefinitionOfColumnsOnlyRector/Fixture/fixture.php.inc
- tests/Rector/v13/v2/MigrateTableDependentDefinitionOfColumnsOnlyRector/Fixture/fixture2.php.inc
- tests/Rector/v13/v2/MigrateTableDependentDefinitionOfColumnsOnlyRector/MigrateTableDependentDefinitionOfColumnsOnlyRectorTest.php
- tests/Rector/v13/v2/MigrateTableDependentDefinitionOfColumnsOnlyRector/config/configured_rule.php
> [FEATURE] Add MigrateTableDependentDefinitionOfColumnsOnlyRector

- config/v13/typo3-130.php
- rules/TYPO313/v0/RemoveSpecialPropertiesOfPageArraysRector.php
- tests/Rector/v13/v0/RemoveSpecialPropertiesOfPageArraysRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/RemoveSpecialPropertiesOfPageArraysRector/RemoveSpecialPropertiesOfPageArraysRectorTest.php
- tests/Rector/v13/v0/RemoveSpecialPropertiesOfPageArraysRector/config/configured_rule.php
> [FEATURE] Add RemoveSpecialPropertiesOfPageArraysRector

- rules/TYPO313/v4/MigratePluginContentElementAndPluginSubtypesRector.php
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesRector/Fixture/extension3/ext_localconf.php.inc
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesRector/Fixture/extension4/Configuration/TCA/Overrides/tt_content.php.inc
- tests/Rector/v13/v4/MigratePluginContentElementAndPluginSubtypesRector/MigratePluginContentElementAndPluginSubtypesRectorTest.php
> [BUGFIX] Add more checks to skip rule

- config/v13/typo3-133.php
- rules/TYPO313/v3/MigrateTypoScriptFrontendControllerAddCacheTagsAndGetPageCacheTagsRector.php
- stubs/TYPO3/CMS/Core/Cache/CacheTag.php
- stubs/TYPO3/CMS/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v13/v3/MigrateTypoScriptFrontendControllerAddCacheTagsAndGetPageCacheTagsRector/Fixture/addCacheTags.php.inc
- tests/Rector/v13/v3/MigrateTypoScriptFrontendControllerAddCacheTagsAndGetPageCacheTagsRector/Fixture/addCacheTags_in_extbase.php.inc
- tests/Rector/v13/v3/MigrateTypoScriptFrontendControllerAddCacheTagsAndGetPageCacheTagsRector/Fixture/getPageCacheTags.php.inc
- tests/Rector/v13/v3/MigrateTypoScriptFrontendControllerAddCacheTagsAndGetPageCacheTagsRector/Fixture/getPageCacheTags_in_extbase.php.inc
- tests/Rector/v13/v3/MigrateTypoScriptFrontendControllerAddCacheTagsAndGetPageCacheTagsRector/MigrateTypoScriptFrontendControllerAddCacheTagsAndGetPageCacheTagsRectorTest.php
- tests/Rector/v13/v3/MigrateTypoScriptFrontendControllerAddCacheTagsAndGetPageCacheTagsRector/config/configured_rule.php
> [BUGFIX] Add MigrateTypoScriptFrontendControllerAddCacheTagsAndGetPageCacheTagsRector

- config/v13/typo3-134.php
- rules/TYPO313/v4/RequireATemplateFileNameInExtbaseModuleTemplateRenderingRector.php
- stubs/TYPO3/CMS/Backend/Template/ModuleTemplate.php
- tests/Rector/v13/v4/RequireATemplateFileNameInExtbaseModuleTemplateRenderingRector/Fixture/fixture.php.inc
- tests/Rector/v13/v4/RequireATemplateFileNameInExtbaseModuleTemplateRenderingRector/RequireATemplateFileNameInExtbaseModuleTemplateRenderingRectorTest.php
- tests/Rector/v13/v4/RequireATemplateFileNameInExtbaseModuleTemplateRenderingRector/config/configured_rule.php
> [BUGFIX] Add RequireATemplateFileNameInExtbaseModuleTemplateRenderingRector

- config/v13/typo3-134.php
- phpstan.neon
- rules/TYPO313/v4/MigrateDataProviderContextGettersAndSettersRector.php
- stubs/TYPO3/CMS/Backend/View/BackendLayout/DataProviderContext.php
- tests/Rector/v13/v4/MigrateDataProviderContextGettersAndSettersRector/Fixture/fixture_chained.php.inc
- tests/Rector/v13/v4/MigrateDataProviderContextGettersAndSettersRector/Fixture/fixture_individual.php.inc
- tests/Rector/v13/v4/MigrateDataProviderContextGettersAndSettersRector/Fixture/getters_and_setters.php.inc
- tests/Rector/v13/v4/MigrateDataProviderContextGettersAndSettersRector/MigrateDataProviderContextGettersAndSettersRectorTest.php
- tests/Rector/v13/v4/MigrateDataProviderContextGettersAndSettersRector/config/configured_rule.php
> [BUGFIX] Add MigrateDataProviderContextGettersAndSettersRector

- config/v13/strict-types.php
- ecs.php
- stubs/TYPO3/CMS/Extbase/Persistence/PersistenceManagerInterface.php
> [FEATURE] Add more strict types for extbase

- config/v13/typo3-130.php
- rules/TYPO313/v0/MigrateTypoScriptFrontendControllerReadOnlyPropertiesRector.php
- stubs/TYPO3/CMS/Frontend/Controller/TypoScriptFrontendController.php
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerReadOnlyPropertiesRector/Fixture/extbase.php.inc
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerReadOnlyPropertiesRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerReadOnlyPropertiesRector/MigrateTypoScriptFrontendControllerReadOnlyPropertiesRectorTest.php
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerReadOnlyPropertiesRector/config/configured_rule.php
> [FEATURE] Add MigrateTypoScriptFrontendControllerReadOnlyPropertiesRector

- config/v13/typo3-130.php
- rules/TYPO313/v0/MigrateTypoScriptFrontendControllerSysPageRector.php
- stubs/TYPO3/CMS/Core/Domain/Repository/PageRepository.php
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerSysPageRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerSysPageRector/MigrateTypoScriptFrontendControllerSysPageRectorTest.php
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerSysPageRector/config/configured_rule.php
> [FEATURE] Add MigrateTypoScriptFrontendControllerSysPageRector

- config/v13/typo3-130.php
- rules/TYPO313/v0/MigrateTypoScriptFrontendControllerFeUserMethodsRector.php
- stubs/TYPO3/CMS/Frontend/Authentication/FrontendUserAuthentication.php
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerFeUserMethodsRector/Fixture/extbase.php.inc
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerFeUserMethodsRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerFeUserMethodsRector/MigrateTypoScriptFrontendControllerFeUserMethodsRectorTest.php
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerFeUserMethodsRector/config/configured_rule.php
> [FEATURE] Add MigrateTypoScriptFrontendControllerFeUserMethodsRector

- config/v13/typo3-133.php
- rules/TYPO313/v3/MigrateBackendUtilityGetTcaFieldConfigurationRector.php
- stubs/TYPO3/CMS/Backend/Utility/BackendUtility.php
- stubs/TYPO3/CMS/Core/DataHandling/TableColumnType.php
- stubs/TYPO3/CMS/Core/Schema/Field/FieldTranslationBehaviour.php
- stubs/TYPO3/CMS/Core/Schema/Field/FieldTypeInterface.php
- stubs/TYPO3/CMS/Core/Schema/TcaSchema.php
- stubs/TYPO3/CMS/Core/Schema/TcaSchemaFactory.php
- stubs/TYPO3/CMS/Frontend/Page/PageRepositoryGetRecordOverlayHookInterface.php
- tests/Rector/v13/v3/MigrateBackendUtilityGetTcaFieldConfigurationRector/Fixture/fixture.php.inc
- tests/Rector/v13/v3/MigrateBackendUtilityGetTcaFieldConfigurationRector/MigrateBackendUtilityGetTcaFieldConfigurationRectorTest.php
- tests/Rector/v13/v3/MigrateBackendUtilityGetTcaFieldConfigurationRector/config/configured_rule.php
> [FEATURE] Add MigrateBackendUtilityGetTcaFieldConfigurationRector

- docs/all_rectors_overview.md
- rules/TYPO314/v0/RemoveIsStaticControlOptionRector.php
- tests/Rector/v14/v0/RemoveIsStaticControlOptionRector/Fixture/fixture.php.inc
- tests/Rector/v14/v0/RemoveIsStaticControlOptionRector/RemoveIsStaticControlOptionRectorTest.php
- tests/Rector/v14/v0/RemoveIsStaticControlOptionRector/config/configured_rule.php
> [FEATURE] Add RemoveIsStaticControlOptionRector

- config/v13/typo3-130.php
- docs/all_rectors_overview.md
- rules/TYPO313/v0/MigrateTypoScriptFrontendControllerFeUserRector.php
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerFeUserRector/Fixture/extbase.php.inc
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerFeUserRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerFeUserRector/Fixture/ignore_assignment.php.inc
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerFeUserRector/MigrateTypoScriptFrontendControllerFeUserRectorTest.php
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerFeUserRector/config/configured_rule.php
> [FEATURE] Add MigrateTypoScriptFrontendControllerFeUserRector

- config/v12/typo3-120.php
- docs/all_rectors_overview.md
- rules/TYPO312/v0/UseLanguageAspectInExtbasePersistenceRector.php
- stubs/TYPO3/CMS/Core/Context/LanguageAspect.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/Qom/ComparisonInterface.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/Query.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/QuerySettingsInterface.php
- stubs/TYPO3/CMS/Extbase/Persistence/Generic/Typo3QuerySettings.php
- tests/Rector/v12/v0/UseLanguageAspectInExtbasePersistenceRector/Fixture/fixture.php.inc
- tests/Rector/v12/v0/UseLanguageAspectInExtbasePersistenceRector/UseLanguageAspectInExtbasePersistenceRectorTest.php
- tests/Rector/v12/v0/UseLanguageAspectInExtbasePersistenceRector/config/configured_rule.php
> [FEATURE] Add UseLanguageAspectInExtbasePersistenceRector

- config/v13/typo3-130.php
- docs/all_rectors_overview.md
- rules/TYPO313/v0/MigrateDuplicationBehaviorClassRector.php
- stubs/TYPO3/CMS/Core/Resource/AbstractFile.php
- stubs/TYPO3/CMS/Core/Resource/DuplicationBehavior.php
- stubs/TYPO3/CMS/Core/Resource/Enum/DuplicationBehavior.php
- tests/Rector/v13/v0/MigrateDuplicationBehaviorClassRector/Fixture/fixture.php.inc
- tests/Rector/v13/v0/MigrateDuplicationBehaviorClassRector/MigrateDuplicationBehaviorClassRectorTest.php
- tests/Rector/v13/v0/MigrateDuplicationBehaviorClassRector/config/configured_rule.php
> [FEATURE] Add MigrateDuplicationBehaviorClassRector

- rules/TYPO310/v0/UseControllerClassesInExtbasePluginsAndModulesRector.php
(cherry picked from commit 5ac39f205ad19375f7960dbda47ad64d989c044f)
> [BUGFIX] Return node if there are changes

- rules/TYPO313/v0/MigrateTypoScriptFrontendControllerMethodCallsRector.php
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerMethodCallsRector/Fixture/extbase.php.inc
- tests/Rector/v13/v0/MigrateTypoScriptFrontendControllerMethodCallsRector/Fixture/fixture.php.inc
> [BUGFIX] Correct migration for $GLOBALS['TSFE']->getLanguage();

- config/v14/typo3-140.php
- docs/all_rectors_overview.md
- rules/TYPO314/v0/MigrateEnvironmentGetComposerRootPathRector.php
- stubs/TYPO3/CMS/Core/Core/Environment.php
- tests/Rector/v14/v0/MigrateEnvironmentGetComposerRootPathRector/Fixture/fixture.php.inc
- tests/Rector/v14/v0/MigrateEnvironmentGetComposerRootPathRector/MigrateEnvironmentGetComposerRootPathRectorTest.php
- tests/Rector/v14/v0/MigrateEnvironmentGetComposerRootPathRector/config/configured_rule.php
> [FEATURE] Add MigrateEnvironmentGetComposerRootPathRector

- config/v14/tca-140.php
- docs/all_rectors_overview.md
- rules/TYPO310/v0/RemoveShowRemovedLocalizationRecordsRector.php
- rules/TYPO314/v0/MigrateObsoleteCharsetInSanitizeFileNameRector.php
- rules/TYPO314/v0/RemoveFieldSearchConfigOptionsRector.php
- rules/TYPO314/v0/RemoveParameterInAuthenticationServiceRector.php
- tests/Rector/v14/v0/RemoveFieldSearchConfigOptionsRector/Fixture/fixture.php.inc
- tests/Rector/v14/v0/RemoveFieldSearchConfigOptionsRector/RemoveFieldSearchConfigOptionsRectorTest.php
- tests/Rector/v14/v0/RemoveFieldSearchConfigOptionsRector/config/configured_rule.php
> [FEATURE] Add RemoveFieldSearchConfigOptionsRector
